package sernet.gs.reveng;

// Generated Jun 5, 2015 1:28:30 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * BrBericht generated by hbm2java
 */
public class BrBericht implements java.io.Serializable {

	private BrBerichtId id;
	private MSprache MSprache;
	private MMetatyp MMetatyp;
	private SysImport sysImport;
	private Integer styId;
	private String name;
	private String dialog;
	private int option1;
	private int option2;
	private int option3;
	private int option4;
	private int option5;
	private int option6;
	private boolean autoRecht;
	private String anwendung;
	private String parameter;
	private String sortMas;
	private String sortBau;
	private String extension;
	private String guid;
	private Date erstelltAm;
	private String erstelltDurch;
	private Date geaendertAm;
	private String geaendertDurch;
	private Set rechteRolleBerichts = new HashSet(0);
	private Set rechteAnwenders = new HashSet(0);
	private Set brFilters = new HashSet(0);
	private Set brAttributs = new HashSet(0);

	public BrBericht() {
	}

	public BrBericht(BrBerichtId id, MSprache MSprache, MMetatyp MMetatyp,
			SysImport sysImport, String name, String dialog, int option1,
			int option2, int option3, int option4, int option5, int option6,
			boolean autoRecht, String anwendung, String parameter,
			String sortMas, String sortBau, String extension, String guid,
			Date erstelltAm, String erstelltDurch) {
		this.id = id;
		this.MSprache = MSprache;
		this.MMetatyp = MMetatyp;
		this.sysImport = sysImport;
		this.name = name;
		this.dialog = dialog;
		this.option1 = option1;
		this.option2 = option2;
		this.option3 = option3;
		this.option4 = option4;
		this.option5 = option5;
		this.option6 = option6;
		this.autoRecht = autoRecht;
		this.anwendung = anwendung;
		this.parameter = parameter;
		this.sortMas = sortMas;
		this.sortBau = sortBau;
		this.extension = extension;
		this.guid = guid;
		this.erstelltAm = erstelltAm;
		this.erstelltDurch = erstelltDurch;
	}

	public BrBericht(BrBerichtId id, MSprache MSprache, MMetatyp MMetatyp,
			SysImport sysImport, Integer styId, String name, String dialog,
			int option1, int option2, int option3, int option4, int option5,
			int option6, boolean autoRecht, String anwendung, String parameter,
			String sortMas, String sortBau, String extension, String guid,
			Date erstelltAm, String erstelltDurch, Date geaendertAm,
			String geaendertDurch, Set rechteRolleBerichts,
			Set rechteAnwenders, Set brFilters, Set brAttributs) {
		this.id = id;
		this.MSprache = MSprache;
		this.MMetatyp = MMetatyp;
		this.sysImport = sysImport;
		this.styId = styId;
		this.name = name;
		this.dialog = dialog;
		this.option1 = option1;
		this.option2 = option2;
		this.option3 = option3;
		this.option4 = option4;
		this.option5 = option5;
		this.option6 = option6;
		this.autoRecht = autoRecht;
		this.anwendung = anwendung;
		this.parameter = parameter;
		this.sortMas = sortMas;
		this.sortBau = sortBau;
		this.extension = extension;
		this.guid = guid;
		this.erstelltAm = erstelltAm;
		this.erstelltDurch = erstelltDurch;
		this.geaendertAm = geaendertAm;
		this.geaendertDurch = geaendertDurch;
		this.rechteRolleBerichts = rechteRolleBerichts;
		this.rechteAnwenders = rechteAnwenders;
		this.brFilters = brFilters;
		this.brAttributs = brAttributs;
	}

	public BrBerichtId getId() {
		return this.id;
	}

	public void setId(BrBerichtId id) {
		this.id = id;
	}

	public MSprache getMSprache() {
		return this.MSprache;
	}

	public void setMSprache(MSprache MSprache) {
		this.MSprache = MSprache;
	}

	public MMetatyp getMMetatyp() {
		return this.MMetatyp;
	}

	public void setMMetatyp(MMetatyp MMetatyp) {
		this.MMetatyp = MMetatyp;
	}

	public SysImport getSysImport() {
		return this.sysImport;
	}

	public void setSysImport(SysImport sysImport) {
		this.sysImport = sysImport;
	}

	public Integer getStyId() {
		return this.styId;
	}

	public void setStyId(Integer styId) {
		this.styId = styId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDialog() {
		return this.dialog;
	}

	public void setDialog(String dialog) {
		this.dialog = dialog;
	}

	public int getOption1() {
		return this.option1;
	}

	public void setOption1(int option1) {
		this.option1 = option1;
	}

	public int getOption2() {
		return this.option2;
	}

	public void setOption2(int option2) {
		this.option2 = option2;
	}

	public int getOption3() {
		return this.option3;
	}

	public void setOption3(int option3) {
		this.option3 = option3;
	}

	public int getOption4() {
		return this.option4;
	}

	public void setOption4(int option4) {
		this.option4 = option4;
	}

	public int getOption5() {
		return this.option5;
	}

	public void setOption5(int option5) {
		this.option5 = option5;
	}

	public int getOption6() {
		return this.option6;
	}

	public void setOption6(int option6) {
		this.option6 = option6;
	}

	public boolean isAutoRecht() {
		return this.autoRecht;
	}

	public void setAutoRecht(boolean autoRecht) {
		this.autoRecht = autoRecht;
	}

	public String getAnwendung() {
		return this.anwendung;
	}

	public void setAnwendung(String anwendung) {
		this.anwendung = anwendung;
	}

	public String getParameter() {
		return this.parameter;
	}

	public void setParameter(String parameter) {
		this.parameter = parameter;
	}

	public String getSortMas() {
		return this.sortMas;
	}

	public void setSortMas(String sortMas) {
		this.sortMas = sortMas;
	}

	public String getSortBau() {
		return this.sortBau;
	}

	public void setSortBau(String sortBau) {
		this.sortBau = sortBau;
	}

	public String getExtension() {
		return this.extension;
	}

	public void setExtension(String extension) {
		this.extension = extension;
	}

	public String getGuid() {
		return this.guid;
	}

	public void setGuid(String guid) {
		this.guid = guid;
	}

	public Date getErstelltAm() {
		return this.erstelltAm;
	}

	public void setErstelltAm(Date erstelltAm) {
		this.erstelltAm = erstelltAm;
	}

	public String getErstelltDurch() {
		return this.erstelltDurch;
	}

	public void setErstelltDurch(String erstelltDurch) {
		this.erstelltDurch = erstelltDurch;
	}

	public Date getGeaendertAm() {
		return this.geaendertAm;
	}

	public void setGeaendertAm(Date geaendertAm) {
		this.geaendertAm = geaendertAm;
	}

	public String getGeaendertDurch() {
		return this.geaendertDurch;
	}

	public void setGeaendertDurch(String geaendertDurch) {
		this.geaendertDurch = geaendertDurch;
	}

	public Set getRechteRolleBerichts() {
		return this.rechteRolleBerichts;
	}

	public void setRechteRolleBerichts(Set rechteRolleBerichts) {
		this.rechteRolleBerichts = rechteRolleBerichts;
	}

	public Set getRechteAnwenders() {
		return this.rechteAnwenders;
	}

	public void setRechteAnwenders(Set rechteAnwenders) {
		this.rechteAnwenders = rechteAnwenders;
	}

	public Set getBrFilters() {
		return this.brFilters;
	}

	public void setBrFilters(Set brFilters) {
		this.brFilters = brFilters;
	}

	public Set getBrAttributs() {
		return this.brAttributs;
	}

	public void setBrAttributs(Set brAttributs) {
		this.brAttributs = brAttributs;
	}

}
