package sernet.gs.reveng;

// Generated Jun 5, 2015 1:28:30 PM by Hibernate Tools 3.4.0.CR1

/**
 * DtsPrecedence generated by hbm2java
 */
public class DtsPrecedence implements java.io.Serializable {

	private DtsPrecedenceId id;
	private DtsStep dtsStepByFkDtsPrecedenceDtsStep2;
	private DtsStep dtsStepByFkDtsPrecedenceDtsStep;
	private byte basis;
	private byte value;

	public DtsPrecedence() {
	}

	public DtsPrecedence(DtsPrecedenceId id,
			DtsStep dtsStepByFkDtsPrecedenceDtsStep2,
			DtsStep dtsStepByFkDtsPrecedenceDtsStep, byte basis, byte value) {
		this.id = id;
		this.dtsStepByFkDtsPrecedenceDtsStep2 = dtsStepByFkDtsPrecedenceDtsStep2;
		this.dtsStepByFkDtsPrecedenceDtsStep = dtsStepByFkDtsPrecedenceDtsStep;
		this.basis = basis;
		this.value = value;
	}

	public DtsPrecedenceId getId() {
		return this.id;
	}

	public void setId(DtsPrecedenceId id) {
		this.id = id;
	}

	public DtsStep getDtsStepByFkDtsPrecedenceDtsStep2() {
		return this.dtsStepByFkDtsPrecedenceDtsStep2;
	}

	public void setDtsStepByFkDtsPrecedenceDtsStep2(
			DtsStep dtsStepByFkDtsPrecedenceDtsStep2) {
		this.dtsStepByFkDtsPrecedenceDtsStep2 = dtsStepByFkDtsPrecedenceDtsStep2;
	}

	public DtsStep getDtsStepByFkDtsPrecedenceDtsStep() {
		return this.dtsStepByFkDtsPrecedenceDtsStep;
	}

	public void setDtsStepByFkDtsPrecedenceDtsStep(
			DtsStep dtsStepByFkDtsPrecedenceDtsStep) {
		this.dtsStepByFkDtsPrecedenceDtsStep = dtsStepByFkDtsPrecedenceDtsStep;
	}

	public byte getBasis() {
		return this.basis;
	}

	public void setBasis(byte basis) {
		this.basis = basis;
	}

	public byte getValue() {
		return this.value;
	}

	public void setValue(byte value) {
		this.value = value;
	}

}
