package sernet.gs.reveng;

// Generated Jun 5, 2015 1:28:30 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * DtsPackage generated by hbm2java
 */
public class DtsPackage implements java.io.Serializable {

	private String dtsId;
	private String name;
	private String description;
	private boolean writecompletionstatustonteventlog;
	private boolean failonerror;
	private int packagepriorityclass;
	private int maxconcurrentsteps;
	private int lineageoptions;
	private boolean usetransaction;
	private int transactionisolationlevel;
	private boolean autocommittransaction;
	private int repositorymetadataoptions;
	private boolean useoledbservicecomponents;
	private boolean logtosqlserver;
	private int logserverflags;
	private boolean failpackageonlogfailure;
	private boolean explicitglobalvariables;
	private int packagetype;
	private Set dtsSteps = new HashSet(0);
	private Set dtsVariables = new HashSet(0);

	public DtsPackage() {
	}

	public DtsPackage(String dtsId, String name,
			boolean writecompletionstatustonteventlog, boolean failonerror,
			int packagepriorityclass, int maxconcurrentsteps,
			int lineageoptions, boolean usetransaction,
			int transactionisolationlevel, boolean autocommittransaction,
			int repositorymetadataoptions, boolean useoledbservicecomponents,
			boolean logtosqlserver, int logserverflags,
			boolean failpackageonlogfailure, boolean explicitglobalvariables,
			int packagetype) {
		this.dtsId = dtsId;
		this.name = name;
		this.writecompletionstatustonteventlog = writecompletionstatustonteventlog;
		this.failonerror = failonerror;
		this.packagepriorityclass = packagepriorityclass;
		this.maxconcurrentsteps = maxconcurrentsteps;
		this.lineageoptions = lineageoptions;
		this.usetransaction = usetransaction;
		this.transactionisolationlevel = transactionisolationlevel;
		this.autocommittransaction = autocommittransaction;
		this.repositorymetadataoptions = repositorymetadataoptions;
		this.useoledbservicecomponents = useoledbservicecomponents;
		this.logtosqlserver = logtosqlserver;
		this.logserverflags = logserverflags;
		this.failpackageonlogfailure = failpackageonlogfailure;
		this.explicitglobalvariables = explicitglobalvariables;
		this.packagetype = packagetype;
	}

	public DtsPackage(String dtsId, String name, String description,
			boolean writecompletionstatustonteventlog, boolean failonerror,
			int packagepriorityclass, int maxconcurrentsteps,
			int lineageoptions, boolean usetransaction,
			int transactionisolationlevel, boolean autocommittransaction,
			int repositorymetadataoptions, boolean useoledbservicecomponents,
			boolean logtosqlserver, int logserverflags,
			boolean failpackageonlogfailure, boolean explicitglobalvariables,
			int packagetype, Set dtsSteps, Set dtsVariables) {
		this.dtsId = dtsId;
		this.name = name;
		this.description = description;
		this.writecompletionstatustonteventlog = writecompletionstatustonteventlog;
		this.failonerror = failonerror;
		this.packagepriorityclass = packagepriorityclass;
		this.maxconcurrentsteps = maxconcurrentsteps;
		this.lineageoptions = lineageoptions;
		this.usetransaction = usetransaction;
		this.transactionisolationlevel = transactionisolationlevel;
		this.autocommittransaction = autocommittransaction;
		this.repositorymetadataoptions = repositorymetadataoptions;
		this.useoledbservicecomponents = useoledbservicecomponents;
		this.logtosqlserver = logtosqlserver;
		this.logserverflags = logserverflags;
		this.failpackageonlogfailure = failpackageonlogfailure;
		this.explicitglobalvariables = explicitglobalvariables;
		this.packagetype = packagetype;
		this.dtsSteps = dtsSteps;
		this.dtsVariables = dtsVariables;
	}

	public String getDtsId() {
		return this.dtsId;
	}

	public void setDtsId(String dtsId) {
		this.dtsId = dtsId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public boolean isWritecompletionstatustonteventlog() {
		return this.writecompletionstatustonteventlog;
	}

	public void setWritecompletionstatustonteventlog(
			boolean writecompletionstatustonteventlog) {
		this.writecompletionstatustonteventlog = writecompletionstatustonteventlog;
	}

	public boolean isFailonerror() {
		return this.failonerror;
	}

	public void setFailonerror(boolean failonerror) {
		this.failonerror = failonerror;
	}

	public int getPackagepriorityclass() {
		return this.packagepriorityclass;
	}

	public void setPackagepriorityclass(int packagepriorityclass) {
		this.packagepriorityclass = packagepriorityclass;
	}

	public int getMaxconcurrentsteps() {
		return this.maxconcurrentsteps;
	}

	public void setMaxconcurrentsteps(int maxconcurrentsteps) {
		this.maxconcurrentsteps = maxconcurrentsteps;
	}

	public int getLineageoptions() {
		return this.lineageoptions;
	}

	public void setLineageoptions(int lineageoptions) {
		this.lineageoptions = lineageoptions;
	}

	public boolean isUsetransaction() {
		return this.usetransaction;
	}

	public void setUsetransaction(boolean usetransaction) {
		this.usetransaction = usetransaction;
	}

	public int getTransactionisolationlevel() {
		return this.transactionisolationlevel;
	}

	public void setTransactionisolationlevel(int transactionisolationlevel) {
		this.transactionisolationlevel = transactionisolationlevel;
	}

	public boolean isAutocommittransaction() {
		return this.autocommittransaction;
	}

	public void setAutocommittransaction(boolean autocommittransaction) {
		this.autocommittransaction = autocommittransaction;
	}

	public int getRepositorymetadataoptions() {
		return this.repositorymetadataoptions;
	}

	public void setRepositorymetadataoptions(int repositorymetadataoptions) {
		this.repositorymetadataoptions = repositorymetadataoptions;
	}

	public boolean isUseoledbservicecomponents() {
		return this.useoledbservicecomponents;
	}

	public void setUseoledbservicecomponents(boolean useoledbservicecomponents) {
		this.useoledbservicecomponents = useoledbservicecomponents;
	}

	public boolean isLogtosqlserver() {
		return this.logtosqlserver;
	}

	public void setLogtosqlserver(boolean logtosqlserver) {
		this.logtosqlserver = logtosqlserver;
	}

	public int getLogserverflags() {
		return this.logserverflags;
	}

	public void setLogserverflags(int logserverflags) {
		this.logserverflags = logserverflags;
	}

	public boolean isFailpackageonlogfailure() {
		return this.failpackageonlogfailure;
	}

	public void setFailpackageonlogfailure(boolean failpackageonlogfailure) {
		this.failpackageonlogfailure = failpackageonlogfailure;
	}

	public boolean isExplicitglobalvariables() {
		return this.explicitglobalvariables;
	}

	public void setExplicitglobalvariables(boolean explicitglobalvariables) {
		this.explicitglobalvariables = explicitglobalvariables;
	}

	public int getPackagetype() {
		return this.packagetype;
	}

	public void setPackagetype(int packagetype) {
		this.packagetype = packagetype;
	}

	public Set getDtsSteps() {
		return this.dtsSteps;
	}

	public void setDtsSteps(Set dtsSteps) {
		this.dtsSteps = dtsSteps;
	}

	public Set getDtsVariables() {
		return this.dtsVariables;
	}

	public void setDtsVariables(Set dtsVariables) {
		this.dtsVariables = dtsVariables;
	}

}
