package sernet.gs.reveng;

// Generated Jun 5, 2015 1:28:30 PM by Hibernate Tools 3.4.0.CR1

/**
 * DtsTaskColcopyId generated by hbm2java
 */
public class DtsTaskColcopyId implements java.io.Serializable {

	private String dtsId;
	private int dtsStep;
	private String nameSrc;

	public DtsTaskColcopyId() {
	}

	public DtsTaskColcopyId(String dtsId, int dtsStep, String nameSrc) {
		this.dtsId = dtsId;
		this.dtsStep = dtsStep;
		this.nameSrc = nameSrc;
	}

	public String getDtsId() {
		return this.dtsId;
	}

	public void setDtsId(String dtsId) {
		this.dtsId = dtsId;
	}

	public int getDtsStep() {
		return this.dtsStep;
	}

	public void setDtsStep(int dtsStep) {
		this.dtsStep = dtsStep;
	}

	public String getNameSrc() {
		return this.nameSrc;
	}

	public void setNameSrc(String nameSrc) {
		this.nameSrc = nameSrc;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DtsTaskColcopyId))
			return false;
		DtsTaskColcopyId castOther = (DtsTaskColcopyId) other;

		return ((this.getDtsId() == castOther.getDtsId()) || (this.getDtsId() != null
				&& castOther.getDtsId() != null && this.getDtsId().equals(
				castOther.getDtsId())))
				&& (this.getDtsStep() == castOther.getDtsStep())
				&& ((this.getNameSrc() == castOther.getNameSrc()) || (this
						.getNameSrc() != null && castOther.getNameSrc() != null && this
						.getNameSrc().equals(castOther.getNameSrc())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getDtsId() == null ? 0 : this.getDtsId().hashCode());
		result = 37 * result + this.getDtsStep();
		result = 37 * result
				+ (getNameSrc() == null ? 0 : this.getNameSrc().hashCode());
		return result;
	}

}
