package sernet.gs.reveng;

// Generated Jun 5, 2015 1:28:30 PM by Hibernate Tools 3.4.0.CR1

/**
 * DtsVariableId generated by hbm2java
 */
public class DtsVariableId implements java.io.Serializable {

	private String dtsId;
	private String name;

	public DtsVariableId() {
	}

	public DtsVariableId(String dtsId, String name) {
		this.dtsId = dtsId;
		this.name = name;
	}

	public String getDtsId() {
		return this.dtsId;
	}

	public void setDtsId(String dtsId) {
		this.dtsId = dtsId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DtsVariableId))
			return false;
		DtsVariableId castOther = (DtsVariableId) other;

		return ((this.getDtsId() == castOther.getDtsId()) || (this.getDtsId() != null
				&& castOther.getDtsId() != null && this.getDtsId().equals(
				castOther.getDtsId())))
				&& ((this.getName() == castOther.getName()) || (this.getName() != null
						&& castOther.getName() != null && this.getName()
						.equals(castOther.getName())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getDtsId() == null ? 0 : this.getDtsId().hashCode());
		result = 37 * result
				+ (getName() == null ? 0 : this.getName().hashCode());
		return result;
	}

}
