package sernet.gs.reveng;

// Generated Jun 5, 2015 1:28:30 PM by Hibernate Tools 3.4.0.CR1

/**
 * FilterResZot generated by hbm2java
 */
public class FilterResZot implements java.io.Serializable {

	private FilterResZotId id;
	private short spid;

	public FilterResZot() {
	}

	public FilterResZot(FilterResZotId id, short spid) {
		this.id = id;
		this.spid = spid;
	}

	public FilterResZotId getId() {
		return this.id;
	}

	public void setId(FilterResZotId id) {
		this.id = id;
	}

	public short getSpid() {
		return this.spid;
	}

	public void setSpid(short spid) {
		this.spid = spid;
	}

}
