package sernet.gs.reveng;

// Generated Jun 5, 2015 1:28:30 PM by Hibernate Tools 3.4.0.CR1

/**
 * FilterSuchenFelderTxtId generated by hbm2java
 */
public class FilterSuchenFelderTxtId implements java.io.Serializable {

	private int fflId;
	private short sprId;

	public FilterSuchenFelderTxtId() {
	}

	public FilterSuchenFelderTxtId(int fflId, short sprId) {
		this.fflId = fflId;
		this.sprId = sprId;
	}

	public int getFflId() {
		return this.fflId;
	}

	public void setFflId(int fflId) {
		this.fflId = fflId;
	}

	public short getSprId() {
		return this.sprId;
	}

	public void setSprId(short sprId) {
		this.sprId = sprId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FilterSuchenFelderTxtId))
			return false;
		FilterSuchenFelderTxtId castOther = (FilterSuchenFelderTxtId) other;

		return (this.getFflId() == castOther.getFflId())
				&& (this.getSprId() == castOther.getSprId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getFflId();
		result = 37 * result + this.getSprId();
		return result;
	}

}
