package sernet.gs.reveng;

// Generated Jun 5, 2015 1:28:30 PM by Hibernate Tools 3.4.0.CR1

/**
 * FilterResBau generated by hbm2java
 */
public class FilterResBau implements java.io.Serializable {

	private FilterResBauId id;
	private short spid;

	public FilterResBau() {
	}

	public FilterResBau(FilterResBauId id, short spid) {
		this.id = id;
		this.spid = spid;
	}

	public FilterResBauId getId() {
		return this.id;
	}

	public void setId(FilterResBauId id) {
		this.id = id;
	}

	public short getSpid() {
		return this.spid;
	}

	public void setSpid(short spid) {
		this.spid = spid;
	}

}
