package sernet.gs.reveng;

// Generated Jun 5, 2015 1:28:30 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * FilterSuchenFelder generated by hbm2java
 */
public class FilterSuchenFelder implements java.io.Serializable {

	private int fflId;
	private FilterInnerjoin filterInnerjoin;
	private FilterVorschlag filterVorschlag;
	private String sucheId;
	private byte fflLevel;
	private String fflTable;
	private String fflField1;
	private String fflField2;
	private String fflField3;
	private String fflType;
	private String fflWhere;
	private String fflCompare;
	private Boolean fflOrderby;
	private boolean anzeigen;
	private Set filterRows = new HashSet(0);
	private Set filterBasises = new HashSet(0);
	private Set filterSuchenFelderTxts = new HashSet(0);
	private Set filterSuchenSeite1s = new HashSet(0);

	public FilterSuchenFelder() {
	}

	public FilterSuchenFelder(int fflId, String sucheId, byte fflLevel,
			String fflTable, String fflField1, String fflType, boolean anzeigen) {
		this.fflId = fflId;
		this.sucheId = sucheId;
		this.fflLevel = fflLevel;
		this.fflTable = fflTable;
		this.fflField1 = fflField1;
		this.fflType = fflType;
		this.anzeigen = anzeigen;
	}

	public FilterSuchenFelder(int fflId, FilterInnerjoin filterInnerjoin,
			FilterVorschlag filterVorschlag, String sucheId, byte fflLevel,
			String fflTable, String fflField1, String fflField2,
			String fflField3, String fflType, String fflWhere,
			String fflCompare, Boolean fflOrderby, boolean anzeigen,
			Set filterRows, Set filterBasises, Set filterSuchenFelderTxts,
			Set filterSuchenSeite1s) {
		this.fflId = fflId;
		this.filterInnerjoin = filterInnerjoin;
		this.filterVorschlag = filterVorschlag;
		this.sucheId = sucheId;
		this.fflLevel = fflLevel;
		this.fflTable = fflTable;
		this.fflField1 = fflField1;
		this.fflField2 = fflField2;
		this.fflField3 = fflField3;
		this.fflType = fflType;
		this.fflWhere = fflWhere;
		this.fflCompare = fflCompare;
		this.fflOrderby = fflOrderby;
		this.anzeigen = anzeigen;
		this.filterRows = filterRows;
		this.filterBasises = filterBasises;
		this.filterSuchenFelderTxts = filterSuchenFelderTxts;
		this.filterSuchenSeite1s = filterSuchenSeite1s;
	}

	public int getFflId() {
		return this.fflId;
	}

	public void setFflId(int fflId) {
		this.fflId = fflId;
	}

	public FilterInnerjoin getFilterInnerjoin() {
		return this.filterInnerjoin;
	}

	public void setFilterInnerjoin(FilterInnerjoin filterInnerjoin) {
		this.filterInnerjoin = filterInnerjoin;
	}

	public FilterVorschlag getFilterVorschlag() {
		return this.filterVorschlag;
	}

	public void setFilterVorschlag(FilterVorschlag filterVorschlag) {
		this.filterVorschlag = filterVorschlag;
	}

	public String getSucheId() {
		return this.sucheId;
	}

	public void setSucheId(String sucheId) {
		this.sucheId = sucheId;
	}

	public byte getFflLevel() {
		return this.fflLevel;
	}

	public void setFflLevel(byte fflLevel) {
		this.fflLevel = fflLevel;
	}

	public String getFflTable() {
		return this.fflTable;
	}

	public void setFflTable(String fflTable) {
		this.fflTable = fflTable;
	}

	public String getFflField1() {
		return this.fflField1;
	}

	public void setFflField1(String fflField1) {
		this.fflField1 = fflField1;
	}

	public String getFflField2() {
		return this.fflField2;
	}

	public void setFflField2(String fflField2) {
		this.fflField2 = fflField2;
	}

	public String getFflField3() {
		return this.fflField3;
	}

	public void setFflField3(String fflField3) {
		this.fflField3 = fflField3;
	}

	public String getFflType() {
		return this.fflType;
	}

	public void setFflType(String fflType) {
		this.fflType = fflType;
	}

	public String getFflWhere() {
		return this.fflWhere;
	}

	public void setFflWhere(String fflWhere) {
		this.fflWhere = fflWhere;
	}

	public String getFflCompare() {
		return this.fflCompare;
	}

	public void setFflCompare(String fflCompare) {
		this.fflCompare = fflCompare;
	}

	public Boolean getFflOrderby() {
		return this.fflOrderby;
	}

	public void setFflOrderby(Boolean fflOrderby) {
		this.fflOrderby = fflOrderby;
	}

	public boolean isAnzeigen() {
		return this.anzeigen;
	}

	public void setAnzeigen(boolean anzeigen) {
		this.anzeigen = anzeigen;
	}

	public Set getFilterRows() {
		return this.filterRows;
	}

	public void setFilterRows(Set filterRows) {
		this.filterRows = filterRows;
	}

	public Set getFilterBasises() {
		return this.filterBasises;
	}

	public void setFilterBasises(Set filterBasises) {
		this.filterBasises = filterBasises;
	}

	public Set getFilterSuchenFelderTxts() {
		return this.filterSuchenFelderTxts;
	}

	public void setFilterSuchenFelderTxts(Set filterSuchenFelderTxts) {
		this.filterSuchenFelderTxts = filterSuchenFelderTxts;
	}

	public Set getFilterSuchenSeite1s() {
		return this.filterSuchenSeite1s;
	}

	public void setFilterSuchenSeite1s(Set filterSuchenSeite1s) {
		this.filterSuchenSeite1s = filterSuchenSeite1s;
	}

}
