package sernet.gs.reveng;

// Generated Jun 5, 2015 1:28:30 PM by Hibernate Tools 3.4.0.CR1

/**
 * FilterResZgm generated by hbm2java
 */
public class FilterResZgm implements java.io.Serializable {

	private FilterResZgmId id;
	private byte spid;

	public FilterResZgm() {
	}

	public FilterResZgm(FilterResZgmId id, byte spid) {
		this.id = id;
		this.spid = spid;
	}

	public FilterResZgmId getId() {
		return this.id;
	}

	public void setId(FilterResZgmId id) {
		this.id = id;
	}

	public byte getSpid() {
		return this.spid;
	}

	public void setSpid(byte spid) {
		this.spid = spid;
	}

}
