package sernet.gs.reveng;

// Generated Jun 5, 2015 1:28:30 PM by Hibernate Tools 3.4.0.CR1

/**
 * FilterResZotId generated by hbm2java
 */
public class FilterResZotId implements java.io.Serializable {

	private int searchId;
	private int zotImpId;
	private int zotId;
	private int col;

	public FilterResZotId() {
	}

	public FilterResZotId(int searchId, int zotImpId, int zotId, int col) {
		this.searchId = searchId;
		this.zotImpId = zotImpId;
		this.zotId = zotId;
		this.col = col;
	}

	public int getSearchId() {
		return this.searchId;
	}

	public void setSearchId(int searchId) {
		this.searchId = searchId;
	}

	public int getZotImpId() {
		return this.zotImpId;
	}

	public void setZotImpId(int zotImpId) {
		this.zotImpId = zotImpId;
	}

	public int getZotId() {
		return this.zotId;
	}

	public void setZotId(int zotId) {
		this.zotId = zotId;
	}

	public int getCol() {
		return this.col;
	}

	public void setCol(int col) {
		this.col = col;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FilterResZotId))
			return false;
		FilterResZotId castOther = (FilterResZotId) other;

		return (this.getSearchId() == castOther.getSearchId())
				&& (this.getZotImpId() == castOther.getZotImpId())
				&& (this.getZotId() == castOther.getZotId())
				&& (this.getCol() == castOther.getCol());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getSearchId();
		result = 37 * result + this.getZotImpId();
		result = 37 * result + this.getZotId();
		result = 37 * result + this.getCol();
		return result;
	}

}
