package sernet.gs.reveng;

// Generated Jun 5, 2015 1:28:30 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * MbBaustZielobjTyp generated by hbm2java
 */
public class MbBaustZielobjTyp implements java.io.Serializable {

	private MbBaustZielobjTypId id;
	private Date timestamp;
	private MbZielobjTyp mbZielobjTyp;
	private MbBaust mbBaust;
	private MMetastatus MMetastatus;
	private int metaVers;
	private Integer obsoletVers;
	private String link;
	private String guid;
	private Date loeschDatum;
	private Byte impNeu;
	private String erfasstDurch;
	private String geloeschtDurch;
	private String guidOrg;
	private int usn;

	public MbBaustZielobjTyp() {
	}

	public MbBaustZielobjTyp(MbBaustZielobjTypId id, MbZielobjTyp mbZielobjTyp,
			MbBaust mbBaust, MMetastatus MMetastatus, int metaVers, int usn) {
		this.id = id;
		this.mbZielobjTyp = mbZielobjTyp;
		this.mbBaust = mbBaust;
		this.MMetastatus = MMetastatus;
		this.metaVers = metaVers;
		this.usn = usn;
	}

	public MbBaustZielobjTyp(MbBaustZielobjTypId id, MbZielobjTyp mbZielobjTyp,
			MbBaust mbBaust, MMetastatus MMetastatus, int metaVers,
			Integer obsoletVers, String link, String guid, Date loeschDatum,
			Byte impNeu, String erfasstDurch, String geloeschtDurch,
			String guidOrg, int usn) {
		this.id = id;
		this.mbZielobjTyp = mbZielobjTyp;
		this.mbBaust = mbBaust;
		this.MMetastatus = MMetastatus;
		this.metaVers = metaVers;
		this.obsoletVers = obsoletVers;
		this.link = link;
		this.guid = guid;
		this.loeschDatum = loeschDatum;
		this.impNeu = impNeu;
		this.erfasstDurch = erfasstDurch;
		this.geloeschtDurch = geloeschtDurch;
		this.guidOrg = guidOrg;
		this.usn = usn;
	}

	public MbBaustZielobjTypId getId() {
		return this.id;
	}

	public void setId(MbBaustZielobjTypId id) {
		this.id = id;
	}

	public Date getTimestamp() {
		return this.timestamp;
	}

	public void setTimestamp(Date timestamp) {
		this.timestamp = timestamp;
	}

	public MbZielobjTyp getMbZielobjTyp() {
		return this.mbZielobjTyp;
	}

	public void setMbZielobjTyp(MbZielobjTyp mbZielobjTyp) {
		this.mbZielobjTyp = mbZielobjTyp;
	}

	public MbBaust getMbBaust() {
		return this.mbBaust;
	}

	public void setMbBaust(MbBaust mbBaust) {
		this.mbBaust = mbBaust;
	}

	public MMetastatus getMMetastatus() {
		return this.MMetastatus;
	}

	public void setMMetastatus(MMetastatus MMetastatus) {
		this.MMetastatus = MMetastatus;
	}

	public int getMetaVers() {
		return this.metaVers;
	}

	public void setMetaVers(int metaVers) {
		this.metaVers = metaVers;
	}

	public Integer getObsoletVers() {
		return this.obsoletVers;
	}

	public void setObsoletVers(Integer obsoletVers) {
		this.obsoletVers = obsoletVers;
	}

	public String getLink() {
		return this.link;
	}

	public void setLink(String link) {
		this.link = link;
	}

	public String getGuid() {
		return this.guid;
	}

	public void setGuid(String guid) {
		this.guid = guid;
	}

	public Date getLoeschDatum() {
		return this.loeschDatum;
	}

	public void setLoeschDatum(Date loeschDatum) {
		this.loeschDatum = loeschDatum;
	}

	public Byte getImpNeu() {
		return this.impNeu;
	}

	public void setImpNeu(Byte impNeu) {
		this.impNeu = impNeu;
	}

	public String getErfasstDurch() {
		return this.erfasstDurch;
	}

	public void setErfasstDurch(String erfasstDurch) {
		this.erfasstDurch = erfasstDurch;
	}

	public String getGeloeschtDurch() {
		return this.geloeschtDurch;
	}

	public void setGeloeschtDurch(String geloeschtDurch) {
		this.geloeschtDurch = geloeschtDurch;
	}

	public String getGuidOrg() {
		return this.guidOrg;
	}

	public void setGuidOrg(String guidOrg) {
		this.guidOrg = guidOrg;
	}

	public int getUsn() {
		return this.usn;
	}

	public void setUsn(int usn) {
		this.usn = usn;
	}

}
