package sernet.gs.reveng;

// Generated Jun 5, 2015 1:28:30 PM by Hibernate Tools 3.4.0.CR1

/**
 * MbBaustGefaehrId generated by hbm2java
 */
public class MbBaustGefaehrId implements java.io.Serializable {

	private int bauImpId;
	private int bauId;
	private int gefImpId;
	private int gefId;

	public MbBaustGefaehrId() {
	}

	public MbBaustGefaehrId(int bauImpId, int bauId, int gefImpId, int gefId) {
		this.bauImpId = bauImpId;
		this.bauId = bauId;
		this.gefImpId = gefImpId;
		this.gefId = gefId;
	}

	public int getBauImpId() {
		return this.bauImpId;
	}

	public void setBauImpId(int bauImpId) {
		this.bauImpId = bauImpId;
	}

	public int getBauId() {
		return this.bauId;
	}

	public void setBauId(int bauId) {
		this.bauId = bauId;
	}

	public int getGefImpId() {
		return this.gefImpId;
	}

	public void setGefImpId(int gefImpId) {
		this.gefImpId = gefImpId;
	}

	public int getGefId() {
		return this.gefId;
	}

	public void setGefId(int gefId) {
		this.gefId = gefId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MbBaustGefaehrId))
			return false;
		MbBaustGefaehrId castOther = (MbBaustGefaehrId) other;

		return (this.getBauImpId() == castOther.getBauImpId())
				&& (this.getBauId() == castOther.getBauId())
				&& (this.getGefImpId() == castOther.getGefImpId())
				&& (this.getGefId() == castOther.getGefId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getBauImpId();
		result = 37 * result + this.getBauId();
		result = 37 * result + this.getGefImpId();
		result = 37 * result + this.getGefId();
		return result;
	}

}
