package sernet.gs.reveng;

// Generated Jun 5, 2015 1:28:30 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * MbBauMasGef generated by hbm2java
 */
public class MbBauMasGef implements java.io.Serializable {

	private MbBauMasGefId id;
	private MbMassn mbMassn;
	private MSchutzbedarfkateg MSchutzbedarfkategBySbkIdVert;
	private MSchutzbedarfkateg MSchutzbedarfkategByBgmTransSbkId;
	private MSchutzbedarfkateg MSchutzbedarfkategByBgmRevisSbkId;
	private MbBaust mbBaust;
	private MSchutzbedarfkateg MSchutzbedarfkategByBgmAutenSbkId;
	private SysImport sysImport;
	private MSchutzbedarfkateg MSchutzbedarfkategBySbkIdInteg;
	private MbGefaehr mbGefaehr;
	private MSchutzbedarfkateg MSchutzbedarfkategBySbkIdVerf;
	private Integer metaVers;
	private byte metaNeu;
	private Integer obsoletVers;
	private Date erfasstAm;
	private String erfasstDurch;
	private Date geloeschtAm;
	private String geloeschtDurch;
	private String guid;
	private String guidOrg;
	private Byte impNeu;

	public MbBauMasGef() {
	}

	public MbBauMasGef(MbBauMasGefId id, MbMassn mbMassn, MbBaust mbBaust,
			SysImport sysImport, MbGefaehr mbGefaehr, byte metaNeu,
			Date erfasstAm, String erfasstDurch, String guid) {
		this.id = id;
		this.mbMassn = mbMassn;
		this.mbBaust = mbBaust;
		this.sysImport = sysImport;
		this.mbGefaehr = mbGefaehr;
		this.metaNeu = metaNeu;
		this.erfasstAm = erfasstAm;
		this.erfasstDurch = erfasstDurch;
		this.guid = guid;
	}

	public MbBauMasGef(MbBauMasGefId id, MbMassn mbMassn,
			MSchutzbedarfkateg MSchutzbedarfkategBySbkIdVert,
			MSchutzbedarfkateg MSchutzbedarfkategByBgmTransSbkId,
			MSchutzbedarfkateg MSchutzbedarfkategByBgmRevisSbkId,
			MbBaust mbBaust,
			MSchutzbedarfkateg MSchutzbedarfkategByBgmAutenSbkId,
			SysImport sysImport,
			MSchutzbedarfkateg MSchutzbedarfkategBySbkIdInteg,
			MbGefaehr mbGefaehr,
			MSchutzbedarfkateg MSchutzbedarfkategBySbkIdVerf, Integer metaVers,
			byte metaNeu, Integer obsoletVers, Date erfasstAm,
			String erfasstDurch, Date geloeschtAm, String geloeschtDurch,
			String guid, String guidOrg, Byte impNeu) {
		this.id = id;
		this.mbMassn = mbMassn;
		this.MSchutzbedarfkategBySbkIdVert = MSchutzbedarfkategBySbkIdVert;
		this.MSchutzbedarfkategByBgmTransSbkId = MSchutzbedarfkategByBgmTransSbkId;
		this.MSchutzbedarfkategByBgmRevisSbkId = MSchutzbedarfkategByBgmRevisSbkId;
		this.mbBaust = mbBaust;
		this.MSchutzbedarfkategByBgmAutenSbkId = MSchutzbedarfkategByBgmAutenSbkId;
		this.sysImport = sysImport;
		this.MSchutzbedarfkategBySbkIdInteg = MSchutzbedarfkategBySbkIdInteg;
		this.mbGefaehr = mbGefaehr;
		this.MSchutzbedarfkategBySbkIdVerf = MSchutzbedarfkategBySbkIdVerf;
		this.metaVers = metaVers;
		this.metaNeu = metaNeu;
		this.obsoletVers = obsoletVers;
		this.erfasstAm = erfasstAm;
		this.erfasstDurch = erfasstDurch;
		this.geloeschtAm = geloeschtAm;
		this.geloeschtDurch = geloeschtDurch;
		this.guid = guid;
		this.guidOrg = guidOrg;
		this.impNeu = impNeu;
	}

	public MbBauMasGefId getId() {
		return this.id;
	}

	public void setId(MbBauMasGefId id) {
		this.id = id;
	}

	public MbMassn getMbMassn() {
		return this.mbMassn;
	}

	public void setMbMassn(MbMassn mbMassn) {
		this.mbMassn = mbMassn;
	}

	public MSchutzbedarfkateg getMSchutzbedarfkategBySbkIdVert() {
		return this.MSchutzbedarfkategBySbkIdVert;
	}

	public void setMSchutzbedarfkategBySbkIdVert(
			MSchutzbedarfkateg MSchutzbedarfkategBySbkIdVert) {
		this.MSchutzbedarfkategBySbkIdVert = MSchutzbedarfkategBySbkIdVert;
	}

	public MSchutzbedarfkateg getMSchutzbedarfkategByBgmTransSbkId() {
		return this.MSchutzbedarfkategByBgmTransSbkId;
	}

	public void setMSchutzbedarfkategByBgmTransSbkId(
			MSchutzbedarfkateg MSchutzbedarfkategByBgmTransSbkId) {
		this.MSchutzbedarfkategByBgmTransSbkId = MSchutzbedarfkategByBgmTransSbkId;
	}

	public MSchutzbedarfkateg getMSchutzbedarfkategByBgmRevisSbkId() {
		return this.MSchutzbedarfkategByBgmRevisSbkId;
	}

	public void setMSchutzbedarfkategByBgmRevisSbkId(
			MSchutzbedarfkateg MSchutzbedarfkategByBgmRevisSbkId) {
		this.MSchutzbedarfkategByBgmRevisSbkId = MSchutzbedarfkategByBgmRevisSbkId;
	}

	public MbBaust getMbBaust() {
		return this.mbBaust;
	}

	public void setMbBaust(MbBaust mbBaust) {
		this.mbBaust = mbBaust;
	}

	public MSchutzbedarfkateg getMSchutzbedarfkategByBgmAutenSbkId() {
		return this.MSchutzbedarfkategByBgmAutenSbkId;
	}

	public void setMSchutzbedarfkategByBgmAutenSbkId(
			MSchutzbedarfkateg MSchutzbedarfkategByBgmAutenSbkId) {
		this.MSchutzbedarfkategByBgmAutenSbkId = MSchutzbedarfkategByBgmAutenSbkId;
	}

	public SysImport getSysImport() {
		return this.sysImport;
	}

	public void setSysImport(SysImport sysImport) {
		this.sysImport = sysImport;
	}

	public MSchutzbedarfkateg getMSchutzbedarfkategBySbkIdInteg() {
		return this.MSchutzbedarfkategBySbkIdInteg;
	}

	public void setMSchutzbedarfkategBySbkIdInteg(
			MSchutzbedarfkateg MSchutzbedarfkategBySbkIdInteg) {
		this.MSchutzbedarfkategBySbkIdInteg = MSchutzbedarfkategBySbkIdInteg;
	}

	public MbGefaehr getMbGefaehr() {
		return this.mbGefaehr;
	}

	public void setMbGefaehr(MbGefaehr mbGefaehr) {
		this.mbGefaehr = mbGefaehr;
	}

	public MSchutzbedarfkateg getMSchutzbedarfkategBySbkIdVerf() {
		return this.MSchutzbedarfkategBySbkIdVerf;
	}

	public void setMSchutzbedarfkategBySbkIdVerf(
			MSchutzbedarfkateg MSchutzbedarfkategBySbkIdVerf) {
		this.MSchutzbedarfkategBySbkIdVerf = MSchutzbedarfkategBySbkIdVerf;
	}

	public Integer getMetaVers() {
		return this.metaVers;
	}

	public void setMetaVers(Integer metaVers) {
		this.metaVers = metaVers;
	}

	public byte getMetaNeu() {
		return this.metaNeu;
	}

	public void setMetaNeu(byte metaNeu) {
		this.metaNeu = metaNeu;
	}

	public Integer getObsoletVers() {
		return this.obsoletVers;
	}

	public void setObsoletVers(Integer obsoletVers) {
		this.obsoletVers = obsoletVers;
	}

	public Date getErfasstAm() {
		return this.erfasstAm;
	}

	public void setErfasstAm(Date erfasstAm) {
		this.erfasstAm = erfasstAm;
	}

	public String getErfasstDurch() {
		return this.erfasstDurch;
	}

	public void setErfasstDurch(String erfasstDurch) {
		this.erfasstDurch = erfasstDurch;
	}

	public Date getGeloeschtAm() {
		return this.geloeschtAm;
	}

	public void setGeloeschtAm(Date geloeschtAm) {
		this.geloeschtAm = geloeschtAm;
	}

	public String getGeloeschtDurch() {
		return this.geloeschtDurch;
	}

	public void setGeloeschtDurch(String geloeschtDurch) {
		this.geloeschtDurch = geloeschtDurch;
	}

	public String getGuid() {
		return this.guid;
	}

	public void setGuid(String guid) {
		this.guid = guid;
	}

	public String getGuidOrg() {
		return this.guidOrg;
	}

	public void setGuidOrg(String guidOrg) {
		this.guidOrg = guidOrg;
	}

	public Byte getImpNeu() {
		return this.impNeu;
	}

	public void setImpNeu(Byte impNeu) {
		this.impNeu = impNeu;
	}

}
