package sernet.gs.reveng;

// Generated Jun 5, 2015 1:28:30 PM by Hibernate Tools 3.4.0.CR1

/**
 * MbDelGefahrId generated by hbm2java
 */
public class MbDelGefahrId implements java.io.Serializable {

	private int impId;
	private int gefImpId;
	private int gefId;

	public MbDelGefahrId() {
	}

	public MbDelGefahrId(int impId, int gefImpId, int gefId) {
		this.impId = impId;
		this.gefImpId = gefImpId;
		this.gefId = gefId;
	}

	public int getImpId() {
		return this.impId;
	}

	public void setImpId(int impId) {
		this.impId = impId;
	}

	public int getGefImpId() {
		return this.gefImpId;
	}

	public void setGefImpId(int gefImpId) {
		this.gefImpId = gefImpId;
	}

	public int getGefId() {
		return this.gefId;
	}

	public void setGefId(int gefId) {
		this.gefId = gefId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MbDelGefahrId))
			return false;
		MbDelGefahrId castOther = (MbDelGefahrId) other;

		return (this.getImpId() == castOther.getImpId())
				&& (this.getGefImpId() == castOther.getGefImpId())
				&& (this.getGefId() == castOther.getGefId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getImpId();
		result = 37 * result + this.getGefImpId();
		result = 37 * result + this.getGefId();
		return result;
	}

}
