package sernet.gs.reveng;

// Generated Jun 5, 2015 1:28:30 PM by Hibernate Tools 3.4.0.CR1

/**
 * MbDelWaehrungenId generated by hbm2java
 */
public class MbDelWaehrungenId implements java.io.Serializable {

	private int impId;
	private int waeImpId;
	private int waeId;

	public MbDelWaehrungenId() {
	}

	public MbDelWaehrungenId(int impId, int waeImpId, int waeId) {
		this.impId = impId;
		this.waeImpId = waeImpId;
		this.waeId = waeId;
	}

	public int getImpId() {
		return this.impId;
	}

	public void setImpId(int impId) {
		this.impId = impId;
	}

	public int getWaeImpId() {
		return this.waeImpId;
	}

	public void setWaeImpId(int waeImpId) {
		this.waeImpId = waeImpId;
	}

	public int getWaeId() {
		return this.waeId;
	}

	public void setWaeId(int waeId) {
		this.waeId = waeId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MbDelWaehrungenId))
			return false;
		MbDelWaehrungenId castOther = (MbDelWaehrungenId) other;

		return (this.getImpId() == castOther.getImpId())
				&& (this.getWaeImpId() == castOther.getWaeImpId())
				&& (this.getWaeId() == castOther.getWaeId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getImpId();
		result = 37 * result + this.getWaeImpId();
		result = 37 * result + this.getWaeId();
		return result;
	}

}
