package sernet.gs.reveng;

// Generated Jun 5, 2015 1:28:30 PM by Hibernate Tools 3.4.0.CR1

/**
 * MbGefaehrTxtId generated by hbm2java
 */
public class MbGefaehrTxtId implements java.io.Serializable {

	private int gefImpId;
	private int gefId;
	private short sprId;

	public MbGefaehrTxtId() {
	}

	public MbGefaehrTxtId(int gefImpId, int gefId, short sprId) {
		this.gefImpId = gefImpId;
		this.gefId = gefId;
		this.sprId = sprId;
	}

	public int getGefImpId() {
		return this.gefImpId;
	}

	public void setGefImpId(int gefImpId) {
		this.gefImpId = gefImpId;
	}

	public int getGefId() {
		return this.gefId;
	}

	public void setGefId(int gefId) {
		this.gefId = gefId;
	}

	public short getSprId() {
		return this.sprId;
	}

	public void setSprId(short sprId) {
		this.sprId = sprId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MbGefaehrTxtId))
			return false;
		MbGefaehrTxtId castOther = (MbGefaehrTxtId) other;

		return (this.getGefImpId() == castOther.getGefImpId())
				&& (this.getGefId() == castOther.getGefId())
				&& (this.getSprId() == castOther.getSprId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getGefImpId();
		result = 37 * result + this.getGefId();
		result = 37 * result + this.getSprId();
		return result;
	}

}
