package sernet.gs.reveng;

// Generated Jun 5, 2015 1:28:30 PM by Hibernate Tools 3.4.0.CR1

/**
 * MbMasQryId generated by hbm2java
 */
public class MbMasQryId implements java.io.Serializable {

	private int masImpId;
	private int masId;
	private int qryId;

	public MbMasQryId() {
	}

	public MbMasQryId(int masImpId, int masId, int qryId) {
		this.masImpId = masImpId;
		this.masId = masId;
		this.qryId = qryId;
	}

	public int getMasImpId() {
		return this.masImpId;
	}

	public void setMasImpId(int masImpId) {
		this.masImpId = masImpId;
	}

	public int getMasId() {
		return this.masId;
	}

	public void setMasId(int masId) {
		this.masId = masId;
	}

	public int getQryId() {
		return this.qryId;
	}

	public void setQryId(int qryId) {
		this.qryId = qryId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MbMasQryId))
			return false;
		MbMasQryId castOther = (MbMasQryId) other;

		return (this.getMasImpId() == castOther.getMasImpId())
				&& (this.getMasId() == castOther.getMasId())
				&& (this.getQryId() == castOther.getQryId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getMasImpId();
		result = 37 * result + this.getMasId();
		result = 37 * result + this.getQryId();
		return result;
	}

}
