package sernet.gs.reveng;

// Generated Jun 5, 2015 1:28:30 PM by Hibernate Tools 3.4.0.CR1

/**
 * MbMassnnkatTxtId generated by hbm2java
 */
public class MbMassnnkatTxtId implements java.io.Serializable {

	private int mskImpId;
	private int mskId;
	private short sprId;

	public MbMassnnkatTxtId() {
	}

	public MbMassnnkatTxtId(int mskImpId, int mskId, short sprId) {
		this.mskImpId = mskImpId;
		this.mskId = mskId;
		this.sprId = sprId;
	}

	public int getMskImpId() {
		return this.mskImpId;
	}

	public void setMskImpId(int mskImpId) {
		this.mskImpId = mskImpId;
	}

	public int getMskId() {
		return this.mskId;
	}

	public void setMskId(int mskId) {
		this.mskId = mskId;
	}

	public short getSprId() {
		return this.sprId;
	}

	public void setSprId(short sprId) {
		this.sprId = sprId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MbMassnnkatTxtId))
			return false;
		MbMassnnkatTxtId castOther = (MbMassnnkatTxtId) other;

		return (this.getMskImpId() == castOther.getMskImpId())
				&& (this.getMskId() == castOther.getMskId())
				&& (this.getSprId() == castOther.getSprId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getMskImpId();
		result = 37 * result + this.getMskId();
		result = 37 * result + this.getSprId();
		return result;
	}

}
