package sernet.gs.reveng;

// Generated Jun 5, 2015 1:28:30 PM by Hibernate Tools 3.4.0.CR1

/**
 * MbMassPhaseId generated by hbm2java
 */
public class MbMassPhaseId implements java.io.Serializable {

	private int phaImpId;
	private int phaId;

	public MbMassPhaseId() {
	}

	public MbMassPhaseId(int phaImpId, int phaId) {
		this.phaImpId = phaImpId;
		this.phaId = phaId;
	}

	public int getPhaImpId() {
		return this.phaImpId;
	}

	public void setPhaImpId(int phaImpId) {
		this.phaImpId = phaImpId;
	}

	public int getPhaId() {
		return this.phaId;
	}

	public void setPhaId(int phaId) {
		this.phaId = phaId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MbMassPhaseId))
			return false;
		MbMassPhaseId castOther = (MbMassPhaseId) other;

		return (this.getPhaImpId() == castOther.getPhaImpId())
				&& (this.getPhaId() == castOther.getPhaId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getPhaImpId();
		result = 37 * result + this.getPhaId();
		return result;
	}

}
