package sernet.gs.reveng;

// Generated Jun 5, 2015 1:28:30 PM by Hibernate Tools 3.4.0.CR1

/**
 * MbMasUpdateId generated by hbm2java
 */
public class MbMasUpdateId implements java.io.Serializable {

	private int masImpId;
	private int masId;

	public MbMasUpdateId() {
	}

	public MbMasUpdateId(int masImpId, int masId) {
		this.masImpId = masImpId;
		this.masId = masId;
	}

	public int getMasImpId() {
		return this.masImpId;
	}

	public void setMasImpId(int masImpId) {
		this.masImpId = masImpId;
	}

	public int getMasId() {
		return this.masId;
	}

	public void setMasId(int masId) {
		this.masId = masId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MbMasUpdateId))
			return false;
		MbMasUpdateId castOther = (MbMasUpdateId) other;

		return (this.getMasImpId() == castOther.getMasImpId())
				&& (this.getMasId() == castOther.getMasId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getMasImpId();
		result = 37 * result + this.getMasId();
		return result;
	}

}
