package sernet.gs.reveng;

// Generated Jun 5, 2015 1:28:30 PM by Hibernate Tools 3.4.0.CR1

/**
 * MbPrioritaetId generated by hbm2java
 */
public class MbPrioritaetId implements java.io.Serializable {

	private int impId;
	private int bauImpId;
	private int bauId;
	private int masImpId;
	private int masId;

	public MbPrioritaetId() {
	}

	public MbPrioritaetId(int impId, int bauImpId, int bauId, int masImpId,
			int masId) {
		this.impId = impId;
		this.bauImpId = bauImpId;
		this.bauId = bauId;
		this.masImpId = masImpId;
		this.masId = masId;
	}

	public int getImpId() {
		return this.impId;
	}

	public void setImpId(int impId) {
		this.impId = impId;
	}

	public int getBauImpId() {
		return this.bauImpId;
	}

	public void setBauImpId(int bauImpId) {
		this.bauImpId = bauImpId;
	}

	public int getBauId() {
		return this.bauId;
	}

	public void setBauId(int bauId) {
		this.bauId = bauId;
	}

	public int getMasImpId() {
		return this.masImpId;
	}

	public void setMasImpId(int masImpId) {
		this.masImpId = masImpId;
	}

	public int getMasId() {
		return this.masId;
	}

	public void setMasId(int masId) {
		this.masId = masId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MbPrioritaetId))
			return false;
		MbPrioritaetId castOther = (MbPrioritaetId) other;

		return (this.getImpId() == castOther.getImpId())
				&& (this.getBauImpId() == castOther.getBauImpId())
				&& (this.getBauId() == castOther.getBauId())
				&& (this.getMasImpId() == castOther.getMasImpId())
				&& (this.getMasId() == castOther.getMasId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getImpId();
		result = 37 * result + this.getBauImpId();
		result = 37 * result + this.getBauId();
		result = 37 * result + this.getMasImpId();
		result = 37 * result + this.getMasId();
		return result;
	}

}
