package sernet.gs.reveng;

// Generated Jun 5, 2015 1:28:30 PM by Hibernate Tools 3.4.0.CR1

/**
 * MBstnStatusTxtId generated by hbm2java
 */
public class MBstnStatusTxtId implements java.io.Serializable {

	private byte bstId;
	private short sprId;

	public MBstnStatusTxtId() {
	}

	public MBstnStatusTxtId(byte bstId, short sprId) {
		this.bstId = bstId;
		this.sprId = sprId;
	}

	public byte getBstId() {
		return this.bstId;
	}

	public void setBstId(byte bstId) {
		this.bstId = bstId;
	}

	public short getSprId() {
		return this.sprId;
	}

	public void setSprId(short sprId) {
		this.sprId = sprId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MBstnStatusTxtId))
			return false;
		MBstnStatusTxtId castOther = (MBstnStatusTxtId) other;

		return (this.getBstId() == castOther.getBstId())
				&& (this.getSprId() == castOther.getSprId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getBstId();
		result = 37 * result + this.getSprId();
		return result;
	}

}
