package sernet.gs.reveng;

// Generated Jun 5, 2015 1:28:30 PM by Hibernate Tools 3.4.0.CR1

/**
 * MbZielobjRelationId generated by hbm2java
 */
public class MbZielobjRelationId implements java.io.Serializable {

	private int zotImpId;
	private int zotId1;
	private int zotId2;
	private char typ;

	public MbZielobjRelationId() {
	}

	public MbZielobjRelationId(int zotImpId, int zotId1, int zotId2, char typ) {
		this.zotImpId = zotImpId;
		this.zotId1 = zotId1;
		this.zotId2 = zotId2;
		this.typ = typ;
	}

	public int getZotImpId() {
		return this.zotImpId;
	}

	public void setZotImpId(int zotImpId) {
		this.zotImpId = zotImpId;
	}

	public int getZotId1() {
		return this.zotId1;
	}

	public void setZotId1(int zotId1) {
		this.zotId1 = zotId1;
	}

	public int getZotId2() {
		return this.zotId2;
	}

	public void setZotId2(int zotId2) {
		this.zotId2 = zotId2;
	}

	public char getTyp() {
		return this.typ;
	}

	public void setTyp(char typ) {
		this.typ = typ;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MbZielobjRelationId))
			return false;
		MbZielobjRelationId castOther = (MbZielobjRelationId) other;

		return (this.getZotImpId() == castOther.getZotImpId())
				&& (this.getZotId1() == castOther.getZotId1())
				&& (this.getZotId2() == castOther.getZotId2())
				&& (this.getTyp() == castOther.getTyp());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getZotImpId();
		result = 37 * result + this.getZotId1();
		result = 37 * result + this.getZotId2();
		result = 37 * result + this.getTyp();
		return result;
	}

}
