package sernet.gs.reveng;

// Generated Jun 5, 2015 1:28:30 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * MMetatypTxt generated by hbm2java
 */
public class MMetatypTxt implements java.io.Serializable {

	private MMetatypTxtId id;
	private Date timestamp;
	private MSprache MSprache;
	private MMetatyp MMetatyp;
	private String name;
	private String beschreibung;
	private String guid;
	private Byte impNeu;
	private String name2;

	public MMetatypTxt() {
	}

	public MMetatypTxt(MMetatypTxtId id, MSprache MSprache, MMetatyp MMetatyp,
			String name2) {
		this.id = id;
		this.MSprache = MSprache;
		this.MMetatyp = MMetatyp;
		this.name2 = name2;
	}

	public MMetatypTxt(MMetatypTxtId id, MSprache MSprache, MMetatyp MMetatyp,
			String name, String beschreibung, String guid, Byte impNeu,
			String name2) {
		this.id = id;
		this.MSprache = MSprache;
		this.MMetatyp = MMetatyp;
		this.name = name;
		this.beschreibung = beschreibung;
		this.guid = guid;
		this.impNeu = impNeu;
		this.name2 = name2;
	}

	public MMetatypTxtId getId() {
		return this.id;
	}

	public void setId(MMetatypTxtId id) {
		this.id = id;
	}

	public Date getTimestamp() {
		return this.timestamp;
	}

	public void setTimestamp(Date timestamp) {
		this.timestamp = timestamp;
	}

	public MSprache getMSprache() {
		return this.MSprache;
	}

	public void setMSprache(MSprache MSprache) {
		this.MSprache = MSprache;
	}

	public MMetatyp getMMetatyp() {
		return this.MMetatyp;
	}

	public void setMMetatyp(MMetatyp MMetatyp) {
		this.MMetatyp = MMetatyp;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getBeschreibung() {
		return this.beschreibung;
	}

	public void setBeschreibung(String beschreibung) {
		this.beschreibung = beschreibung;
	}

	public String getGuid() {
		return this.guid;
	}

	public void setGuid(String guid) {
		this.guid = guid;
	}

	public Byte getImpNeu() {
		return this.impNeu;
	}

	public void setImpNeu(Byte impNeu) {
		this.impNeu = impNeu;
	}

	public String getName2() {
		return this.name2;
	}

	public void setName2(String name2) {
		this.name2 = name2;
	}

}
