package sernet.gs.reveng;

// Generated Jun 5, 2015 1:28:30 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * MsRaBehandTxt generated by hbm2java
 */
public class MsRaBehandTxt implements java.io.Serializable {

	private MsRaBehandTxtId id;
	private String name;
	private char kurz;
	private String guid;
	private Date erstelltAm;
	private String erstelltDurch;

	public MsRaBehandTxt() {
	}

	public MsRaBehandTxt(MsRaBehandTxtId id, String name, char kurz,
			String guid, Date erstelltAm, String erstelltDurch) {
		this.id = id;
		this.name = name;
		this.kurz = kurz;
		this.guid = guid;
		this.erstelltAm = erstelltAm;
		this.erstelltDurch = erstelltDurch;
	}

	public MsRaBehandTxtId getId() {
		return this.id;
	}

	public void setId(MsRaBehandTxtId id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public char getKurz() {
		return this.kurz;
	}

	public void setKurz(char kurz) {
		this.kurz = kurz;
	}

	public String getGuid() {
		return this.guid;
	}

	public void setGuid(String guid) {
		this.guid = guid;
	}

	public Date getErstelltAm() {
		return this.erstelltAm;
	}

	public void setErstelltAm(Date erstelltAm) {
		this.erstelltAm = erstelltAm;
	}

	public String getErstelltDurch() {
		return this.erstelltDurch;
	}

	public void setErstelltDurch(String erstelltDurch) {
		this.erstelltDurch = erstelltDurch;
	}

}
