package sernet.gs.reveng;

// Generated Jun 5, 2015 1:28:30 PM by Hibernate Tools 3.4.0.CR1

/**
 * MsRaBehandTxtId generated by hbm2java
 */
public class MsRaBehandTxtId implements java.io.Serializable {

	private byte rabId;
	private short sprId;

	public MsRaBehandTxtId() {
	}

	public MsRaBehandTxtId(byte rabId, short sprId) {
		this.rabId = rabId;
		this.sprId = sprId;
	}

	public byte getRabId() {
		return this.rabId;
	}

	public void setRabId(byte rabId) {
		this.rabId = rabId;
	}

	public short getSprId() {
		return this.sprId;
	}

	public void setSprId(short sprId) {
		this.sprId = sprId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MsRaBehandTxtId))
			return false;
		MsRaBehandTxtId castOther = (MsRaBehandTxtId) other;

		return (this.getRabId() == castOther.getRabId())
				&& (this.getSprId() == castOther.getSprId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getRabId();
		result = 37 * result + this.getSprId();
		return result;
	}

}
