package sernet.gs.reveng;

// Generated Jun 5, 2015 1:28:30 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * MsZyk generated by hbm2java
 */
public class MsZyk implements java.io.Serializable {

	private byte zykId;
	private String guid;
	private Date erstelltAm;
	private String erstelltDurch;
	private Set modZobjBstMasses = new HashSet(0);
	private Set msZykTxts = new HashSet(0);
	private Set mbBaustMassnGsiegels = new HashSet(0);

	public MsZyk() {
	}

	public MsZyk(byte zykId, String guid, Date erstelltAm) {
		this.zykId = zykId;
		this.guid = guid;
		this.erstelltAm = erstelltAm;
	}

	public MsZyk(byte zykId, String guid, Date erstelltAm,
			String erstelltDurch, Set modZobjBstMasses, Set msZykTxts,
			Set mbBaustMassnGsiegels) {
		this.zykId = zykId;
		this.guid = guid;
		this.erstelltAm = erstelltAm;
		this.erstelltDurch = erstelltDurch;
		this.modZobjBstMasses = modZobjBstMasses;
		this.msZykTxts = msZykTxts;
		this.mbBaustMassnGsiegels = mbBaustMassnGsiegels;
	}

	public byte getZykId() {
		return this.zykId;
	}

	public void setZykId(byte zykId) {
		this.zykId = zykId;
	}

	public String getGuid() {
		return this.guid;
	}

	public void setGuid(String guid) {
		this.guid = guid;
	}

	public Date getErstelltAm() {
		return this.erstelltAm;
	}

	public void setErstelltAm(Date erstelltAm) {
		this.erstelltAm = erstelltAm;
	}

	public String getErstelltDurch() {
		return this.erstelltDurch;
	}

	public void setErstelltDurch(String erstelltDurch) {
		this.erstelltDurch = erstelltDurch;
	}

	public Set getModZobjBstMasses() {
		return this.modZobjBstMasses;
	}

	public void setModZobjBstMasses(Set modZobjBstMasses) {
		this.modZobjBstMasses = modZobjBstMasses;
	}

	public Set getMsZykTxts() {
		return this.msZykTxts;
	}

	public void setMsZykTxts(Set msZykTxts) {
		this.msZykTxts = msZykTxts;
	}

	public Set getMbBaustMassnGsiegels() {
		return this.mbBaustMassnGsiegels;
	}

	public void setMbBaustMassnGsiegels(Set mbBaustMassnGsiegels) {
		this.mbBaustMassnGsiegels = mbBaustMassnGsiegels;
	}

}
