package sernet.gs.reveng;

// Generated Jun 5, 2015 1:28:30 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * MYesnoTxt generated by hbm2java
 */
public class MYesnoTxt implements java.io.Serializable {

	private MYesnoTxtId id;
	private Date timestamp;
	private MYesno MYesno;
	private MSprache MSprache;
	private String name;
	private String beschreibung;
	private String guid;
	private Byte impNeu;

	public MYesnoTxt() {
	}

	public MYesnoTxt(MYesnoTxtId id, MYesno MYesno, MSprache MSprache) {
		this.id = id;
		this.MYesno = MYesno;
		this.MSprache = MSprache;
	}

	public MYesnoTxt(MYesnoTxtId id, MYesno MYesno, MSprache MSprache,
			String name, String beschreibung, String guid, Byte impNeu) {
		this.id = id;
		this.MYesno = MYesno;
		this.MSprache = MSprache;
		this.name = name;
		this.beschreibung = beschreibung;
		this.guid = guid;
		this.impNeu = impNeu;
	}

	public MYesnoTxtId getId() {
		return this.id;
	}

	public void setId(MYesnoTxtId id) {
		this.id = id;
	}

	public Date getTimestamp() {
		return this.timestamp;
	}

	public void setTimestamp(Date timestamp) {
		this.timestamp = timestamp;
	}

	public MYesno getMYesno() {
		return this.MYesno;
	}

	public void setMYesno(MYesno MYesno) {
		this.MYesno = MYesno;
	}

	public MSprache getMSprache() {
		return this.MSprache;
	}

	public void setMSprache(MSprache MSprache) {
		this.MSprache = MSprache;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getBeschreibung() {
		return this.beschreibung;
	}

	public void setBeschreibung(String beschreibung) {
		this.beschreibung = beschreibung;
	}

	public String getGuid() {
		return this.guid;
	}

	public void setGuid(String guid) {
		this.guid = guid;
	}

	public Byte getImpNeu() {
		return this.impNeu;
	}

	public void setImpNeu(Byte impNeu) {
		this.impNeu = impNeu;
	}

}
