package sernet.gs.reveng;

// Generated Jun 5, 2015 1:28:30 PM by Hibernate Tools 3.4.0.CR1

/**
 * NZielobjektZusatzId generated by hbm2java
 */
public class NZielobjektZusatzId implements java.io.Serializable {

	private int zobImpId;
	private int zobId;
	private int attId;
	private int zusId;
	private int zosZusId;

	public NZielobjektZusatzId() {
	}

	public NZielobjektZusatzId(int zobImpId, int zobId, int attId, int zusId,
			int zosZusId) {
		this.zobImpId = zobImpId;
		this.zobId = zobId;
		this.attId = attId;
		this.zusId = zusId;
		this.zosZusId = zosZusId;
	}

	public int getZobImpId() {
		return this.zobImpId;
	}

	public void setZobImpId(int zobImpId) {
		this.zobImpId = zobImpId;
	}

	public int getZobId() {
		return this.zobId;
	}

	public void setZobId(int zobId) {
		this.zobId = zobId;
	}

	public int getAttId() {
		return this.attId;
	}

	public void setAttId(int attId) {
		this.attId = attId;
	}

	public int getZusId() {
		return this.zusId;
	}

	public void setZusId(int zusId) {
		this.zusId = zusId;
	}

	public int getZosZusId() {
		return this.zosZusId;
	}

	public void setZosZusId(int zosZusId) {
		this.zosZusId = zosZusId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NZielobjektZusatzId))
			return false;
		NZielobjektZusatzId castOther = (NZielobjektZusatzId) other;

		return (this.getZobImpId() == castOther.getZobImpId())
				&& (this.getZobId() == castOther.getZobId())
				&& (this.getAttId() == castOther.getAttId())
				&& (this.getZusId() == castOther.getZusId())
				&& (this.getZosZusId() == castOther.getZosZusId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getZobImpId();
		result = 37 * result + this.getZobId();
		result = 37 * result + this.getAttId();
		result = 37 * result + this.getZusId();
		result = 37 * result + this.getZosZusId();
		return result;
	}

}
