package sernet.gs.reveng;

// Generated Jun 5, 2015 1:28:30 PM by Hibernate Tools 3.4.0.CR1

/**
 * NZobEsaId generated by hbm2java
 */
public class NZobEsaId implements java.io.Serializable {

	private int zobImpId;
	private int zobId;

	public NZobEsaId() {
	}

	public NZobEsaId(int zobImpId, int zobId) {
		this.zobImpId = zobImpId;
		this.zobId = zobId;
	}

	public int getZobImpId() {
		return this.zobImpId;
	}

	public void setZobImpId(int zobImpId) {
		this.zobImpId = zobImpId;
	}

	public int getZobId() {
		return this.zobId;
	}

	public void setZobId(int zobId) {
		this.zobId = zobId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NZobEsaId))
			return false;
		NZobEsaId castOther = (NZobEsaId) other;

		return (this.getZobImpId() == castOther.getZobImpId())
				&& (this.getZobId() == castOther.getZobId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getZobImpId();
		result = 37 * result + this.getZobId();
		return result;
	}

}
