package sernet.gs.reveng;

// Generated Jun 5, 2015 1:28:30 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * RaZobGefMit generated by hbm2java
 */
public class RaZobGefMit implements java.io.Serializable {

	private RaZobGefMitId id;
	private MsUnj msUnj;
	private NZielobjekt NZielobjekt;
	private RaZobGef raZobGef;
	private Date zgmaDatum;
	private String guid;
	private String guidOrg;
	private Byte impNeu;
	private int usn;
	private Date erstelltAm;
	private String erstelltDurch;
	private Date geaendertAm;
	private String geaendertDurch;
	private Date geloeschtAm;
	private String geloeschtDurch;

	public RaZobGefMit() {
	}

	public RaZobGefMit(RaZobGefMitId id, MsUnj msUnj, NZielobjekt NZielobjekt,
			RaZobGef raZobGef, String guid, int usn) {
		this.id = id;
		this.msUnj = msUnj;
		this.NZielobjekt = NZielobjekt;
		this.raZobGef = raZobGef;
		this.guid = guid;
		this.usn = usn;
	}

	public RaZobGefMit(RaZobGefMitId id, MsUnj msUnj, NZielobjekt NZielobjekt,
			RaZobGef raZobGef, Date zgmaDatum, String guid, String guidOrg,
			Byte impNeu, int usn, Date erstelltAm, String erstelltDurch,
			Date geaendertAm, String geaendertDurch, Date geloeschtAm,
			String geloeschtDurch) {
		this.id = id;
		this.msUnj = msUnj;
		this.NZielobjekt = NZielobjekt;
		this.raZobGef = raZobGef;
		this.zgmaDatum = zgmaDatum;
		this.guid = guid;
		this.guidOrg = guidOrg;
		this.impNeu = impNeu;
		this.usn = usn;
		this.erstelltAm = erstelltAm;
		this.erstelltDurch = erstelltDurch;
		this.geaendertAm = geaendertAm;
		this.geaendertDurch = geaendertDurch;
		this.geloeschtAm = geloeschtAm;
		this.geloeschtDurch = geloeschtDurch;
	}

	public RaZobGefMitId getId() {
		return this.id;
	}

	public void setId(RaZobGefMitId id) {
		this.id = id;
	}

	public MsUnj getMsUnj() {
		return this.msUnj;
	}

	public void setMsUnj(MsUnj msUnj) {
		this.msUnj = msUnj;
	}

	public NZielobjekt getNZielobjekt() {
		return this.NZielobjekt;
	}

	public void setNZielobjekt(NZielobjekt NZielobjekt) {
		this.NZielobjekt = NZielobjekt;
	}

	public RaZobGef getRaZobGef() {
		return this.raZobGef;
	}

	public void setRaZobGef(RaZobGef raZobGef) {
		this.raZobGef = raZobGef;
	}

	public Date getZgmaDatum() {
		return this.zgmaDatum;
	}

	public void setZgmaDatum(Date zgmaDatum) {
		this.zgmaDatum = zgmaDatum;
	}

	public String getGuid() {
		return this.guid;
	}

	public void setGuid(String guid) {
		this.guid = guid;
	}

	public String getGuidOrg() {
		return this.guidOrg;
	}

	public void setGuidOrg(String guidOrg) {
		this.guidOrg = guidOrg;
	}

	public Byte getImpNeu() {
		return this.impNeu;
	}

	public void setImpNeu(Byte impNeu) {
		this.impNeu = impNeu;
	}

	public int getUsn() {
		return this.usn;
	}

	public void setUsn(int usn) {
		this.usn = usn;
	}

	public Date getErstelltAm() {
		return this.erstelltAm;
	}

	public void setErstelltAm(Date erstelltAm) {
		this.erstelltAm = erstelltAm;
	}

	public String getErstelltDurch() {
		return this.erstelltDurch;
	}

	public void setErstelltDurch(String erstelltDurch) {
		this.erstelltDurch = erstelltDurch;
	}

	public Date getGeaendertAm() {
		return this.geaendertAm;
	}

	public void setGeaendertAm(Date geaendertAm) {
		this.geaendertAm = geaendertAm;
	}

	public String getGeaendertDurch() {
		return this.geaendertDurch;
	}

	public void setGeaendertDurch(String geaendertDurch) {
		this.geaendertDurch = geaendertDurch;
	}

	public Date getGeloeschtAm() {
		return this.geloeschtAm;
	}

	public void setGeloeschtAm(Date geloeschtAm) {
		this.geloeschtAm = geloeschtAm;
	}

	public String getGeloeschtDurch() {
		return this.geloeschtDurch;
	}

	public void setGeloeschtDurch(String geloeschtDurch) {
		this.geloeschtDurch = geloeschtDurch;
	}

}
