package sernet.gs.reveng;

// Generated Jun 5, 2015 1:28:30 PM by Hibernate Tools 3.4.0.CR1

/**
 * RaZobGefMasId generated by hbm2java
 */
public class RaZobGefMasId implements java.io.Serializable {

	private int zobImpId;
	private int zobId;
	private int gefImpId;
	private int gefId;
	private int masImpId;
	private int masId;

	public RaZobGefMasId() {
	}

	public RaZobGefMasId(int zobImpId, int zobId, int gefImpId, int gefId,
			int masImpId, int masId) {
		this.zobImpId = zobImpId;
		this.zobId = zobId;
		this.gefImpId = gefImpId;
		this.gefId = gefId;
		this.masImpId = masImpId;
		this.masId = masId;
	}

	public int getZobImpId() {
		return this.zobImpId;
	}

	public void setZobImpId(int zobImpId) {
		this.zobImpId = zobImpId;
	}

	public int getZobId() {
		return this.zobId;
	}

	public void setZobId(int zobId) {
		this.zobId = zobId;
	}

	public int getGefImpId() {
		return this.gefImpId;
	}

	public void setGefImpId(int gefImpId) {
		this.gefImpId = gefImpId;
	}

	public int getGefId() {
		return this.gefId;
	}

	public void setGefId(int gefId) {
		this.gefId = gefId;
	}

	public int getMasImpId() {
		return this.masImpId;
	}

	public void setMasImpId(int masImpId) {
		this.masImpId = masImpId;
	}

	public int getMasId() {
		return this.masId;
	}

	public void setMasId(int masId) {
		this.masId = masId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RaZobGefMasId))
			return false;
		RaZobGefMasId castOther = (RaZobGefMasId) other;

		return (this.getZobImpId() == castOther.getZobImpId())
				&& (this.getZobId() == castOther.getZobId())
				&& (this.getGefImpId() == castOther.getGefImpId())
				&& (this.getGefId() == castOther.getGefId())
				&& (this.getMasImpId() == castOther.getMasImpId())
				&& (this.getMasId() == castOther.getMasId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getZobImpId();
		result = 37 * result + this.getZobId();
		result = 37 * result + this.getGefImpId();
		result = 37 * result + this.getGefId();
		result = 37 * result + this.getMasImpId();
		result = 37 * result + this.getMasId();
		return result;
	}

}
