package sernet.gs.reveng;

// Generated Jun 5, 2015 1:28:30 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * RechteRolleBericht generated by hbm2java
 */
public class RechteRolleBericht implements java.io.Serializable {

	private RechteRolleBerichtId id;
	private BrBericht brBericht;
	private RechteRolle rechteRolle;
	private String guid;
	private Date erstelltAm;
	private String erstelltDurch;

	public RechteRolleBericht() {
	}

	public RechteRolleBericht(RechteRolleBerichtId id, BrBericht brBericht,
			RechteRolle rechteRolle, String guid) {
		this.id = id;
		this.brBericht = brBericht;
		this.rechteRolle = rechteRolle;
		this.guid = guid;
	}

	public RechteRolleBericht(RechteRolleBerichtId id, BrBericht brBericht,
			RechteRolle rechteRolle, String guid, Date erstelltAm,
			String erstelltDurch) {
		this.id = id;
		this.brBericht = brBericht;
		this.rechteRolle = rechteRolle;
		this.guid = guid;
		this.erstelltAm = erstelltAm;
		this.erstelltDurch = erstelltDurch;
	}

	public RechteRolleBerichtId getId() {
		return this.id;
	}

	public void setId(RechteRolleBerichtId id) {
		this.id = id;
	}

	public BrBericht getBrBericht() {
		return this.brBericht;
	}

	public void setBrBericht(BrBericht brBericht) {
		this.brBericht = brBericht;
	}

	public RechteRolle getRechteRolle() {
		return this.rechteRolle;
	}

	public void setRechteRolle(RechteRolle rechteRolle) {
		this.rechteRolle = rechteRolle;
	}

	public String getGuid() {
		return this.guid;
	}

	public void setGuid(String guid) {
		this.guid = guid;
	}

	public Date getErstelltAm() {
		return this.erstelltAm;
	}

	public void setErstelltAm(Date erstelltAm) {
		this.erstelltAm = erstelltAm;
	}

	public String getErstelltDurch() {
		return this.erstelltDurch;
	}

	public void setErstelltDurch(String erstelltDurch) {
		this.erstelltDurch = erstelltDurch;
	}

}
