package sernet.gs.reveng;

// Generated Jun 5, 2015 1:28:30 PM by Hibernate Tools 3.4.0.CR1

/**
 * RechteRolleZosId generated by hbm2java
 */
public class RechteRolleZosId implements java.io.Serializable {

	private int rerId;
	private int zosImpId;
	private int zotId;
	private int zosId;

	public RechteRolleZosId() {
	}

	public RechteRolleZosId(int rerId, int zosImpId, int zotId, int zosId) {
		this.rerId = rerId;
		this.zosImpId = zosImpId;
		this.zotId = zotId;
		this.zosId = zosId;
	}

	public int getRerId() {
		return this.rerId;
	}

	public void setRerId(int rerId) {
		this.rerId = rerId;
	}

	public int getZosImpId() {
		return this.zosImpId;
	}

	public void setZosImpId(int zosImpId) {
		this.zosImpId = zosImpId;
	}

	public int getZotId() {
		return this.zotId;
	}

	public void setZotId(int zotId) {
		this.zotId = zotId;
	}

	public int getZosId() {
		return this.zosId;
	}

	public void setZosId(int zosId) {
		this.zosId = zosId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RechteRolleZosId))
			return false;
		RechteRolleZosId castOther = (RechteRolleZosId) other;

		return (this.getRerId() == castOther.getRerId())
				&& (this.getZosImpId() == castOther.getZosImpId())
				&& (this.getZotId() == castOther.getZotId())
				&& (this.getZosId() == castOther.getZosId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getRerId();
		result = 37 * result + this.getZosImpId();
		result = 37 * result + this.getZotId();
		result = 37 * result + this.getZosId();
		return result;
	}

}
