package sernet.gs.reveng;

// Generated Jun 5, 2015 1:28:30 PM by Hibernate Tools 3.4.0.CR1

/**
 * RechteAnwenderRolleId generated by hbm2java
 */
public class RechteAnwenderRolleId implements java.io.Serializable {

	private short uid;
	private int rerId;

	public RechteAnwenderRolleId() {
	}

	public RechteAnwenderRolleId(short uid, int rerId) {
		this.uid = uid;
		this.rerId = rerId;
	}

	public short getUid() {
		return this.uid;
	}

	public void setUid(short uid) {
		this.uid = uid;
	}

	public int getRerId() {
		return this.rerId;
	}

	public void setRerId(int rerId) {
		this.rerId = rerId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RechteAnwenderRolleId))
			return false;
		RechteAnwenderRolleId castOther = (RechteAnwenderRolleId) other;

		return (this.getUid() == castOther.getUid())
				&& (this.getRerId() == castOther.getRerId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getUid();
		result = 37 * result + this.getRerId();
		return result;
	}

}
