package sernet.gs.reveng;

// Generated Jun 5, 2015 1:28:30 PM by Hibernate Tools 3.4.0.CR1

/**
 * RechteProzesse generated by hbm2java
 */
public class RechteProzesse implements java.io.Serializable {

	private RechteProzesseId id;

	public RechteProzesse() {
	}

	public RechteProzesse(RechteProzesseId id) {
		this.id = id;
	}

	public RechteProzesseId getId() {
		return this.id;
	}

	public void setId(RechteProzesseId id) {
		this.id = id;
	}

}
