package sernet.gs.reveng;

// Generated Jun 5, 2015 1:28:30 PM by Hibernate Tools 3.4.0.CR1

/**
 * RechteRolleItvId generated by hbm2java
 */
public class RechteRolleItvId implements java.io.Serializable {

	private int rerId;
	private int itvImpId;
	private int itvId;

	public RechteRolleItvId() {
	}

	public RechteRolleItvId(int rerId, int itvImpId, int itvId) {
		this.rerId = rerId;
		this.itvImpId = itvImpId;
		this.itvId = itvId;
	}

	public int getRerId() {
		return this.rerId;
	}

	public void setRerId(int rerId) {
		this.rerId = rerId;
	}

	public int getItvImpId() {
		return this.itvImpId;
	}

	public void setItvImpId(int itvImpId) {
		this.itvImpId = itvImpId;
	}

	public int getItvId() {
		return this.itvId;
	}

	public void setItvId(int itvId) {
		this.itvId = itvId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RechteRolleItvId))
			return false;
		RechteRolleItvId castOther = (RechteRolleItvId) other;

		return (this.getRerId() == castOther.getRerId())
				&& (this.getItvImpId() == castOther.getItvImpId())
				&& (this.getItvId() == castOther.getItvId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getRerId();
		result = 37 * result + this.getItvImpId();
		result = 37 * result + this.getItvId();
		return result;
	}

}
