package sernet.gs.reveng;

// Generated Jun 5, 2015 1:28:30 PM by Hibernate Tools 3.4.0.CR1

/**
 * StgDtsPackageTxtId generated by hbm2java
 */
public class StgDtsPackageTxtId implements java.io.Serializable {

	private String dtsId;
	private Short sprId;
	private String beschreibung;

	public StgDtsPackageTxtId() {
	}

	public StgDtsPackageTxtId(String dtsId) {
		this.dtsId = dtsId;
	}

	public StgDtsPackageTxtId(String dtsId, Short sprId, String beschreibung) {
		this.dtsId = dtsId;
		this.sprId = sprId;
		this.beschreibung = beschreibung;
	}

	public String getDtsId() {
		return this.dtsId;
	}

	public void setDtsId(String dtsId) {
		this.dtsId = dtsId;
	}

	public Short getSprId() {
		return this.sprId;
	}

	public void setSprId(Short sprId) {
		this.sprId = sprId;
	}

	public String getBeschreibung() {
		return this.beschreibung;
	}

	public void setBeschreibung(String beschreibung) {
		this.beschreibung = beschreibung;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof StgDtsPackageTxtId))
			return false;
		StgDtsPackageTxtId castOther = (StgDtsPackageTxtId) other;

		return ((this.getDtsId() == castOther.getDtsId()) || (this.getDtsId() != null
				&& castOther.getDtsId() != null && this.getDtsId().equals(
				castOther.getDtsId())))
				&& ((this.getSprId() == castOther.getSprId()) || (this
						.getSprId() != null && castOther.getSprId() != null && this
						.getSprId().equals(castOther.getSprId())))
				&& ((this.getBeschreibung() == castOther.getBeschreibung()) || (this
						.getBeschreibung() != null
						&& castOther.getBeschreibung() != null && this
						.getBeschreibung().equals(castOther.getBeschreibung())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getDtsId() == null ? 0 : this.getDtsId().hashCode());
		result = 37 * result
				+ (getSprId() == null ? 0 : this.getSprId().hashCode());
		result = 37
				* result
				+ (getBeschreibung() == null ? 0 : this.getBeschreibung()
						.hashCode());
		return result;
	}

}
