package sernet.gs.reveng;

// Generated Jun 5, 2015 1:28:30 PM by Hibernate Tools 3.4.0.CR1

/**
 * StgFilterSuchenFelderTxt generated by hbm2java
 */
public class StgFilterSuchenFelderTxt implements java.io.Serializable {

	private StgFilterSuchenFelderTxtId id;

	public StgFilterSuchenFelderTxt() {
	}

	public StgFilterSuchenFelderTxt(StgFilterSuchenFelderTxtId id) {
		this.id = id;
	}

	public StgFilterSuchenFelderTxtId getId() {
		return this.id;
	}

	public void setId(StgFilterSuchenFelderTxtId id) {
		this.id = id;
	}

}
