package sernet.gs.reveng;

// Generated Jun 5, 2015 1:28:30 PM by Hibernate Tools 3.4.0.CR1

/**
 * StgG20Sys generated by hbm2java
 */
public class StgG20Sys implements java.io.Serializable {

	private StgG20SysId id;

	public StgG20Sys() {
	}

	public StgG20Sys(StgG20SysId id) {
		this.id = id;
	}

	public StgG20SysId getId() {
		return this.id;
	}

	public void setId(StgG20SysId id) {
		this.id = id;
	}

}
