package sernet.gs.reveng;

// Generated Jun 5, 2015 1:28:30 PM by Hibernate Tools 3.4.0.CR1

/**
 * StgG20ZbesyId generated by hbm2java
 */
public class StgG20ZbesyId implements java.io.Serializable {

	private int benSnr;
	private int sysSnr;

	public StgG20ZbesyId() {
	}

	public StgG20ZbesyId(int benSnr, int sysSnr) {
		this.benSnr = benSnr;
		this.sysSnr = sysSnr;
	}

	public int getBenSnr() {
		return this.benSnr;
	}

	public void setBenSnr(int benSnr) {
		this.benSnr = benSnr;
	}

	public int getSysSnr() {
		return this.sysSnr;
	}

	public void setSysSnr(int sysSnr) {
		this.sysSnr = sysSnr;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof StgG20ZbesyId))
			return false;
		StgG20ZbesyId castOther = (StgG20ZbesyId) other;

		return (this.getBenSnr() == castOther.getBenSnr())
				&& (this.getSysSnr() == castOther.getSysSnr());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getBenSnr();
		result = 37 * result + this.getSysSnr();
		return result;
	}

}
