package sernet.gs.reveng;

// Generated Jun 5, 2015 1:28:30 PM by Hibernate Tools 3.4.0.CR1

/**
 * StgG20MasId generated by hbm2java
 */
public class StgG20MasId implements java.io.Serializable {

	private String typ;
	private String nr;
	private String leiter;
	private String umsetzer;
	private String name;
	private String htxt;
	private Integer sortnr;
	private String leiterOrg;
	private String umsetzerOrg;
	private Integer importflag;

	public StgG20MasId() {
	}

	public StgG20MasId(String nr) {
		this.nr = nr;
	}

	public StgG20MasId(String typ, String nr, String leiter, String umsetzer,
			String name, String htxt, Integer sortnr, String leiterOrg,
			String umsetzerOrg, Integer importflag) {
		this.typ = typ;
		this.nr = nr;
		this.leiter = leiter;
		this.umsetzer = umsetzer;
		this.name = name;
		this.htxt = htxt;
		this.sortnr = sortnr;
		this.leiterOrg = leiterOrg;
		this.umsetzerOrg = umsetzerOrg;
		this.importflag = importflag;
	}

	public String getTyp() {
		return this.typ;
	}

	public void setTyp(String typ) {
		this.typ = typ;
	}

	public String getNr() {
		return this.nr;
	}

	public void setNr(String nr) {
		this.nr = nr;
	}

	public String getLeiter() {
		return this.leiter;
	}

	public void setLeiter(String leiter) {
		this.leiter = leiter;
	}

	public String getUmsetzer() {
		return this.umsetzer;
	}

	public void setUmsetzer(String umsetzer) {
		this.umsetzer = umsetzer;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getHtxt() {
		return this.htxt;
	}

	public void setHtxt(String htxt) {
		this.htxt = htxt;
	}

	public Integer getSortnr() {
		return this.sortnr;
	}

	public void setSortnr(Integer sortnr) {
		this.sortnr = sortnr;
	}

	public String getLeiterOrg() {
		return this.leiterOrg;
	}

	public void setLeiterOrg(String leiterOrg) {
		this.leiterOrg = leiterOrg;
	}

	public String getUmsetzerOrg() {
		return this.umsetzerOrg;
	}

	public void setUmsetzerOrg(String umsetzerOrg) {
		this.umsetzerOrg = umsetzerOrg;
	}

	public Integer getImportflag() {
		return this.importflag;
	}

	public void setImportflag(Integer importflag) {
		this.importflag = importflag;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof StgG20MasId))
			return false;
		StgG20MasId castOther = (StgG20MasId) other;

		return ((this.getTyp() == castOther.getTyp()) || (this.getTyp() != null
				&& castOther.getTyp() != null && this.getTyp().equals(
				castOther.getTyp())))
				&& ((this.getNr() == castOther.getNr()) || (this.getNr() != null
						&& castOther.getNr() != null && this.getNr().equals(
						castOther.getNr())))
				&& ((this.getLeiter() == castOther.getLeiter()) || (this
						.getLeiter() != null && castOther.getLeiter() != null && this
						.getLeiter().equals(castOther.getLeiter())))
				&& ((this.getUmsetzer() == castOther.getUmsetzer()) || (this
						.getUmsetzer() != null
						&& castOther.getUmsetzer() != null && this
						.getUmsetzer().equals(castOther.getUmsetzer())))
				&& ((this.getName() == castOther.getName()) || (this.getName() != null
						&& castOther.getName() != null && this.getName()
						.equals(castOther.getName())))
				&& ((this.getHtxt() == castOther.getHtxt()) || (this.getHtxt() != null
						&& castOther.getHtxt() != null && this.getHtxt()
						.equals(castOther.getHtxt())))
				&& ((this.getSortnr() == castOther.getSortnr()) || (this
						.getSortnr() != null && castOther.getSortnr() != null && this
						.getSortnr().equals(castOther.getSortnr())))
				&& ((this.getLeiterOrg() == castOther.getLeiterOrg()) || (this
						.getLeiterOrg() != null
						&& castOther.getLeiterOrg() != null && this
						.getLeiterOrg().equals(castOther.getLeiterOrg())))
				&& ((this.getUmsetzerOrg() == castOther.getUmsetzerOrg()) || (this
						.getUmsetzerOrg() != null
						&& castOther.getUmsetzerOrg() != null && this
						.getUmsetzerOrg().equals(castOther.getUmsetzerOrg())))
				&& ((this.getImportflag() == castOther.getImportflag()) || (this
						.getImportflag() != null
						&& castOther.getImportflag() != null && this
						.getImportflag().equals(castOther.getImportflag())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getTyp() == null ? 0 : this.getTyp().hashCode());
		result = 37 * result + (getNr() == null ? 0 : this.getNr().hashCode());
		result = 37 * result
				+ (getLeiter() == null ? 0 : this.getLeiter().hashCode());
		result = 37 * result
				+ (getUmsetzer() == null ? 0 : this.getUmsetzer().hashCode());
		result = 37 * result
				+ (getName() == null ? 0 : this.getName().hashCode());
		result = 37 * result
				+ (getHtxt() == null ? 0 : this.getHtxt().hashCode());
		result = 37 * result
				+ (getSortnr() == null ? 0 : this.getSortnr().hashCode());
		result = 37 * result
				+ (getLeiterOrg() == null ? 0 : this.getLeiterOrg().hashCode());
		result = 37
				* result
				+ (getUmsetzerOrg() == null ? 0 : this.getUmsetzerOrg()
						.hashCode());
		result = 37
				* result
				+ (getImportflag() == null ? 0 : this.getImportflag()
						.hashCode());
		return result;
	}

}
