package sernet.gs.reveng;

// Generated Jun 5, 2015 1:28:30 PM by Hibernate Tools 3.4.0.CR1

/**
 * StgG20BenMapping generated by hbm2java
 */
public class StgG20BenMapping implements java.io.Serializable {

	private StgG20BenMappingId id;

	public StgG20BenMapping() {
	}

	public StgG20BenMapping(StgG20BenMappingId id) {
		this.id = id;
	}

	public StgG20BenMappingId getId() {
		return this.id;
	}

	public void setId(StgG20BenMappingId id) {
		this.id = id;
	}

}
