package sernet.gs.reveng;

// Generated Jun 5, 2015 1:28:30 PM by Hibernate Tools 3.4.0.CR1

/**
 * StgG20SclMappingId generated by hbm2java
 */
public class StgG20SclMappingId implements java.io.Serializable {

	private int alteId;
	private int neueId;
	private int zotId;

	public StgG20SclMappingId() {
	}

	public StgG20SclMappingId(int alteId, int neueId, int zotId) {
		this.alteId = alteId;
		this.neueId = neueId;
		this.zotId = zotId;
	}

	public int getAlteId() {
		return this.alteId;
	}

	public void setAlteId(int alteId) {
		this.alteId = alteId;
	}

	public int getNeueId() {
		return this.neueId;
	}

	public void setNeueId(int neueId) {
		this.neueId = neueId;
	}

	public int getZotId() {
		return this.zotId;
	}

	public void setZotId(int zotId) {
		this.zotId = zotId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof StgG20SclMappingId))
			return false;
		StgG20SclMappingId castOther = (StgG20SclMappingId) other;

		return (this.getAlteId() == castOther.getAlteId())
				&& (this.getNeueId() == castOther.getNeueId())
				&& (this.getZotId() == castOther.getZotId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getAlteId();
		result = 37 * result + this.getNeueId();
		result = 37 * result + this.getZotId();
		return result;
	}

}
