package sernet.gs.reveng;

// Generated Jun 5, 2015 1:28:30 PM by Hibernate Tools 3.4.0.CR1

/**
 * StgG20ZosMapping generated by hbm2java
 */
public class StgG20ZosMapping implements java.io.Serializable {

	private StgG20ZosMappingId id;

	public StgG20ZosMapping() {
	}

	public StgG20ZosMapping(StgG20ZosMappingId id) {
		this.id = id;
	}

	public StgG20ZosMappingId getId() {
		return this.id;
	}

	public void setId(StgG20ZosMappingId id) {
		this.id = id;
	}

}
