package sernet.gs.reveng;

// Generated Jun 5, 2015 1:28:30 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * StgModZobjBstId generated by hbm2java
 */
public class StgModZobjBstId implements java.io.Serializable {

	private Integer bauId;
	private Integer bauImpId;
	private Integer zobId;
	private Integer zobImpId;
	private Integer orgImpId;
	private Integer zobIdMit;
	private Integer refZobId;
	private String begruendung;
	private Byte bearbeitet;
	private Date datum;
	private Byte ustId;
	private Integer notizId;
	private Short siegel;
	private Integer stgNeu;
	private Byte impNeu;
	private Integer usn;
	private String guid;
	private String guidOrg;
	private Date timestamp;
	private Date loeschDatum;
	private String geloeschtDurch;
	private Integer mmtId;
	private String erfasstDurch;
	private Byte bearbeitetOrg;
	private Date cmTimestamp;
	private String cmUsername;
	private Short cmVerId2;
	private Byte cmStaId;
	private Byte setDefault;
	private String changedBy;
	private Date changedOn;

	public StgModZobjBstId() {
	}

	public StgModZobjBstId(Integer bauId, Integer bauImpId, Integer zobId,
			Integer zobImpId, Integer orgImpId, Integer zobIdMit,
			Integer refZobId, String begruendung, Byte bearbeitet, Date datum,
			Byte ustId, Integer notizId, Short siegel, Integer stgNeu,
			Byte impNeu, Integer usn, String guid, String guidOrg,
			Date timestamp, Date loeschDatum, String geloeschtDurch,
			Integer mmtId, String erfasstDurch, Byte bearbeitetOrg,
			Date cmTimestamp, String cmUsername, Short cmVerId2, Byte cmStaId,
			Byte setDefault, String changedBy, Date changedOn) {
		this.bauId = bauId;
		this.bauImpId = bauImpId;
		this.zobId = zobId;
		this.zobImpId = zobImpId;
		this.orgImpId = orgImpId;
		this.zobIdMit = zobIdMit;
		this.refZobId = refZobId;
		this.begruendung = begruendung;
		this.bearbeitet = bearbeitet;
		this.datum = datum;
		this.ustId = ustId;
		this.notizId = notizId;
		this.siegel = siegel;
		this.stgNeu = stgNeu;
		this.impNeu = impNeu;
		this.usn = usn;
		this.guid = guid;
		this.guidOrg = guidOrg;
		this.timestamp = timestamp;
		this.loeschDatum = loeschDatum;
		this.geloeschtDurch = geloeschtDurch;
		this.mmtId = mmtId;
		this.erfasstDurch = erfasstDurch;
		this.bearbeitetOrg = bearbeitetOrg;
		this.cmTimestamp = cmTimestamp;
		this.cmUsername = cmUsername;
		this.cmVerId2 = cmVerId2;
		this.cmStaId = cmStaId;
		this.setDefault = setDefault;
		this.changedBy = changedBy;
		this.changedOn = changedOn;
	}

	public Integer getBauId() {
		return this.bauId;
	}

	public void setBauId(Integer bauId) {
		this.bauId = bauId;
	}

	public Integer getBauImpId() {
		return this.bauImpId;
	}

	public void setBauImpId(Integer bauImpId) {
		this.bauImpId = bauImpId;
	}

	public Integer getZobId() {
		return this.zobId;
	}

	public void setZobId(Integer zobId) {
		this.zobId = zobId;
	}

	public Integer getZobImpId() {
		return this.zobImpId;
	}

	public void setZobImpId(Integer zobImpId) {
		this.zobImpId = zobImpId;
	}

	public Integer getOrgImpId() {
		return this.orgImpId;
	}

	public void setOrgImpId(Integer orgImpId) {
		this.orgImpId = orgImpId;
	}

	public Integer getZobIdMit() {
		return this.zobIdMit;
	}

	public void setZobIdMit(Integer zobIdMit) {
		this.zobIdMit = zobIdMit;
	}

	public Integer getRefZobId() {
		return this.refZobId;
	}

	public void setRefZobId(Integer refZobId) {
		this.refZobId = refZobId;
	}

	public String getBegruendung() {
		return this.begruendung;
	}

	public void setBegruendung(String begruendung) {
		this.begruendung = begruendung;
	}

	public Byte getBearbeitet() {
		return this.bearbeitet;
	}

	public void setBearbeitet(Byte bearbeitet) {
		this.bearbeitet = bearbeitet;
	}

	public Date getDatum() {
		return this.datum;
	}

	public void setDatum(Date datum) {
		this.datum = datum;
	}

	public Byte getUstId() {
		return this.ustId;
	}

	public void setUstId(Byte ustId) {
		this.ustId = ustId;
	}

	public Integer getNotizId() {
		return this.notizId;
	}

	public void setNotizId(Integer notizId) {
		this.notizId = notizId;
	}

	public Short getSiegel() {
		return this.siegel;
	}

	public void setSiegel(Short siegel) {
		this.siegel = siegel;
	}

	public Integer getStgNeu() {
		return this.stgNeu;
	}

	public void setStgNeu(Integer stgNeu) {
		this.stgNeu = stgNeu;
	}

	public Byte getImpNeu() {
		return this.impNeu;
	}

	public void setImpNeu(Byte impNeu) {
		this.impNeu = impNeu;
	}

	public Integer getUsn() {
		return this.usn;
	}

	public void setUsn(Integer usn) {
		this.usn = usn;
	}

	public String getGuid() {
		return this.guid;
	}

	public void setGuid(String guid) {
		this.guid = guid;
	}

	public String getGuidOrg() {
		return this.guidOrg;
	}

	public void setGuidOrg(String guidOrg) {
		this.guidOrg = guidOrg;
	}

	public Date getTimestamp() {
		return this.timestamp;
	}

	public void setTimestamp(Date timestamp) {
		this.timestamp = timestamp;
	}

	public Date getLoeschDatum() {
		return this.loeschDatum;
	}

	public void setLoeschDatum(Date loeschDatum) {
		this.loeschDatum = loeschDatum;
	}

	public String getGeloeschtDurch() {
		return this.geloeschtDurch;
	}

	public void setGeloeschtDurch(String geloeschtDurch) {
		this.geloeschtDurch = geloeschtDurch;
	}

	public Integer getMmtId() {
		return this.mmtId;
	}

	public void setMmtId(Integer mmtId) {
		this.mmtId = mmtId;
	}

	public String getErfasstDurch() {
		return this.erfasstDurch;
	}

	public void setErfasstDurch(String erfasstDurch) {
		this.erfasstDurch = erfasstDurch;
	}

	public Byte getBearbeitetOrg() {
		return this.bearbeitetOrg;
	}

	public void setBearbeitetOrg(Byte bearbeitetOrg) {
		this.bearbeitetOrg = bearbeitetOrg;
	}

	public Date getCmTimestamp() {
		return this.cmTimestamp;
	}

	public void setCmTimestamp(Date cmTimestamp) {
		this.cmTimestamp = cmTimestamp;
	}

	public String getCmUsername() {
		return this.cmUsername;
	}

	public void setCmUsername(String cmUsername) {
		this.cmUsername = cmUsername;
	}

	public Short getCmVerId2() {
		return this.cmVerId2;
	}

	public void setCmVerId2(Short cmVerId2) {
		this.cmVerId2 = cmVerId2;
	}

	public Byte getCmStaId() {
		return this.cmStaId;
	}

	public void setCmStaId(Byte cmStaId) {
		this.cmStaId = cmStaId;
	}

	public Byte getSetDefault() {
		return this.setDefault;
	}

	public void setSetDefault(Byte setDefault) {
		this.setDefault = setDefault;
	}

	public String getChangedBy() {
		return this.changedBy;
	}

	public void setChangedBy(String changedBy) {
		this.changedBy = changedBy;
	}

	public Date getChangedOn() {
		return this.changedOn;
	}

	public void setChangedOn(Date changedOn) {
		this.changedOn = changedOn;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof StgModZobjBstId))
			return false;
		StgModZobjBstId castOther = (StgModZobjBstId) other;

		return ((this.getBauId() == castOther.getBauId()) || (this.getBauId() != null
				&& castOther.getBauId() != null && this.getBauId().equals(
				castOther.getBauId())))
				&& ((this.getBauImpId() == castOther.getBauImpId()) || (this
						.getBauImpId() != null
						&& castOther.getBauImpId() != null && this
						.getBauImpId().equals(castOther.getBauImpId())))
				&& ((this.getZobId() == castOther.getZobId()) || (this
						.getZobId() != null && castOther.getZobId() != null && this
						.getZobId().equals(castOther.getZobId())))
				&& ((this.getZobImpId() == castOther.getZobImpId()) || (this
						.getZobImpId() != null
						&& castOther.getZobImpId() != null && this
						.getZobImpId().equals(castOther.getZobImpId())))
				&& ((this.getOrgImpId() == castOther.getOrgImpId()) || (this
						.getOrgImpId() != null
						&& castOther.getOrgImpId() != null && this
						.getOrgImpId().equals(castOther.getOrgImpId())))
				&& ((this.getZobIdMit() == castOther.getZobIdMit()) || (this
						.getZobIdMit() != null
						&& castOther.getZobIdMit() != null && this
						.getZobIdMit().equals(castOther.getZobIdMit())))
				&& ((this.getRefZobId() == castOther.getRefZobId()) || (this
						.getRefZobId() != null
						&& castOther.getRefZobId() != null && this
						.getRefZobId().equals(castOther.getRefZobId())))
				&& ((this.getBegruendung() == castOther.getBegruendung()) || (this
						.getBegruendung() != null
						&& castOther.getBegruendung() != null && this
						.getBegruendung().equals(castOther.getBegruendung())))
				&& ((this.getBearbeitet() == castOther.getBearbeitet()) || (this
						.getBearbeitet() != null
						&& castOther.getBearbeitet() != null && this
						.getBearbeitet().equals(castOther.getBearbeitet())))
				&& ((this.getDatum() == castOther.getDatum()) || (this
						.getDatum() != null && castOther.getDatum() != null && this
						.getDatum().equals(castOther.getDatum())))
				&& ((this.getUstId() == castOther.getUstId()) || (this
						.getUstId() != null && castOther.getUstId() != null && this
						.getUstId().equals(castOther.getUstId())))
				&& ((this.getNotizId() == castOther.getNotizId()) || (this
						.getNotizId() != null && castOther.getNotizId() != null && this
						.getNotizId().equals(castOther.getNotizId())))
				&& ((this.getSiegel() == castOther.getSiegel()) || (this
						.getSiegel() != null && castOther.getSiegel() != null && this
						.getSiegel().equals(castOther.getSiegel())))
				&& ((this.getStgNeu() == castOther.getStgNeu()) || (this
						.getStgNeu() != null && castOther.getStgNeu() != null && this
						.getStgNeu().equals(castOther.getStgNeu())))
				&& ((this.getImpNeu() == castOther.getImpNeu()) || (this
						.getImpNeu() != null && castOther.getImpNeu() != null && this
						.getImpNeu().equals(castOther.getImpNeu())))
				&& ((this.getUsn() == castOther.getUsn()) || (this.getUsn() != null
						&& castOther.getUsn() != null && this.getUsn().equals(
						castOther.getUsn())))
				&& ((this.getGuid() == castOther.getGuid()) || (this.getGuid() != null
						&& castOther.getGuid() != null && this.getGuid()
						.equals(castOther.getGuid())))
				&& ((this.getGuidOrg() == castOther.getGuidOrg()) || (this
						.getGuidOrg() != null && castOther.getGuidOrg() != null && this
						.getGuidOrg().equals(castOther.getGuidOrg())))
				&& ((this.getTimestamp() == castOther.getTimestamp()) || (this
						.getTimestamp() != null
						&& castOther.getTimestamp() != null && this
						.getTimestamp().equals(castOther.getTimestamp())))
				&& ((this.getLoeschDatum() == castOther.getLoeschDatum()) || (this
						.getLoeschDatum() != null
						&& castOther.getLoeschDatum() != null && this
						.getLoeschDatum().equals(castOther.getLoeschDatum())))
				&& ((this.getGeloeschtDurch() == castOther.getGeloeschtDurch()) || (this
						.getGeloeschtDurch() != null
						&& castOther.getGeloeschtDurch() != null && this
						.getGeloeschtDurch().equals(
								castOther.getGeloeschtDurch())))
				&& ((this.getMmtId() == castOther.getMmtId()) || (this
						.getMmtId() != null && castOther.getMmtId() != null && this
						.getMmtId().equals(castOther.getMmtId())))
				&& ((this.getErfasstDurch() == castOther.getErfasstDurch()) || (this
						.getErfasstDurch() != null
						&& castOther.getErfasstDurch() != null && this
						.getErfasstDurch().equals(castOther.getErfasstDurch())))
				&& ((this.getBearbeitetOrg() == castOther.getBearbeitetOrg()) || (this
						.getBearbeitetOrg() != null
						&& castOther.getBearbeitetOrg() != null && this
						.getBearbeitetOrg()
						.equals(castOther.getBearbeitetOrg())))
				&& ((this.getCmTimestamp() == castOther.getCmTimestamp()) || (this
						.getCmTimestamp() != null
						&& castOther.getCmTimestamp() != null && this
						.getCmTimestamp().equals(castOther.getCmTimestamp())))
				&& ((this.getCmUsername() == castOther.getCmUsername()) || (this
						.getCmUsername() != null
						&& castOther.getCmUsername() != null && this
						.getCmUsername().equals(castOther.getCmUsername())))
				&& ((this.getCmVerId2() == castOther.getCmVerId2()) || (this
						.getCmVerId2() != null
						&& castOther.getCmVerId2() != null && this
						.getCmVerId2().equals(castOther.getCmVerId2())))
				&& ((this.getCmStaId() == castOther.getCmStaId()) || (this
						.getCmStaId() != null && castOther.getCmStaId() != null && this
						.getCmStaId().equals(castOther.getCmStaId())))
				&& ((this.getSetDefault() == castOther.getSetDefault()) || (this
						.getSetDefault() != null
						&& castOther.getSetDefault() != null && this
						.getSetDefault().equals(castOther.getSetDefault())))
				&& ((this.getChangedBy() == castOther.getChangedBy()) || (this
						.getChangedBy() != null
						&& castOther.getChangedBy() != null && this
						.getChangedBy().equals(castOther.getChangedBy())))
				&& ((this.getChangedOn() == castOther.getChangedOn()) || (this
						.getChangedOn() != null
						&& castOther.getChangedOn() != null && this
						.getChangedOn().equals(castOther.getChangedOn())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getBauId() == null ? 0 : this.getBauId().hashCode());
		result = 37 * result
				+ (getBauImpId() == null ? 0 : this.getBauImpId().hashCode());
		result = 37 * result
				+ (getZobId() == null ? 0 : this.getZobId().hashCode());
		result = 37 * result
				+ (getZobImpId() == null ? 0 : this.getZobImpId().hashCode());
		result = 37 * result
				+ (getOrgImpId() == null ? 0 : this.getOrgImpId().hashCode());
		result = 37 * result
				+ (getZobIdMit() == null ? 0 : this.getZobIdMit().hashCode());
		result = 37 * result
				+ (getRefZobId() == null ? 0 : this.getRefZobId().hashCode());
		result = 37
				* result
				+ (getBegruendung() == null ? 0 : this.getBegruendung()
						.hashCode());
		result = 37
				* result
				+ (getBearbeitet() == null ? 0 : this.getBearbeitet()
						.hashCode());
		result = 37 * result
				+ (getDatum() == null ? 0 : this.getDatum().hashCode());
		result = 37 * result
				+ (getUstId() == null ? 0 : this.getUstId().hashCode());
		result = 37 * result
				+ (getNotizId() == null ? 0 : this.getNotizId().hashCode());
		result = 37 * result
				+ (getSiegel() == null ? 0 : this.getSiegel().hashCode());
		result = 37 * result
				+ (getStgNeu() == null ? 0 : this.getStgNeu().hashCode());
		result = 37 * result
				+ (getImpNeu() == null ? 0 : this.getImpNeu().hashCode());
		result = 37 * result
				+ (getUsn() == null ? 0 : this.getUsn().hashCode());
		result = 37 * result
				+ (getGuid() == null ? 0 : this.getGuid().hashCode());
		result = 37 * result
				+ (getGuidOrg() == null ? 0 : this.getGuidOrg().hashCode());
		result = 37 * result
				+ (getTimestamp() == null ? 0 : this.getTimestamp().hashCode());
		result = 37
				* result
				+ (getLoeschDatum() == null ? 0 : this.getLoeschDatum()
						.hashCode());
		result = 37
				* result
				+ (getGeloeschtDurch() == null ? 0 : this.getGeloeschtDurch()
						.hashCode());
		result = 37 * result
				+ (getMmtId() == null ? 0 : this.getMmtId().hashCode());
		result = 37
				* result
				+ (getErfasstDurch() == null ? 0 : this.getErfasstDurch()
						.hashCode());
		result = 37
				* result
				+ (getBearbeitetOrg() == null ? 0 : this.getBearbeitetOrg()
						.hashCode());
		result = 37
				* result
				+ (getCmTimestamp() == null ? 0 : this.getCmTimestamp()
						.hashCode());
		result = 37
				* result
				+ (getCmUsername() == null ? 0 : this.getCmUsername()
						.hashCode());
		result = 37 * result
				+ (getCmVerId2() == null ? 0 : this.getCmVerId2().hashCode());
		result = 37 * result
				+ (getCmStaId() == null ? 0 : this.getCmStaId().hashCode());
		result = 37
				* result
				+ (getSetDefault() == null ? 0 : this.getSetDefault()
						.hashCode());
		result = 37 * result
				+ (getChangedBy() == null ? 0 : this.getChangedBy().hashCode());
		result = 37 * result
				+ (getChangedOn() == null ? 0 : this.getChangedOn().hashCode());
		return result;
	}

}
