package sernet.gs.reveng;

// Generated Jun 5, 2015 1:28:30 PM by Hibernate Tools 3.4.0.CR1

/**
 * StgMbZeiteinheitenTxt generated by hbm2java
 */
public class StgMbZeiteinheitenTxt implements java.io.Serializable {

	private StgMbZeiteinheitenTxtId id;

	public StgMbZeiteinheitenTxt() {
	}

	public StgMbZeiteinheitenTxt(StgMbZeiteinheitenTxtId id) {
		this.id = id;
	}

	public StgMbZeiteinheitenTxtId getId() {
		return this.id;
	}

	public void setId(StgMbZeiteinheitenTxtId id) {
		this.id = id;
	}

}
