package sernet.gs.reveng;

// Generated Jun 5, 2015 1:28:30 PM by Hibernate Tools 3.4.0.CR1

/**
 * StgMapRerId generated by hbm2java
 */
public class StgMapRerId implements java.io.Serializable {

	private int altId;
	private int neuId;

	public StgMapRerId() {
	}

	public StgMapRerId(int altId, int neuId) {
		this.altId = altId;
		this.neuId = neuId;
	}

	public int getAltId() {
		return this.altId;
	}

	public void setAltId(int altId) {
		this.altId = altId;
	}

	public int getNeuId() {
		return this.neuId;
	}

	public void setNeuId(int neuId) {
		this.neuId = neuId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof StgMapRerId))
			return false;
		StgMapRerId castOther = (StgMapRerId) other;

		return (this.getAltId() == castOther.getAltId())
				&& (this.getNeuId() == castOther.getNeuId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getAltId();
		result = 37 * result + this.getNeuId();
		return result;
	}

}
