package sernet.gs.reveng;

// Generated Jun 5, 2015 1:28:30 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * StgMbDelMassnId generated by hbm2java
 */
public class StgMbDelMassnId implements java.io.Serializable {

	private Integer masId;
	private Integer masImpId;
	private Integer impId;
	private Date timestamp;
	private String guid;
	private String geloeschtDurch;

	public StgMbDelMassnId() {
	}

	public StgMbDelMassnId(Integer masId, Integer masImpId, Integer impId,
			Date timestamp, String guid, String geloeschtDurch) {
		this.masId = masId;
		this.masImpId = masImpId;
		this.impId = impId;
		this.timestamp = timestamp;
		this.guid = guid;
		this.geloeschtDurch = geloeschtDurch;
	}

	public Integer getMasId() {
		return this.masId;
	}

	public void setMasId(Integer masId) {
		this.masId = masId;
	}

	public Integer getMasImpId() {
		return this.masImpId;
	}

	public void setMasImpId(Integer masImpId) {
		this.masImpId = masImpId;
	}

	public Integer getImpId() {
		return this.impId;
	}

	public void setImpId(Integer impId) {
		this.impId = impId;
	}

	public Date getTimestamp() {
		return this.timestamp;
	}

	public void setTimestamp(Date timestamp) {
		this.timestamp = timestamp;
	}

	public String getGuid() {
		return this.guid;
	}

	public void setGuid(String guid) {
		this.guid = guid;
	}

	public String getGeloeschtDurch() {
		return this.geloeschtDurch;
	}

	public void setGeloeschtDurch(String geloeschtDurch) {
		this.geloeschtDurch = geloeschtDurch;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof StgMbDelMassnId))
			return false;
		StgMbDelMassnId castOther = (StgMbDelMassnId) other;

		return ((this.getMasId() == castOther.getMasId()) || (this.getMasId() != null
				&& castOther.getMasId() != null && this.getMasId().equals(
				castOther.getMasId())))
				&& ((this.getMasImpId() == castOther.getMasImpId()) || (this
						.getMasImpId() != null
						&& castOther.getMasImpId() != null && this
						.getMasImpId().equals(castOther.getMasImpId())))
				&& ((this.getImpId() == castOther.getImpId()) || (this
						.getImpId() != null && castOther.getImpId() != null && this
						.getImpId().equals(castOther.getImpId())))
				&& ((this.getTimestamp() == castOther.getTimestamp()) || (this
						.getTimestamp() != null
						&& castOther.getTimestamp() != null && this
						.getTimestamp().equals(castOther.getTimestamp())))
				&& ((this.getGuid() == castOther.getGuid()) || (this.getGuid() != null
						&& castOther.getGuid() != null && this.getGuid()
						.equals(castOther.getGuid())))
				&& ((this.getGeloeschtDurch() == castOther.getGeloeschtDurch()) || (this
						.getGeloeschtDurch() != null
						&& castOther.getGeloeschtDurch() != null && this
						.getGeloeschtDurch().equals(
								castOther.getGeloeschtDurch())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getMasId() == null ? 0 : this.getMasId().hashCode());
		result = 37 * result
				+ (getMasImpId() == null ? 0 : this.getMasImpId().hashCode());
		result = 37 * result
				+ (getImpId() == null ? 0 : this.getImpId().hashCode());
		result = 37 * result
				+ (getTimestamp() == null ? 0 : this.getTimestamp().hashCode());
		result = 37 * result
				+ (getGuid() == null ? 0 : this.getGuid().hashCode());
		result = 37
				* result
				+ (getGeloeschtDurch() == null ? 0 : this.getGeloeschtDurch()
						.hashCode());
		return result;
	}

}
