package sernet.gs.reveng;

// Generated Jun 5, 2015 1:28:30 PM by Hibernate Tools 3.4.0.CR1

/**
 * StgMapM31ZusId generated by hbm2java
 */
public class StgMapM31ZusId implements java.io.Serializable {

	private int altZotId;
	private int altImpId;
	private String name;
	private int neuZotId;
	private int neuImpId;
	private int zusId;

	public StgMapM31ZusId() {
	}

	public StgMapM31ZusId(int altZotId, int altImpId, String name,
			int neuZotId, int neuImpId, int zusId) {
		this.altZotId = altZotId;
		this.altImpId = altImpId;
		this.name = name;
		this.neuZotId = neuZotId;
		this.neuImpId = neuImpId;
		this.zusId = zusId;
	}

	public int getAltZotId() {
		return this.altZotId;
	}

	public void setAltZotId(int altZotId) {
		this.altZotId = altZotId;
	}

	public int getAltImpId() {
		return this.altImpId;
	}

	public void setAltImpId(int altImpId) {
		this.altImpId = altImpId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public int getNeuZotId() {
		return this.neuZotId;
	}

	public void setNeuZotId(int neuZotId) {
		this.neuZotId = neuZotId;
	}

	public int getNeuImpId() {
		return this.neuImpId;
	}

	public void setNeuImpId(int neuImpId) {
		this.neuImpId = neuImpId;
	}

	public int getZusId() {
		return this.zusId;
	}

	public void setZusId(int zusId) {
		this.zusId = zusId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof StgMapM31ZusId))
			return false;
		StgMapM31ZusId castOther = (StgMapM31ZusId) other;

		return (this.getAltZotId() == castOther.getAltZotId())
				&& (this.getAltImpId() == castOther.getAltImpId())
				&& ((this.getName() == castOther.getName()) || (this.getName() != null
						&& castOther.getName() != null && this.getName()
						.equals(castOther.getName())))
				&& (this.getNeuZotId() == castOther.getNeuZotId())
				&& (this.getNeuImpId() == castOther.getNeuImpId())
				&& (this.getZusId() == castOther.getZusId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getAltZotId();
		result = 37 * result + this.getAltImpId();
		result = 37 * result
				+ (getName() == null ? 0 : this.getName().hashCode());
		result = 37 * result + this.getNeuZotId();
		result = 37 * result + this.getNeuImpId();
		result = 37 * result + this.getZusId();
		return result;
	}

}
