package sernet.gs.reveng;

// Generated Jun 5, 2015 1:28:30 PM by Hibernate Tools 3.4.0.CR1

/**
 * StgMsDatatype generated by hbm2java
 */
public class StgMsDatatype implements java.io.Serializable {

	private StgMsDatatypeId id;

	public StgMsDatatype() {
	}

	public StgMsDatatype(StgMsDatatypeId id) {
		this.id = id;
	}

	public StgMsDatatypeId getId() {
		return this.id;
	}

	public void setId(StgMsDatatypeId id) {
		this.id = id;
	}

}
