package sernet.gs.reveng;

// Generated Jun 5, 2015 1:28:30 PM by Hibernate Tools 3.4.0.CR1

/**
 * StgMbMassnnkatTxt generated by hbm2java
 */
public class StgMbMassnnkatTxt implements java.io.Serializable {

	private StgMbMassnnkatTxtId id;

	public StgMbMassnnkatTxt() {
	}

	public StgMbMassnnkatTxt(StgMbMassnnkatTxtId id) {
		this.id = id;
	}

	public StgMbMassnnkatTxtId getId() {
		return this.id;
	}

	public void setId(StgMbMassnnkatTxtId id) {
		this.id = id;
	}

}
