package sernet.gs.reveng;

// Generated Jun 5, 2015 1:28:30 PM by Hibernate Tools 3.4.0.CR1

import java.sql.Clob;
import java.util.Date;

/**
 * StgMbGefaehrTxtId generated by hbm2java
 */
public class StgMbGefaehrTxtId implements java.io.Serializable {

	private Integer gefId;
	private Integer gefImpId;
	private Short sprId;
	private String name;
	private Clob beschreibung;
	private Clob htmltext;
	private String guid;
	private Date timestamp;
	private String guidOrg;
	private String abstract_;
	private String changedBy;
	private Date changedOn;

	public StgMbGefaehrTxtId() {
	}

	public StgMbGefaehrTxtId(Integer gefId, Integer gefImpId, Short sprId,
			String name, Clob beschreibung, Clob htmltext, String guid,
			Date timestamp, String guidOrg, String abstract_, String changedBy,
			Date changedOn) {
		this.gefId = gefId;
		this.gefImpId = gefImpId;
		this.sprId = sprId;
		this.name = name;
		this.beschreibung = beschreibung;
		this.htmltext = htmltext;
		this.guid = guid;
		this.timestamp = timestamp;
		this.guidOrg = guidOrg;
		this.abstract_ = abstract_;
		this.changedBy = changedBy;
		this.changedOn = changedOn;
	}

	public Integer getGefId() {
		return this.gefId;
	}

	public void setGefId(Integer gefId) {
		this.gefId = gefId;
	}

	public Integer getGefImpId() {
		return this.gefImpId;
	}

	public void setGefImpId(Integer gefImpId) {
		this.gefImpId = gefImpId;
	}

	public Short getSprId() {
		return this.sprId;
	}

	public void setSprId(Short sprId) {
		this.sprId = sprId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Clob getBeschreibung() {
		return this.beschreibung;
	}

	public void setBeschreibung(Clob beschreibung) {
		this.beschreibung = beschreibung;
	}

	public Clob getHtmltext() {
		return this.htmltext;
	}

	public void setHtmltext(Clob htmltext) {
		this.htmltext = htmltext;
	}

	public String getGuid() {
		return this.guid;
	}

	public void setGuid(String guid) {
		this.guid = guid;
	}

	public Date getTimestamp() {
		return this.timestamp;
	}

	public void setTimestamp(Date timestamp) {
		this.timestamp = timestamp;
	}

	public String getGuidOrg() {
		return this.guidOrg;
	}

	public void setGuidOrg(String guidOrg) {
		this.guidOrg = guidOrg;
	}

	public String getAbstract_() {
		return this.abstract_;
	}

	public void setAbstract_(String abstract_) {
		this.abstract_ = abstract_;
	}

	public String getChangedBy() {
		return this.changedBy;
	}

	public void setChangedBy(String changedBy) {
		this.changedBy = changedBy;
	}

	public Date getChangedOn() {
		return this.changedOn;
	}

	public void setChangedOn(Date changedOn) {
		this.changedOn = changedOn;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof StgMbGefaehrTxtId))
			return false;
		StgMbGefaehrTxtId castOther = (StgMbGefaehrTxtId) other;

		return ((this.getGefId() == castOther.getGefId()) || (this.getGefId() != null
				&& castOther.getGefId() != null && this.getGefId().equals(
				castOther.getGefId())))
				&& ((this.getGefImpId() == castOther.getGefImpId()) || (this
						.getGefImpId() != null
						&& castOther.getGefImpId() != null && this
						.getGefImpId().equals(castOther.getGefImpId())))
				&& ((this.getSprId() == castOther.getSprId()) || (this
						.getSprId() != null && castOther.getSprId() != null && this
						.getSprId().equals(castOther.getSprId())))
				&& ((this.getName() == castOther.getName()) || (this.getName() != null
						&& castOther.getName() != null && this.getName()
						.equals(castOther.getName())))
				&& ((this.getBeschreibung() == castOther.getBeschreibung()) || (this
						.getBeschreibung() != null
						&& castOther.getBeschreibung() != null && this
						.getBeschreibung().equals(castOther.getBeschreibung())))
				&& ((this.getHtmltext() == castOther.getHtmltext()) || (this
						.getHtmltext() != null
						&& castOther.getHtmltext() != null && this
						.getHtmltext().equals(castOther.getHtmltext())))
				&& ((this.getGuid() == castOther.getGuid()) || (this.getGuid() != null
						&& castOther.getGuid() != null && this.getGuid()
						.equals(castOther.getGuid())))
				&& ((this.getTimestamp() == castOther.getTimestamp()) || (this
						.getTimestamp() != null
						&& castOther.getTimestamp() != null && this
						.getTimestamp().equals(castOther.getTimestamp())))
				&& ((this.getGuidOrg() == castOther.getGuidOrg()) || (this
						.getGuidOrg() != null && castOther.getGuidOrg() != null && this
						.getGuidOrg().equals(castOther.getGuidOrg())))
				&& ((this.getAbstract_() == castOther.getAbstract_()) || (this
						.getAbstract_() != null
						&& castOther.getAbstract_() != null && this
						.getAbstract_().equals(castOther.getAbstract_())))
				&& ((this.getChangedBy() == castOther.getChangedBy()) || (this
						.getChangedBy() != null
						&& castOther.getChangedBy() != null && this
						.getChangedBy().equals(castOther.getChangedBy())))
				&& ((this.getChangedOn() == castOther.getChangedOn()) || (this
						.getChangedOn() != null
						&& castOther.getChangedOn() != null && this
						.getChangedOn().equals(castOther.getChangedOn())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getGefId() == null ? 0 : this.getGefId().hashCode());
		result = 37 * result
				+ (getGefImpId() == null ? 0 : this.getGefImpId().hashCode());
		result = 37 * result
				+ (getSprId() == null ? 0 : this.getSprId().hashCode());
		result = 37 * result
				+ (getName() == null ? 0 : this.getName().hashCode());
		result = 37
				* result
				+ (getBeschreibung() == null ? 0 : this.getBeschreibung()
						.hashCode());
		result = 37 * result
				+ (getHtmltext() == null ? 0 : this.getHtmltext().hashCode());
		result = 37 * result
				+ (getGuid() == null ? 0 : this.getGuid().hashCode());
		result = 37 * result
				+ (getTimestamp() == null ? 0 : this.getTimestamp().hashCode());
		result = 37 * result
				+ (getGuidOrg() == null ? 0 : this.getGuidOrg().hashCode());
		result = 37 * result
				+ (getAbstract_() == null ? 0 : this.getAbstract_().hashCode());
		result = 37 * result
				+ (getChangedBy() == null ? 0 : this.getChangedBy().hashCode());
		result = 37 * result
				+ (getChangedOn() == null ? 0 : this.getChangedOn().hashCode());
		return result;
	}

}
