package sernet.gs.reveng;

// Generated Jun 5, 2015 1:28:30 PM by Hibernate Tools 3.4.0.CR1

/**
 * StgMapNotizId generated by hbm2java
 */
public class StgMapNotizId implements java.io.Serializable {

	private int altId;
	private int altImpId;
	private int neuId;
	private int neuImpId;
	private int urlId;

	public StgMapNotizId() {
	}

	public StgMapNotizId(int altId, int altImpId, int neuId, int neuImpId,
			int urlId) {
		this.altId = altId;
		this.altImpId = altImpId;
		this.neuId = neuId;
		this.neuImpId = neuImpId;
		this.urlId = urlId;
	}

	public int getAltId() {
		return this.altId;
	}

	public void setAltId(int altId) {
		this.altId = altId;
	}

	public int getAltImpId() {
		return this.altImpId;
	}

	public void setAltImpId(int altImpId) {
		this.altImpId = altImpId;
	}

	public int getNeuId() {
		return this.neuId;
	}

	public void setNeuId(int neuId) {
		this.neuId = neuId;
	}

	public int getNeuImpId() {
		return this.neuImpId;
	}

	public void setNeuImpId(int neuImpId) {
		this.neuImpId = neuImpId;
	}

	public int getUrlId() {
		return this.urlId;
	}

	public void setUrlId(int urlId) {
		this.urlId = urlId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof StgMapNotizId))
			return false;
		StgMapNotizId castOther = (StgMapNotizId) other;

		return (this.getAltId() == castOther.getAltId())
				&& (this.getAltImpId() == castOther.getAltImpId())
				&& (this.getNeuId() == castOther.getNeuId())
				&& (this.getNeuImpId() == castOther.getNeuImpId())
				&& (this.getUrlId() == castOther.getUrlId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getAltId();
		result = 37 * result + this.getAltImpId();
		result = 37 * result + this.getNeuId();
		result = 37 * result + this.getNeuImpId();
		result = 37 * result + this.getUrlId();
		return result;
	}

}
