package sernet.gs.reveng;

// Generated Jun 5, 2015 1:28:30 PM by Hibernate Tools 3.4.0.CR1

/**
 * StgMMetatypTxt generated by hbm2java
 */
public class StgMMetatypTxt implements java.io.Serializable {

	private StgMMetatypTxtId id;

	public StgMMetatypTxt() {
	}

	public StgMMetatypTxt(StgMMetatypTxtId id) {
		this.id = id;
	}

	public StgMMetatypTxtId getId() {
		return this.id;
	}

	public void setId(StgMMetatypTxtId id) {
		this.id = id;
	}

}
