package sernet.gs.reveng;

// Generated Jun 5, 2015 1:28:30 PM by Hibernate Tools 3.4.0.CR1

/**
 * StgMMetastatusTxt generated by hbm2java
 */
public class StgMMetastatusTxt implements java.io.Serializable {

	private StgMMetastatusTxtId id;

	public StgMMetastatusTxt() {
	}

	public StgMMetastatusTxt(StgMMetastatusTxtId id) {
		this.id = id;
	}

	public StgMMetastatusTxtId getId() {
		return this.id;
	}

	public void setId(StgMMetastatusTxtId id) {
		this.id = id;
	}

}
