package sernet.gs.reveng;

// Generated Jun 5, 2015 1:28:30 PM by Hibernate Tools 3.4.0.CR1

/**
 * StgMapZotZusId generated by hbm2java
 */
public class StgMapZotZusId implements java.io.Serializable {

	private Integer altId;
	private Integer altImpId;
	private Integer altZusId;
	private Integer neuId;
	private Integer neuImpId;
	private Integer neuZusId;
	private Integer dtyId;
	private String name;
	private Short length;
	private Short prec;
	private Short scale;
	private Integer waeId;
	private Integer waeImpId;
	private Boolean inserted;

	public StgMapZotZusId() {
	}

	public StgMapZotZusId(Integer altId, Integer altImpId, Integer altZusId,
			Integer neuId, Integer neuImpId, Integer neuZusId, Integer dtyId,
			String name, Short length, Short prec, Short scale, Integer waeId,
			Integer waeImpId, Boolean inserted) {
		this.altId = altId;
		this.altImpId = altImpId;
		this.altZusId = altZusId;
		this.neuId = neuId;
		this.neuImpId = neuImpId;
		this.neuZusId = neuZusId;
		this.dtyId = dtyId;
		this.name = name;
		this.length = length;
		this.prec = prec;
		this.scale = scale;
		this.waeId = waeId;
		this.waeImpId = waeImpId;
		this.inserted = inserted;
	}

	public Integer getAltId() {
		return this.altId;
	}

	public void setAltId(Integer altId) {
		this.altId = altId;
	}

	public Integer getAltImpId() {
		return this.altImpId;
	}

	public void setAltImpId(Integer altImpId) {
		this.altImpId = altImpId;
	}

	public Integer getAltZusId() {
		return this.altZusId;
	}

	public void setAltZusId(Integer altZusId) {
		this.altZusId = altZusId;
	}

	public Integer getNeuId() {
		return this.neuId;
	}

	public void setNeuId(Integer neuId) {
		this.neuId = neuId;
	}

	public Integer getNeuImpId() {
		return this.neuImpId;
	}

	public void setNeuImpId(Integer neuImpId) {
		this.neuImpId = neuImpId;
	}

	public Integer getNeuZusId() {
		return this.neuZusId;
	}

	public void setNeuZusId(Integer neuZusId) {
		this.neuZusId = neuZusId;
	}

	public Integer getDtyId() {
		return this.dtyId;
	}

	public void setDtyId(Integer dtyId) {
		this.dtyId = dtyId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Short getLength() {
		return this.length;
	}

	public void setLength(Short length) {
		this.length = length;
	}

	public Short getPrec() {
		return this.prec;
	}

	public void setPrec(Short prec) {
		this.prec = prec;
	}

	public Short getScale() {
		return this.scale;
	}

	public void setScale(Short scale) {
		this.scale = scale;
	}

	public Integer getWaeId() {
		return this.waeId;
	}

	public void setWaeId(Integer waeId) {
		this.waeId = waeId;
	}

	public Integer getWaeImpId() {
		return this.waeImpId;
	}

	public void setWaeImpId(Integer waeImpId) {
		this.waeImpId = waeImpId;
	}

	public Boolean getInserted() {
		return this.inserted;
	}

	public void setInserted(Boolean inserted) {
		this.inserted = inserted;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof StgMapZotZusId))
			return false;
		StgMapZotZusId castOther = (StgMapZotZusId) other;

		return ((this.getAltId() == castOther.getAltId()) || (this.getAltId() != null
				&& castOther.getAltId() != null && this.getAltId().equals(
				castOther.getAltId())))
				&& ((this.getAltImpId() == castOther.getAltImpId()) || (this
						.getAltImpId() != null
						&& castOther.getAltImpId() != null && this
						.getAltImpId().equals(castOther.getAltImpId())))
				&& ((this.getAltZusId() == castOther.getAltZusId()) || (this
						.getAltZusId() != null
						&& castOther.getAltZusId() != null && this
						.getAltZusId().equals(castOther.getAltZusId())))
				&& ((this.getNeuId() == castOther.getNeuId()) || (this
						.getNeuId() != null && castOther.getNeuId() != null && this
						.getNeuId().equals(castOther.getNeuId())))
				&& ((this.getNeuImpId() == castOther.getNeuImpId()) || (this
						.getNeuImpId() != null
						&& castOther.getNeuImpId() != null && this
						.getNeuImpId().equals(castOther.getNeuImpId())))
				&& ((this.getNeuZusId() == castOther.getNeuZusId()) || (this
						.getNeuZusId() != null
						&& castOther.getNeuZusId() != null && this
						.getNeuZusId().equals(castOther.getNeuZusId())))
				&& ((this.getDtyId() == castOther.getDtyId()) || (this
						.getDtyId() != null && castOther.getDtyId() != null && this
						.getDtyId().equals(castOther.getDtyId())))
				&& ((this.getName() == castOther.getName()) || (this.getName() != null
						&& castOther.getName() != null && this.getName()
						.equals(castOther.getName())))
				&& ((this.getLength() == castOther.getLength()) || (this
						.getLength() != null && castOther.getLength() != null && this
						.getLength().equals(castOther.getLength())))
				&& ((this.getPrec() == castOther.getPrec()) || (this.getPrec() != null
						&& castOther.getPrec() != null && this.getPrec()
						.equals(castOther.getPrec())))
				&& ((this.getScale() == castOther.getScale()) || (this
						.getScale() != null && castOther.getScale() != null && this
						.getScale().equals(castOther.getScale())))
				&& ((this.getWaeId() == castOther.getWaeId()) || (this
						.getWaeId() != null && castOther.getWaeId() != null && this
						.getWaeId().equals(castOther.getWaeId())))
				&& ((this.getWaeImpId() == castOther.getWaeImpId()) || (this
						.getWaeImpId() != null
						&& castOther.getWaeImpId() != null && this
						.getWaeImpId().equals(castOther.getWaeImpId())))
				&& ((this.getInserted() == castOther.getInserted()) || (this
						.getInserted() != null
						&& castOther.getInserted() != null && this
						.getInserted().equals(castOther.getInserted())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getAltId() == null ? 0 : this.getAltId().hashCode());
		result = 37 * result
				+ (getAltImpId() == null ? 0 : this.getAltImpId().hashCode());
		result = 37 * result
				+ (getAltZusId() == null ? 0 : this.getAltZusId().hashCode());
		result = 37 * result
				+ (getNeuId() == null ? 0 : this.getNeuId().hashCode());
		result = 37 * result
				+ (getNeuImpId() == null ? 0 : this.getNeuImpId().hashCode());
		result = 37 * result
				+ (getNeuZusId() == null ? 0 : this.getNeuZusId().hashCode());
		result = 37 * result
				+ (getDtyId() == null ? 0 : this.getDtyId().hashCode());
		result = 37 * result
				+ (getName() == null ? 0 : this.getName().hashCode());
		result = 37 * result
				+ (getLength() == null ? 0 : this.getLength().hashCode());
		result = 37 * result
				+ (getPrec() == null ? 0 : this.getPrec().hashCode());
		result = 37 * result
				+ (getScale() == null ? 0 : this.getScale().hashCode());
		result = 37 * result
				+ (getWaeId() == null ? 0 : this.getWaeId().hashCode());
		result = 37 * result
				+ (getWaeImpId() == null ? 0 : this.getWaeImpId().hashCode());
		result = 37 * result
				+ (getInserted() == null ? 0 : this.getInserted().hashCode());
		return result;
	}

}
