package sernet.gs.reveng;

// Generated Jun 5, 2015 1:28:30 PM by Hibernate Tools 3.4.0.CR1

/**
 * StgMMetastatus generated by hbm2java
 */
public class StgMMetastatus implements java.io.Serializable {

	private StgMMetastatusId id;

	public StgMMetastatus() {
	}

	public StgMMetastatus(StgMMetastatusId id) {
		this.id = id;
	}

	public StgMMetastatusId getId() {
		return this.id;
	}

	public void setId(StgMMetastatusId id) {
		this.id = id;
	}

}
