package sernet.gs.reveng;

// Generated Jun 5, 2015 1:28:30 PM by Hibernate Tools 3.4.0.CR1

/**
 * StgMbBaustZielobjSubtyp generated by hbm2java
 */
public class StgMbBaustZielobjSubtyp implements java.io.Serializable {

	private StgMbBaustZielobjSubtypId id;

	public StgMbBaustZielobjSubtyp() {
	}

	public StgMbBaustZielobjSubtyp(StgMbBaustZielobjSubtypId id) {
		this.id = id;
	}

	public StgMbBaustZielobjSubtypId getId() {
		return this.id;
	}

	public void setId(StgMbBaustZielobjSubtypId id) {
		this.id = id;
	}

}
