package sernet.gs.reveng;

// Generated Jun 5, 2015 1:28:30 PM by Hibernate Tools 3.4.0.CR1

/**
 * StgMbBaustMassnGsiegelTxt generated by hbm2java
 */
public class StgMbBaustMassnGsiegelTxt implements java.io.Serializable {

	private StgMbBaustMassnGsiegelTxtId id;

	public StgMbBaustMassnGsiegelTxt() {
	}

	public StgMbBaustMassnGsiegelTxt(StgMbBaustMassnGsiegelTxtId id) {
		this.id = id;
	}

	public StgMbBaustMassnGsiegelTxtId getId() {
		return this.id;
	}

	public void setId(StgMbBaustMassnGsiegelTxtId id) {
		this.id = id;
	}

}
