package sernet.gs.reveng;

// Generated Jun 5, 2015 1:28:30 PM by Hibernate Tools 3.4.0.CR1

/**
 * StgMbMassnnkat generated by hbm2java
 */
public class StgMbMassnnkat implements java.io.Serializable {

	private StgMbMassnnkatId id;

	public StgMbMassnnkat() {
	}

	public StgMbMassnnkat(StgMbMassnnkatId id) {
		this.id = id;
	}

	public StgMbMassnnkatId getId() {
		return this.id;
	}

	public void setId(StgMbMassnnkatId id) {
		this.id = id;
	}

}
