package sernet.gs.reveng;

// Generated Jun 5, 2015 1:28:30 PM by Hibernate Tools 3.4.0.CR1

/**
 * StgMbRolleTxt generated by hbm2java
 */
public class StgMbRolleTxt implements java.io.Serializable {

	private StgMbRolleTxtId id;

	public StgMbRolleTxt() {
	}

	public StgMbRolleTxt(StgMbRolleTxtId id) {
		this.id = id;
	}

	public StgMbRolleTxtId getId() {
		return this.id;
	}

	public void setId(StgMbRolleTxtId id) {
		this.id = id;
	}

}
