package sernet.gs.reveng;

// Generated Jun 5, 2015 1:28:30 PM by Hibernate Tools 3.4.0.CR1

/**
 * StgMbZielobjTyp generated by hbm2java
 */
public class StgMbZielobjTyp implements java.io.Serializable {

	private StgMbZielobjTypId id;

	public StgMbZielobjTyp() {
	}

	public StgMbZielobjTyp(StgMbZielobjTypId id) {
		this.id = id;
	}

	public StgMbZielobjTypId getId() {
		return this.id;
	}

	public void setId(StgMbZielobjTypId id) {
		this.id = id;
	}

}
