package sernet.gs.reveng;

// Generated Jun 5, 2015 1:28:30 PM by Hibernate Tools 3.4.0.CR1

/**
 * StgMbWaehrungen generated by hbm2java
 */
public class StgMbWaehrungen implements java.io.Serializable {

	private StgMbWaehrungenId id;

	public StgMbWaehrungen() {
	}

	public StgMbWaehrungen(StgMbWaehrungenId id) {
		this.id = id;
	}

	public StgMbWaehrungenId getId() {
		return this.id;
	}

	public void setId(StgMbWaehrungenId id) {
		this.id = id;
	}

}
