package sernet.gs.reveng;

// Generated Jun 5, 2015 1:28:30 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * StgModZobjBstMassId generated by hbm2java
 */
public class StgModZobjBstMassId implements java.io.Serializable {

	private Integer id;
	private Integer bauId;
	private Integer bauImpId;
	private Integer masId;
	private Integer masImpId;
	private Integer zobId;
	private Integer zobImpId;
	private Integer orgImpId;
	private Byte ustId;
	private Integer waeId;
	private Integer waeImpId;
	private Integer notizId;
	private String dateiKosten;
	private String dateiProzess;
	private Date umsDatVon;
	private Date umsDatBis;
	private String umsBeschr;
	private BigDecimal kostPersFix;
	private BigDecimal kostPersVar;
	private Integer kostPersZeiId;
	private Integer kostPersZeiImpId;
	private BigDecimal kostSachFix;
	private BigDecimal kostSachVar;
	private Integer kostSachZeiId;
	private Integer kostSachZeiImpId;
	private String revBeschr;
	private Date revDat;
	private Integer revZobIdMit;
	private Date revDatNext;
	private Integer revZobIdMitNext;
	private Integer stgNeu;
	private Integer usn;
	private String guid;
	private String guidOrg;
	private Date timestamp;
	private Date loeschDatum;
	private Byte impNeu;
	private String erfasstDurch;
	private String geloeschtDurch;
	private Date cmTimestamp;
	private String cmUsername;
	private Short cmVerId2;
	private Byte cmStaId;
	private String changedBy;
	private Date changedOn;
	private Byte zykId;

	public StgModZobjBstMassId() {
	}

	public StgModZobjBstMassId(Integer id, Integer bauId, Integer bauImpId,
			Integer masId, Integer masImpId, Integer zobId, Integer zobImpId,
			Integer orgImpId, Byte ustId, Integer waeId, Integer waeImpId,
			Integer notizId, String dateiKosten, String dateiProzess,
			Date umsDatVon, Date umsDatBis, String umsBeschr,
			BigDecimal kostPersFix, BigDecimal kostPersVar,
			Integer kostPersZeiId, Integer kostPersZeiImpId,
			BigDecimal kostSachFix, BigDecimal kostSachVar,
			Integer kostSachZeiId, Integer kostSachZeiImpId, String revBeschr,
			Date revDat, Integer revZobIdMit, Date revDatNext,
			Integer revZobIdMitNext, Integer stgNeu, Integer usn, String guid,
			String guidOrg, Date timestamp, Date loeschDatum, Byte impNeu,
			String erfasstDurch, String geloeschtDurch, Date cmTimestamp,
			String cmUsername, Short cmVerId2, Byte cmStaId, String changedBy,
			Date changedOn, Byte zykId) {
		this.id = id;
		this.bauId = bauId;
		this.bauImpId = bauImpId;
		this.masId = masId;
		this.masImpId = masImpId;
		this.zobId = zobId;
		this.zobImpId = zobImpId;
		this.orgImpId = orgImpId;
		this.ustId = ustId;
		this.waeId = waeId;
		this.waeImpId = waeImpId;
		this.notizId = notizId;
		this.dateiKosten = dateiKosten;
		this.dateiProzess = dateiProzess;
		this.umsDatVon = umsDatVon;
		this.umsDatBis = umsDatBis;
		this.umsBeschr = umsBeschr;
		this.kostPersFix = kostPersFix;
		this.kostPersVar = kostPersVar;
		this.kostPersZeiId = kostPersZeiId;
		this.kostPersZeiImpId = kostPersZeiImpId;
		this.kostSachFix = kostSachFix;
		this.kostSachVar = kostSachVar;
		this.kostSachZeiId = kostSachZeiId;
		this.kostSachZeiImpId = kostSachZeiImpId;
		this.revBeschr = revBeschr;
		this.revDat = revDat;
		this.revZobIdMit = revZobIdMit;
		this.revDatNext = revDatNext;
		this.revZobIdMitNext = revZobIdMitNext;
		this.stgNeu = stgNeu;
		this.usn = usn;
		this.guid = guid;
		this.guidOrg = guidOrg;
		this.timestamp = timestamp;
		this.loeschDatum = loeschDatum;
		this.impNeu = impNeu;
		this.erfasstDurch = erfasstDurch;
		this.geloeschtDurch = geloeschtDurch;
		this.cmTimestamp = cmTimestamp;
		this.cmUsername = cmUsername;
		this.cmVerId2 = cmVerId2;
		this.cmStaId = cmStaId;
		this.changedBy = changedBy;
		this.changedOn = changedOn;
		this.zykId = zykId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getBauId() {
		return this.bauId;
	}

	public void setBauId(Integer bauId) {
		this.bauId = bauId;
	}

	public Integer getBauImpId() {
		return this.bauImpId;
	}

	public void setBauImpId(Integer bauImpId) {
		this.bauImpId = bauImpId;
	}

	public Integer getMasId() {
		return this.masId;
	}

	public void setMasId(Integer masId) {
		this.masId = masId;
	}

	public Integer getMasImpId() {
		return this.masImpId;
	}

	public void setMasImpId(Integer masImpId) {
		this.masImpId = masImpId;
	}

	public Integer getZobId() {
		return this.zobId;
	}

	public void setZobId(Integer zobId) {
		this.zobId = zobId;
	}

	public Integer getZobImpId() {
		return this.zobImpId;
	}

	public void setZobImpId(Integer zobImpId) {
		this.zobImpId = zobImpId;
	}

	public Integer getOrgImpId() {
		return this.orgImpId;
	}

	public void setOrgImpId(Integer orgImpId) {
		this.orgImpId = orgImpId;
	}

	public Byte getUstId() {
		return this.ustId;
	}

	public void setUstId(Byte ustId) {
		this.ustId = ustId;
	}

	public Integer getWaeId() {
		return this.waeId;
	}

	public void setWaeId(Integer waeId) {
		this.waeId = waeId;
	}

	public Integer getWaeImpId() {
		return this.waeImpId;
	}

	public void setWaeImpId(Integer waeImpId) {
		this.waeImpId = waeImpId;
	}

	public Integer getNotizId() {
		return this.notizId;
	}

	public void setNotizId(Integer notizId) {
		this.notizId = notizId;
	}

	public String getDateiKosten() {
		return this.dateiKosten;
	}

	public void setDateiKosten(String dateiKosten) {
		this.dateiKosten = dateiKosten;
	}

	public String getDateiProzess() {
		return this.dateiProzess;
	}

	public void setDateiProzess(String dateiProzess) {
		this.dateiProzess = dateiProzess;
	}

	public Date getUmsDatVon() {
		return this.umsDatVon;
	}

	public void setUmsDatVon(Date umsDatVon) {
		this.umsDatVon = umsDatVon;
	}

	public Date getUmsDatBis() {
		return this.umsDatBis;
	}

	public void setUmsDatBis(Date umsDatBis) {
		this.umsDatBis = umsDatBis;
	}

	public String getUmsBeschr() {
		return this.umsBeschr;
	}

	public void setUmsBeschr(String umsBeschr) {
		this.umsBeschr = umsBeschr;
	}

	public BigDecimal getKostPersFix() {
		return this.kostPersFix;
	}

	public void setKostPersFix(BigDecimal kostPersFix) {
		this.kostPersFix = kostPersFix;
	}

	public BigDecimal getKostPersVar() {
		return this.kostPersVar;
	}

	public void setKostPersVar(BigDecimal kostPersVar) {
		this.kostPersVar = kostPersVar;
	}

	public Integer getKostPersZeiId() {
		return this.kostPersZeiId;
	}

	public void setKostPersZeiId(Integer kostPersZeiId) {
		this.kostPersZeiId = kostPersZeiId;
	}

	public Integer getKostPersZeiImpId() {
		return this.kostPersZeiImpId;
	}

	public void setKostPersZeiImpId(Integer kostPersZeiImpId) {
		this.kostPersZeiImpId = kostPersZeiImpId;
	}

	public BigDecimal getKostSachFix() {
		return this.kostSachFix;
	}

	public void setKostSachFix(BigDecimal kostSachFix) {
		this.kostSachFix = kostSachFix;
	}

	public BigDecimal getKostSachVar() {
		return this.kostSachVar;
	}

	public void setKostSachVar(BigDecimal kostSachVar) {
		this.kostSachVar = kostSachVar;
	}

	public Integer getKostSachZeiId() {
		return this.kostSachZeiId;
	}

	public void setKostSachZeiId(Integer kostSachZeiId) {
		this.kostSachZeiId = kostSachZeiId;
	}

	public Integer getKostSachZeiImpId() {
		return this.kostSachZeiImpId;
	}

	public void setKostSachZeiImpId(Integer kostSachZeiImpId) {
		this.kostSachZeiImpId = kostSachZeiImpId;
	}

	public String getRevBeschr() {
		return this.revBeschr;
	}

	public void setRevBeschr(String revBeschr) {
		this.revBeschr = revBeschr;
	}

	public Date getRevDat() {
		return this.revDat;
	}

	public void setRevDat(Date revDat) {
		this.revDat = revDat;
	}

	public Integer getRevZobIdMit() {
		return this.revZobIdMit;
	}

	public void setRevZobIdMit(Integer revZobIdMit) {
		this.revZobIdMit = revZobIdMit;
	}

	public Date getRevDatNext() {
		return this.revDatNext;
	}

	public void setRevDatNext(Date revDatNext) {
		this.revDatNext = revDatNext;
	}

	public Integer getRevZobIdMitNext() {
		return this.revZobIdMitNext;
	}

	public void setRevZobIdMitNext(Integer revZobIdMitNext) {
		this.revZobIdMitNext = revZobIdMitNext;
	}

	public Integer getStgNeu() {
		return this.stgNeu;
	}

	public void setStgNeu(Integer stgNeu) {
		this.stgNeu = stgNeu;
	}

	public Integer getUsn() {
		return this.usn;
	}

	public void setUsn(Integer usn) {
		this.usn = usn;
	}

	public String getGuid() {
		return this.guid;
	}

	public void setGuid(String guid) {
		this.guid = guid;
	}

	public String getGuidOrg() {
		return this.guidOrg;
	}

	public void setGuidOrg(String guidOrg) {
		this.guidOrg = guidOrg;
	}

	public Date getTimestamp() {
		return this.timestamp;
	}

	public void setTimestamp(Date timestamp) {
		this.timestamp = timestamp;
	}

	public Date getLoeschDatum() {
		return this.loeschDatum;
	}

	public void setLoeschDatum(Date loeschDatum) {
		this.loeschDatum = loeschDatum;
	}

	public Byte getImpNeu() {
		return this.impNeu;
	}

	public void setImpNeu(Byte impNeu) {
		this.impNeu = impNeu;
	}

	public String getErfasstDurch() {
		return this.erfasstDurch;
	}

	public void setErfasstDurch(String erfasstDurch) {
		this.erfasstDurch = erfasstDurch;
	}

	public String getGeloeschtDurch() {
		return this.geloeschtDurch;
	}

	public void setGeloeschtDurch(String geloeschtDurch) {
		this.geloeschtDurch = geloeschtDurch;
	}

	public Date getCmTimestamp() {
		return this.cmTimestamp;
	}

	public void setCmTimestamp(Date cmTimestamp) {
		this.cmTimestamp = cmTimestamp;
	}

	public String getCmUsername() {
		return this.cmUsername;
	}

	public void setCmUsername(String cmUsername) {
		this.cmUsername = cmUsername;
	}

	public Short getCmVerId2() {
		return this.cmVerId2;
	}

	public void setCmVerId2(Short cmVerId2) {
		this.cmVerId2 = cmVerId2;
	}

	public Byte getCmStaId() {
		return this.cmStaId;
	}

	public void setCmStaId(Byte cmStaId) {
		this.cmStaId = cmStaId;
	}

	public String getChangedBy() {
		return this.changedBy;
	}

	public void setChangedBy(String changedBy) {
		this.changedBy = changedBy;
	}

	public Date getChangedOn() {
		return this.changedOn;
	}

	public void setChangedOn(Date changedOn) {
		this.changedOn = changedOn;
	}

	public Byte getZykId() {
		return this.zykId;
	}

	public void setZykId(Byte zykId) {
		this.zykId = zykId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof StgModZobjBstMassId))
			return false;
		StgModZobjBstMassId castOther = (StgModZobjBstMassId) other;

		return ((this.getId() == castOther.getId()) || (this.getId() != null
				&& castOther.getId() != null && this.getId().equals(
				castOther.getId())))
				&& ((this.getBauId() == castOther.getBauId()) || (this
						.getBauId() != null && castOther.getBauId() != null && this
						.getBauId().equals(castOther.getBauId())))
				&& ((this.getBauImpId() == castOther.getBauImpId()) || (this
						.getBauImpId() != null
						&& castOther.getBauImpId() != null && this
						.getBauImpId().equals(castOther.getBauImpId())))
				&& ((this.getMasId() == castOther.getMasId()) || (this
						.getMasId() != null && castOther.getMasId() != null && this
						.getMasId().equals(castOther.getMasId())))
				&& ((this.getMasImpId() == castOther.getMasImpId()) || (this
						.getMasImpId() != null
						&& castOther.getMasImpId() != null && this
						.getMasImpId().equals(castOther.getMasImpId())))
				&& ((this.getZobId() == castOther.getZobId()) || (this
						.getZobId() != null && castOther.getZobId() != null && this
						.getZobId().equals(castOther.getZobId())))
				&& ((this.getZobImpId() == castOther.getZobImpId()) || (this
						.getZobImpId() != null
						&& castOther.getZobImpId() != null && this
						.getZobImpId().equals(castOther.getZobImpId())))
				&& ((this.getOrgImpId() == castOther.getOrgImpId()) || (this
						.getOrgImpId() != null
						&& castOther.getOrgImpId() != null && this
						.getOrgImpId().equals(castOther.getOrgImpId())))
				&& ((this.getUstId() == castOther.getUstId()) || (this
						.getUstId() != null && castOther.getUstId() != null && this
						.getUstId().equals(castOther.getUstId())))
				&& ((this.getWaeId() == castOther.getWaeId()) || (this
						.getWaeId() != null && castOther.getWaeId() != null && this
						.getWaeId().equals(castOther.getWaeId())))
				&& ((this.getWaeImpId() == castOther.getWaeImpId()) || (this
						.getWaeImpId() != null
						&& castOther.getWaeImpId() != null && this
						.getWaeImpId().equals(castOther.getWaeImpId())))
				&& ((this.getNotizId() == castOther.getNotizId()) || (this
						.getNotizId() != null && castOther.getNotizId() != null && this
						.getNotizId().equals(castOther.getNotizId())))
				&& ((this.getDateiKosten() == castOther.getDateiKosten()) || (this
						.getDateiKosten() != null
						&& castOther.getDateiKosten() != null && this
						.getDateiKosten().equals(castOther.getDateiKosten())))
				&& ((this.getDateiProzess() == castOther.getDateiProzess()) || (this
						.getDateiProzess() != null
						&& castOther.getDateiProzess() != null && this
						.getDateiProzess().equals(castOther.getDateiProzess())))
				&& ((this.getUmsDatVon() == castOther.getUmsDatVon()) || (this
						.getUmsDatVon() != null
						&& castOther.getUmsDatVon() != null && this
						.getUmsDatVon().equals(castOther.getUmsDatVon())))
				&& ((this.getUmsDatBis() == castOther.getUmsDatBis()) || (this
						.getUmsDatBis() != null
						&& castOther.getUmsDatBis() != null && this
						.getUmsDatBis().equals(castOther.getUmsDatBis())))
				&& ((this.getUmsBeschr() == castOther.getUmsBeschr()) || (this
						.getUmsBeschr() != null
						&& castOther.getUmsBeschr() != null && this
						.getUmsBeschr().equals(castOther.getUmsBeschr())))
				&& ((this.getKostPersFix() == castOther.getKostPersFix()) || (this
						.getKostPersFix() != null
						&& castOther.getKostPersFix() != null && this
						.getKostPersFix().equals(castOther.getKostPersFix())))
				&& ((this.getKostPersVar() == castOther.getKostPersVar()) || (this
						.getKostPersVar() != null
						&& castOther.getKostPersVar() != null && this
						.getKostPersVar().equals(castOther.getKostPersVar())))
				&& ((this.getKostPersZeiId() == castOther.getKostPersZeiId()) || (this
						.getKostPersZeiId() != null
						&& castOther.getKostPersZeiId() != null && this
						.getKostPersZeiId()
						.equals(castOther.getKostPersZeiId())))
				&& ((this.getKostPersZeiImpId() == castOther
						.getKostPersZeiImpId()) || (this.getKostPersZeiImpId() != null
						&& castOther.getKostPersZeiImpId() != null && this
						.getKostPersZeiImpId().equals(
								castOther.getKostPersZeiImpId())))
				&& ((this.getKostSachFix() == castOther.getKostSachFix()) || (this
						.getKostSachFix() != null
						&& castOther.getKostSachFix() != null && this
						.getKostSachFix().equals(castOther.getKostSachFix())))
				&& ((this.getKostSachVar() == castOther.getKostSachVar()) || (this
						.getKostSachVar() != null
						&& castOther.getKostSachVar() != null && this
						.getKostSachVar().equals(castOther.getKostSachVar())))
				&& ((this.getKostSachZeiId() == castOther.getKostSachZeiId()) || (this
						.getKostSachZeiId() != null
						&& castOther.getKostSachZeiId() != null && this
						.getKostSachZeiId()
						.equals(castOther.getKostSachZeiId())))
				&& ((this.getKostSachZeiImpId() == castOther
						.getKostSachZeiImpId()) || (this.getKostSachZeiImpId() != null
						&& castOther.getKostSachZeiImpId() != null && this
						.getKostSachZeiImpId().equals(
								castOther.getKostSachZeiImpId())))
				&& ((this.getRevBeschr() == castOther.getRevBeschr()) || (this
						.getRevBeschr() != null
						&& castOther.getRevBeschr() != null && this
						.getRevBeschr().equals(castOther.getRevBeschr())))
				&& ((this.getRevDat() == castOther.getRevDat()) || (this
						.getRevDat() != null && castOther.getRevDat() != null && this
						.getRevDat().equals(castOther.getRevDat())))
				&& ((this.getRevZobIdMit() == castOther.getRevZobIdMit()) || (this
						.getRevZobIdMit() != null
						&& castOther.getRevZobIdMit() != null && this
						.getRevZobIdMit().equals(castOther.getRevZobIdMit())))
				&& ((this.getRevDatNext() == castOther.getRevDatNext()) || (this
						.getRevDatNext() != null
						&& castOther.getRevDatNext() != null && this
						.getRevDatNext().equals(castOther.getRevDatNext())))
				&& ((this.getRevZobIdMitNext() == castOther
						.getRevZobIdMitNext()) || (this.getRevZobIdMitNext() != null
						&& castOther.getRevZobIdMitNext() != null && this
						.getRevZobIdMitNext().equals(
								castOther.getRevZobIdMitNext())))
				&& ((this.getStgNeu() == castOther.getStgNeu()) || (this
						.getStgNeu() != null && castOther.getStgNeu() != null && this
						.getStgNeu().equals(castOther.getStgNeu())))
				&& ((this.getUsn() == castOther.getUsn()) || (this.getUsn() != null
						&& castOther.getUsn() != null && this.getUsn().equals(
						castOther.getUsn())))
				&& ((this.getGuid() == castOther.getGuid()) || (this.getGuid() != null
						&& castOther.getGuid() != null && this.getGuid()
						.equals(castOther.getGuid())))
				&& ((this.getGuidOrg() == castOther.getGuidOrg()) || (this
						.getGuidOrg() != null && castOther.getGuidOrg() != null && this
						.getGuidOrg().equals(castOther.getGuidOrg())))
				&& ((this.getTimestamp() == castOther.getTimestamp()) || (this
						.getTimestamp() != null
						&& castOther.getTimestamp() != null && this
						.getTimestamp().equals(castOther.getTimestamp())))
				&& ((this.getLoeschDatum() == castOther.getLoeschDatum()) || (this
						.getLoeschDatum() != null
						&& castOther.getLoeschDatum() != null && this
						.getLoeschDatum().equals(castOther.getLoeschDatum())))
				&& ((this.getImpNeu() == castOther.getImpNeu()) || (this
						.getImpNeu() != null && castOther.getImpNeu() != null && this
						.getImpNeu().equals(castOther.getImpNeu())))
				&& ((this.getErfasstDurch() == castOther.getErfasstDurch()) || (this
						.getErfasstDurch() != null
						&& castOther.getErfasstDurch() != null && this
						.getErfasstDurch().equals(castOther.getErfasstDurch())))
				&& ((this.getGeloeschtDurch() == castOther.getGeloeschtDurch()) || (this
						.getGeloeschtDurch() != null
						&& castOther.getGeloeschtDurch() != null && this
						.getGeloeschtDurch().equals(
								castOther.getGeloeschtDurch())))
				&& ((this.getCmTimestamp() == castOther.getCmTimestamp()) || (this
						.getCmTimestamp() != null
						&& castOther.getCmTimestamp() != null && this
						.getCmTimestamp().equals(castOther.getCmTimestamp())))
				&& ((this.getCmUsername() == castOther.getCmUsername()) || (this
						.getCmUsername() != null
						&& castOther.getCmUsername() != null && this
						.getCmUsername().equals(castOther.getCmUsername())))
				&& ((this.getCmVerId2() == castOther.getCmVerId2()) || (this
						.getCmVerId2() != null
						&& castOther.getCmVerId2() != null && this
						.getCmVerId2().equals(castOther.getCmVerId2())))
				&& ((this.getCmStaId() == castOther.getCmStaId()) || (this
						.getCmStaId() != null && castOther.getCmStaId() != null && this
						.getCmStaId().equals(castOther.getCmStaId())))
				&& ((this.getChangedBy() == castOther.getChangedBy()) || (this
						.getChangedBy() != null
						&& castOther.getChangedBy() != null && this
						.getChangedBy().equals(castOther.getChangedBy())))
				&& ((this.getChangedOn() == castOther.getChangedOn()) || (this
						.getChangedOn() != null
						&& castOther.getChangedOn() != null && this
						.getChangedOn().equals(castOther.getChangedOn())))
				&& ((this.getZykId() == castOther.getZykId()) || (this
						.getZykId() != null && castOther.getZykId() != null && this
						.getZykId().equals(castOther.getZykId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37 * result
				+ (getBauId() == null ? 0 : this.getBauId().hashCode());
		result = 37 * result
				+ (getBauImpId() == null ? 0 : this.getBauImpId().hashCode());
		result = 37 * result
				+ (getMasId() == null ? 0 : this.getMasId().hashCode());
		result = 37 * result
				+ (getMasImpId() == null ? 0 : this.getMasImpId().hashCode());
		result = 37 * result
				+ (getZobId() == null ? 0 : this.getZobId().hashCode());
		result = 37 * result
				+ (getZobImpId() == null ? 0 : this.getZobImpId().hashCode());
		result = 37 * result
				+ (getOrgImpId() == null ? 0 : this.getOrgImpId().hashCode());
		result = 37 * result
				+ (getUstId() == null ? 0 : this.getUstId().hashCode());
		result = 37 * result
				+ (getWaeId() == null ? 0 : this.getWaeId().hashCode());
		result = 37 * result
				+ (getWaeImpId() == null ? 0 : this.getWaeImpId().hashCode());
		result = 37 * result
				+ (getNotizId() == null ? 0 : this.getNotizId().hashCode());
		result = 37
				* result
				+ (getDateiKosten() == null ? 0 : this.getDateiKosten()
						.hashCode());
		result = 37
				* result
				+ (getDateiProzess() == null ? 0 : this.getDateiProzess()
						.hashCode());
		result = 37 * result
				+ (getUmsDatVon() == null ? 0 : this.getUmsDatVon().hashCode());
		result = 37 * result
				+ (getUmsDatBis() == null ? 0 : this.getUmsDatBis().hashCode());
		result = 37 * result
				+ (getUmsBeschr() == null ? 0 : this.getUmsBeschr().hashCode());
		result = 37
				* result
				+ (getKostPersFix() == null ? 0 : this.getKostPersFix()
						.hashCode());
		result = 37
				* result
				+ (getKostPersVar() == null ? 0 : this.getKostPersVar()
						.hashCode());
		result = 37
				* result
				+ (getKostPersZeiId() == null ? 0 : this.getKostPersZeiId()
						.hashCode());
		result = 37
				* result
				+ (getKostPersZeiImpId() == null ? 0 : this
						.getKostPersZeiImpId().hashCode());
		result = 37
				* result
				+ (getKostSachFix() == null ? 0 : this.getKostSachFix()
						.hashCode());
		result = 37
				* result
				+ (getKostSachVar() == null ? 0 : this.getKostSachVar()
						.hashCode());
		result = 37
				* result
				+ (getKostSachZeiId() == null ? 0 : this.getKostSachZeiId()
						.hashCode());
		result = 37
				* result
				+ (getKostSachZeiImpId() == null ? 0 : this
						.getKostSachZeiImpId().hashCode());
		result = 37 * result
				+ (getRevBeschr() == null ? 0 : this.getRevBeschr().hashCode());
		result = 37 * result
				+ (getRevDat() == null ? 0 : this.getRevDat().hashCode());
		result = 37
				* result
				+ (getRevZobIdMit() == null ? 0 : this.getRevZobIdMit()
						.hashCode());
		result = 37
				* result
				+ (getRevDatNext() == null ? 0 : this.getRevDatNext()
						.hashCode());
		result = 37
				* result
				+ (getRevZobIdMitNext() == null ? 0 : this.getRevZobIdMitNext()
						.hashCode());
		result = 37 * result
				+ (getStgNeu() == null ? 0 : this.getStgNeu().hashCode());
		result = 37 * result
				+ (getUsn() == null ? 0 : this.getUsn().hashCode());
		result = 37 * result
				+ (getGuid() == null ? 0 : this.getGuid().hashCode());
		result = 37 * result
				+ (getGuidOrg() == null ? 0 : this.getGuidOrg().hashCode());
		result = 37 * result
				+ (getTimestamp() == null ? 0 : this.getTimestamp().hashCode());
		result = 37
				* result
				+ (getLoeschDatum() == null ? 0 : this.getLoeschDatum()
						.hashCode());
		result = 37 * result
				+ (getImpNeu() == null ? 0 : this.getImpNeu().hashCode());
		result = 37
				* result
				+ (getErfasstDurch() == null ? 0 : this.getErfasstDurch()
						.hashCode());
		result = 37
				* result
				+ (getGeloeschtDurch() == null ? 0 : this.getGeloeschtDurch()
						.hashCode());
		result = 37
				* result
				+ (getCmTimestamp() == null ? 0 : this.getCmTimestamp()
						.hashCode());
		result = 37
				* result
				+ (getCmUsername() == null ? 0 : this.getCmUsername()
						.hashCode());
		result = 37 * result
				+ (getCmVerId2() == null ? 0 : this.getCmVerId2().hashCode());
		result = 37 * result
				+ (getCmStaId() == null ? 0 : this.getCmStaId().hashCode());
		result = 37 * result
				+ (getChangedBy() == null ? 0 : this.getChangedBy().hashCode());
		result = 37 * result
				+ (getChangedOn() == null ? 0 : this.getChangedOn().hashCode());
		result = 37 * result
				+ (getZykId() == null ? 0 : this.getZykId().hashCode());
		return result;
	}

}
