package sernet.gs.reveng;

// Generated Jun 5, 2015 1:28:30 PM by Hibernate Tools 3.4.0.CR1

/**
 * StgMbRolleMassn generated by hbm2java
 */
public class StgMbRolleMassn implements java.io.Serializable {

	private StgMbRolleMassnId id;

	public StgMbRolleMassn() {
	}

	public StgMbRolleMassn(StgMbRolleMassnId id) {
		this.id = id;
	}

	public StgMbRolleMassnId getId() {
		return this.id;
	}

	public void setId(StgMbRolleMassnId id) {
		this.id = id;
	}

}
