package sernet.gs.reveng;

// Generated Jun 5, 2015 1:28:30 PM by Hibernate Tools 3.4.0.CR1

/**
 * StgMapZosZus generated by hbm2java
 */
public class StgMapZosZus implements java.io.Serializable {

	private StgMapZosZusId id;

	public StgMapZosZus() {
	}

	public StgMapZosZus(StgMapZosZusId id) {
		this.id = id;
	}

	public StgMapZosZusId getId() {
		return this.id;
	}

	public void setId(StgMapZosZusId id) {
		this.id = id;
	}

}
