package sernet.gs.reveng;

// Generated Jun 5, 2015 1:28:30 PM by Hibernate Tools 3.4.0.CR1

/**
 * StgMbDringlichkeitTxt generated by hbm2java
 */
public class StgMbDringlichkeitTxt implements java.io.Serializable {

	private StgMbDringlichkeitTxtId id;

	public StgMbDringlichkeitTxt() {
	}

	public StgMbDringlichkeitTxt(StgMbDringlichkeitTxtId id) {
		this.id = id;
	}

	public StgMbDringlichkeitTxtId getId() {
		return this.id;
	}

	public void setId(StgMbDringlichkeitTxtId id) {
		this.id = id;
	}

}
