package sernet.gs.reveng;

// Generated Jun 5, 2015 1:28:30 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * StgMbRolleMassnId generated by hbm2java
 */
public class StgMbRolleMassnId implements java.io.Serializable {

	private Integer rolId;
	private Integer rolImpId;
	private Integer masId;
	private Integer masImpId;
	private String masTyp;
	private Integer phaId;
	private Integer phaImpId;
	private Byte metaNeu;
	private Integer metaVers;
	private Integer obsoletVers;
	private String guid;
	private Date timestamp;
	private Date loeschDatum;
	private String erfasstDurch;
	private String geloeschtDurch;
	private String guidOrg;
	private Integer usn;

	public StgMbRolleMassnId() {
	}

	public StgMbRolleMassnId(Integer rolId, Integer rolImpId, Integer masId,
			Integer masImpId, String masTyp, Integer phaId, Integer phaImpId,
			Byte metaNeu, Integer metaVers, Integer obsoletVers, String guid,
			Date timestamp, Date loeschDatum, String erfasstDurch,
			String geloeschtDurch, String guidOrg, Integer usn) {
		this.rolId = rolId;
		this.rolImpId = rolImpId;
		this.masId = masId;
		this.masImpId = masImpId;
		this.masTyp = masTyp;
		this.phaId = phaId;
		this.phaImpId = phaImpId;
		this.metaNeu = metaNeu;
		this.metaVers = metaVers;
		this.obsoletVers = obsoletVers;
		this.guid = guid;
		this.timestamp = timestamp;
		this.loeschDatum = loeschDatum;
		this.erfasstDurch = erfasstDurch;
		this.geloeschtDurch = geloeschtDurch;
		this.guidOrg = guidOrg;
		this.usn = usn;
	}

	public Integer getRolId() {
		return this.rolId;
	}

	public void setRolId(Integer rolId) {
		this.rolId = rolId;
	}

	public Integer getRolImpId() {
		return this.rolImpId;
	}

	public void setRolImpId(Integer rolImpId) {
		this.rolImpId = rolImpId;
	}

	public Integer getMasId() {
		return this.masId;
	}

	public void setMasId(Integer masId) {
		this.masId = masId;
	}

	public Integer getMasImpId() {
		return this.masImpId;
	}

	public void setMasImpId(Integer masImpId) {
		this.masImpId = masImpId;
	}

	public String getMasTyp() {
		return this.masTyp;
	}

	public void setMasTyp(String masTyp) {
		this.masTyp = masTyp;
	}

	public Integer getPhaId() {
		return this.phaId;
	}

	public void setPhaId(Integer phaId) {
		this.phaId = phaId;
	}

	public Integer getPhaImpId() {
		return this.phaImpId;
	}

	public void setPhaImpId(Integer phaImpId) {
		this.phaImpId = phaImpId;
	}

	public Byte getMetaNeu() {
		return this.metaNeu;
	}

	public void setMetaNeu(Byte metaNeu) {
		this.metaNeu = metaNeu;
	}

	public Integer getMetaVers() {
		return this.metaVers;
	}

	public void setMetaVers(Integer metaVers) {
		this.metaVers = metaVers;
	}

	public Integer getObsoletVers() {
		return this.obsoletVers;
	}

	public void setObsoletVers(Integer obsoletVers) {
		this.obsoletVers = obsoletVers;
	}

	public String getGuid() {
		return this.guid;
	}

	public void setGuid(String guid) {
		this.guid = guid;
	}

	public Date getTimestamp() {
		return this.timestamp;
	}

	public void setTimestamp(Date timestamp) {
		this.timestamp = timestamp;
	}

	public Date getLoeschDatum() {
		return this.loeschDatum;
	}

	public void setLoeschDatum(Date loeschDatum) {
		this.loeschDatum = loeschDatum;
	}

	public String getErfasstDurch() {
		return this.erfasstDurch;
	}

	public void setErfasstDurch(String erfasstDurch) {
		this.erfasstDurch = erfasstDurch;
	}

	public String getGeloeschtDurch() {
		return this.geloeschtDurch;
	}

	public void setGeloeschtDurch(String geloeschtDurch) {
		this.geloeschtDurch = geloeschtDurch;
	}

	public String getGuidOrg() {
		return this.guidOrg;
	}

	public void setGuidOrg(String guidOrg) {
		this.guidOrg = guidOrg;
	}

	public Integer getUsn() {
		return this.usn;
	}

	public void setUsn(Integer usn) {
		this.usn = usn;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof StgMbRolleMassnId))
			return false;
		StgMbRolleMassnId castOther = (StgMbRolleMassnId) other;

		return ((this.getRolId() == castOther.getRolId()) || (this.getRolId() != null
				&& castOther.getRolId() != null && this.getRolId().equals(
				castOther.getRolId())))
				&& ((this.getRolImpId() == castOther.getRolImpId()) || (this
						.getRolImpId() != null
						&& castOther.getRolImpId() != null && this
						.getRolImpId().equals(castOther.getRolImpId())))
				&& ((this.getMasId() == castOther.getMasId()) || (this
						.getMasId() != null && castOther.getMasId() != null && this
						.getMasId().equals(castOther.getMasId())))
				&& ((this.getMasImpId() == castOther.getMasImpId()) || (this
						.getMasImpId() != null
						&& castOther.getMasImpId() != null && this
						.getMasImpId().equals(castOther.getMasImpId())))
				&& ((this.getMasTyp() == castOther.getMasTyp()) || (this
						.getMasTyp() != null && castOther.getMasTyp() != null && this
						.getMasTyp().equals(castOther.getMasTyp())))
				&& ((this.getPhaId() == castOther.getPhaId()) || (this
						.getPhaId() != null && castOther.getPhaId() != null && this
						.getPhaId().equals(castOther.getPhaId())))
				&& ((this.getPhaImpId() == castOther.getPhaImpId()) || (this
						.getPhaImpId() != null
						&& castOther.getPhaImpId() != null && this
						.getPhaImpId().equals(castOther.getPhaImpId())))
				&& ((this.getMetaNeu() == castOther.getMetaNeu()) || (this
						.getMetaNeu() != null && castOther.getMetaNeu() != null && this
						.getMetaNeu().equals(castOther.getMetaNeu())))
				&& ((this.getMetaVers() == castOther.getMetaVers()) || (this
						.getMetaVers() != null
						&& castOther.getMetaVers() != null && this
						.getMetaVers().equals(castOther.getMetaVers())))
				&& ((this.getObsoletVers() == castOther.getObsoletVers()) || (this
						.getObsoletVers() != null
						&& castOther.getObsoletVers() != null && this
						.getObsoletVers().equals(castOther.getObsoletVers())))
				&& ((this.getGuid() == castOther.getGuid()) || (this.getGuid() != null
						&& castOther.getGuid() != null && this.getGuid()
						.equals(castOther.getGuid())))
				&& ((this.getTimestamp() == castOther.getTimestamp()) || (this
						.getTimestamp() != null
						&& castOther.getTimestamp() != null && this
						.getTimestamp().equals(castOther.getTimestamp())))
				&& ((this.getLoeschDatum() == castOther.getLoeschDatum()) || (this
						.getLoeschDatum() != null
						&& castOther.getLoeschDatum() != null && this
						.getLoeschDatum().equals(castOther.getLoeschDatum())))
				&& ((this.getErfasstDurch() == castOther.getErfasstDurch()) || (this
						.getErfasstDurch() != null
						&& castOther.getErfasstDurch() != null && this
						.getErfasstDurch().equals(castOther.getErfasstDurch())))
				&& ((this.getGeloeschtDurch() == castOther.getGeloeschtDurch()) || (this
						.getGeloeschtDurch() != null
						&& castOther.getGeloeschtDurch() != null && this
						.getGeloeschtDurch().equals(
								castOther.getGeloeschtDurch())))
				&& ((this.getGuidOrg() == castOther.getGuidOrg()) || (this
						.getGuidOrg() != null && castOther.getGuidOrg() != null && this
						.getGuidOrg().equals(castOther.getGuidOrg())))
				&& ((this.getUsn() == castOther.getUsn()) || (this.getUsn() != null
						&& castOther.getUsn() != null && this.getUsn().equals(
						castOther.getUsn())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getRolId() == null ? 0 : this.getRolId().hashCode());
		result = 37 * result
				+ (getRolImpId() == null ? 0 : this.getRolImpId().hashCode());
		result = 37 * result
				+ (getMasId() == null ? 0 : this.getMasId().hashCode());
		result = 37 * result
				+ (getMasImpId() == null ? 0 : this.getMasImpId().hashCode());
		result = 37 * result
				+ (getMasTyp() == null ? 0 : this.getMasTyp().hashCode());
		result = 37 * result
				+ (getPhaId() == null ? 0 : this.getPhaId().hashCode());
		result = 37 * result
				+ (getPhaImpId() == null ? 0 : this.getPhaImpId().hashCode());
		result = 37 * result
				+ (getMetaNeu() == null ? 0 : this.getMetaNeu().hashCode());
		result = 37 * result
				+ (getMetaVers() == null ? 0 : this.getMetaVers().hashCode());
		result = 37
				* result
				+ (getObsoletVers() == null ? 0 : this.getObsoletVers()
						.hashCode());
		result = 37 * result
				+ (getGuid() == null ? 0 : this.getGuid().hashCode());
		result = 37 * result
				+ (getTimestamp() == null ? 0 : this.getTimestamp().hashCode());
		result = 37
				* result
				+ (getLoeschDatum() == null ? 0 : this.getLoeschDatum()
						.hashCode());
		result = 37
				* result
				+ (getErfasstDurch() == null ? 0 : this.getErfasstDurch()
						.hashCode());
		result = 37
				* result
				+ (getGeloeschtDurch() == null ? 0 : this.getGeloeschtDurch()
						.hashCode());
		result = 37 * result
				+ (getGuidOrg() == null ? 0 : this.getGuidOrg().hashCode());
		result = 37 * result
				+ (getUsn() == null ? 0 : this.getUsn().hashCode());
		return result;
	}

}
