package sernet.gs.reveng;

// Generated Jun 5, 2015 1:28:30 PM by Hibernate Tools 3.4.0.CR1

/**
 * StgMapM31Zus generated by hbm2java
 */
public class StgMapM31Zus implements java.io.Serializable {

	private StgMapM31ZusId id;

	public StgMapM31Zus() {
	}

	public StgMapM31Zus(StgMapM31ZusId id) {
		this.id = id;
	}

	public StgMapM31ZusId getId() {
		return this.id;
	}

	public void setId(StgMapM31ZusId id) {
		this.id = id;
	}

}
