package sernet.gs.reveng;

// Generated Jun 5, 2015 1:28:30 PM by Hibernate Tools 3.4.0.CR1

/**
 * StgMbB2gDel generated by hbm2java
 */
public class StgMbB2gDel implements java.io.Serializable {

	private StgMbB2gDelId id;

	public StgMbB2gDel() {
	}

	public StgMbB2gDel(StgMbB2gDelId id) {
		this.id = id;
	}

	public StgMbB2gDelId getId() {
		return this.id;
	}

	public void setId(StgMbB2gDelId id) {
		this.id = id;
	}

}
