package sernet.gs.reveng;

// Generated Jun 5, 2015 1:28:30 PM by Hibernate Tools 3.4.0.CR1

/**
 * StgMbRolle generated by hbm2java
 */
public class StgMbRolle implements java.io.Serializable {

	private StgMbRolleId id;

	public StgMbRolle() {
	}

	public StgMbRolle(StgMbRolleId id) {
		this.id = id;
	}

	public StgMbRolleId getId() {
		return this.id;
	}

	public void setId(StgMbRolleId id) {
		this.id = id;
	}

}
