package sernet.gs.reveng;

// Generated Jun 5, 2015 1:28:30 PM by Hibernate Tools 3.4.0.CR1

/**
 * StgMbStatus generated by hbm2java
 */
public class StgMbStatus implements java.io.Serializable {

	private StgMbStatusId id;

	public StgMbStatus() {
	}

	public StgMbStatus(StgMbStatusId id) {
		this.id = id;
	}

	public StgMbStatusId getId() {
		return this.id;
	}

	public void setId(StgMbStatusId id) {
		this.id = id;
	}

}
