package sernet.gs.reveng;

// Generated Jun 5, 2015 1:28:30 PM by Hibernate Tools 3.4.0.CR1

/**
 * StgMbZielobjZusatz generated by hbm2java
 */
public class StgMbZielobjZusatz implements java.io.Serializable {

	private StgMbZielobjZusatzId id;

	public StgMbZielobjZusatz() {
	}

	public StgMbZielobjZusatz(StgMbZielobjZusatzId id) {
		this.id = id;
	}

	public StgMbZielobjZusatzId getId() {
		return this.id;
	}

	public void setId(StgMbZielobjZusatzId id) {
		this.id = id;
	}

}
