package sernet.gs.reveng;

// Generated Jun 5, 2015 1:28:30 PM by Hibernate Tools 3.4.0.CR1

/**
 * StgMapRer generated by hbm2java
 */
public class StgMapRer implements java.io.Serializable {

	private StgMapRerId id;

	public StgMapRer() {
	}

	public StgMapRer(StgMapRerId id) {
		this.id = id;
	}

	public StgMapRerId getId() {
		return this.id;
	}

	public void setId(StgMapRerId id) {
		this.id = id;
	}

}
