package sernet.gs.reveng;

// Generated Jun 5, 2015 1:28:30 PM by Hibernate Tools 3.4.0.CR1

/**
 * StgMbMassPhase generated by hbm2java
 */
public class StgMbMassPhase implements java.io.Serializable {

	private StgMbMassPhaseId id;

	public StgMbMassPhase() {
	}

	public StgMbMassPhase(StgMbMassPhaseId id) {
		this.id = id;
	}

	public StgMbMassPhaseId getId() {
		return this.id;
	}

	public void setId(StgMbMassPhaseId id) {
		this.id = id;
	}

}
