package sernet.gs.reveng;

// Generated Jun 5, 2015 1:28:30 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * StgMbDelGefahrId generated by hbm2java
 */
public class StgMbDelGefahrId implements java.io.Serializable {

	private Integer gefId;
	private Integer gefImpId;
	private Integer impId;
	private Date timestamp;
	private String guid;
	private String geloeschtDurch;

	public StgMbDelGefahrId() {
	}

	public StgMbDelGefahrId(Integer gefId, Integer gefImpId, Integer impId,
			Date timestamp, String guid, String geloeschtDurch) {
		this.gefId = gefId;
		this.gefImpId = gefImpId;
		this.impId = impId;
		this.timestamp = timestamp;
		this.guid = guid;
		this.geloeschtDurch = geloeschtDurch;
	}

	public Integer getGefId() {
		return this.gefId;
	}

	public void setGefId(Integer gefId) {
		this.gefId = gefId;
	}

	public Integer getGefImpId() {
		return this.gefImpId;
	}

	public void setGefImpId(Integer gefImpId) {
		this.gefImpId = gefImpId;
	}

	public Integer getImpId() {
		return this.impId;
	}

	public void setImpId(Integer impId) {
		this.impId = impId;
	}

	public Date getTimestamp() {
		return this.timestamp;
	}

	public void setTimestamp(Date timestamp) {
		this.timestamp = timestamp;
	}

	public String getGuid() {
		return this.guid;
	}

	public void setGuid(String guid) {
		this.guid = guid;
	}

	public String getGeloeschtDurch() {
		return this.geloeschtDurch;
	}

	public void setGeloeschtDurch(String geloeschtDurch) {
		this.geloeschtDurch = geloeschtDurch;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof StgMbDelGefahrId))
			return false;
		StgMbDelGefahrId castOther = (StgMbDelGefahrId) other;

		return ((this.getGefId() == castOther.getGefId()) || (this.getGefId() != null
				&& castOther.getGefId() != null && this.getGefId().equals(
				castOther.getGefId())))
				&& ((this.getGefImpId() == castOther.getGefImpId()) || (this
						.getGefImpId() != null
						&& castOther.getGefImpId() != null && this
						.getGefImpId().equals(castOther.getGefImpId())))
				&& ((this.getImpId() == castOther.getImpId()) || (this
						.getImpId() != null && castOther.getImpId() != null && this
						.getImpId().equals(castOther.getImpId())))
				&& ((this.getTimestamp() == castOther.getTimestamp()) || (this
						.getTimestamp() != null
						&& castOther.getTimestamp() != null && this
						.getTimestamp().equals(castOther.getTimestamp())))
				&& ((this.getGuid() == castOther.getGuid()) || (this.getGuid() != null
						&& castOther.getGuid() != null && this.getGuid()
						.equals(castOther.getGuid())))
				&& ((this.getGeloeschtDurch() == castOther.getGeloeschtDurch()) || (this
						.getGeloeschtDurch() != null
						&& castOther.getGeloeschtDurch() != null && this
						.getGeloeschtDurch().equals(
								castOther.getGeloeschtDurch())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getGefId() == null ? 0 : this.getGefId().hashCode());
		result = 37 * result
				+ (getGefImpId() == null ? 0 : this.getGefImpId().hashCode());
		result = 37 * result
				+ (getImpId() == null ? 0 : this.getImpId().hashCode());
		result = 37 * result
				+ (getTimestamp() == null ? 0 : this.getTimestamp().hashCode());
		result = 37 * result
				+ (getGuid() == null ? 0 : this.getGuid().hashCode());
		result = 37
				* result
				+ (getGeloeschtDurch() == null ? 0 : this.getGeloeschtDurch()
						.hashCode());
		return result;
	}

}
