package sernet.gs.reveng;

// Generated Jun 5, 2015 1:28:30 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * StgMsRaBehandId generated by hbm2java
 */
public class StgMsRaBehandId implements java.io.Serializable {

	private Byte rabId;
	private String guid;
	private Date erstelltAm;
	private String erstelltDurch;

	public StgMsRaBehandId() {
	}

	public StgMsRaBehandId(Byte rabId, String guid, Date erstelltAm,
			String erstelltDurch) {
		this.rabId = rabId;
		this.guid = guid;
		this.erstelltAm = erstelltAm;
		this.erstelltDurch = erstelltDurch;
	}

	public Byte getRabId() {
		return this.rabId;
	}

	public void setRabId(Byte rabId) {
		this.rabId = rabId;
	}

	public String getGuid() {
		return this.guid;
	}

	public void setGuid(String guid) {
		this.guid = guid;
	}

	public Date getErstelltAm() {
		return this.erstelltAm;
	}

	public void setErstelltAm(Date erstelltAm) {
		this.erstelltAm = erstelltAm;
	}

	public String getErstelltDurch() {
		return this.erstelltDurch;
	}

	public void setErstelltDurch(String erstelltDurch) {
		this.erstelltDurch = erstelltDurch;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof StgMsRaBehandId))
			return false;
		StgMsRaBehandId castOther = (StgMsRaBehandId) other;

		return ((this.getRabId() == castOther.getRabId()) || (this.getRabId() != null
				&& castOther.getRabId() != null && this.getRabId().equals(
				castOther.getRabId())))
				&& ((this.getGuid() == castOther.getGuid()) || (this.getGuid() != null
						&& castOther.getGuid() != null && this.getGuid()
						.equals(castOther.getGuid())))
				&& ((this.getErstelltAm() == castOther.getErstelltAm()) || (this
						.getErstelltAm() != null
						&& castOther.getErstelltAm() != null && this
						.getErstelltAm().equals(castOther.getErstelltAm())))
				&& ((this.getErstelltDurch() == castOther.getErstelltDurch()) || (this
						.getErstelltDurch() != null
						&& castOther.getErstelltDurch() != null && this
						.getErstelltDurch()
						.equals(castOther.getErstelltDurch())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getRabId() == null ? 0 : this.getRabId().hashCode());
		result = 37 * result
				+ (getGuid() == null ? 0 : this.getGuid().hashCode());
		result = 37
				* result
				+ (getErstelltAm() == null ? 0 : this.getErstelltAm()
						.hashCode());
		result = 37
				* result
				+ (getErstelltDurch() == null ? 0 : this.getErstelltDurch()
						.hashCode());
		return result;
	}

}
