package sernet.gs.reveng;

// Generated Jun 5, 2015 1:28:30 PM by Hibernate Tools 3.4.0.CR1

/**
 * StgMSprache generated by hbm2java
 */
public class StgMSprache implements java.io.Serializable {

	private StgMSpracheId id;

	public StgMSprache() {
	}

	public StgMSprache(StgMSpracheId id) {
		this.id = id;
	}

	public StgMSpracheId getId() {
		return this.id;
	}

	public void setId(StgMSpracheId id) {
		this.id = id;
	}

}
