package sernet.gs.reveng;

// Generated Jun 5, 2015 1:28:30 PM by Hibernate Tools 3.4.0.CR1

/**
 * StgMbGefaehrTxt generated by hbm2java
 */
public class StgMbGefaehrTxt implements java.io.Serializable {

	private StgMbGefaehrTxtId id;

	public StgMbGefaehrTxt() {
	}

	public StgMbGefaehrTxt(StgMbGefaehrTxtId id) {
		this.id = id;
	}

	public StgMbGefaehrTxtId getId() {
		return this.id;
	}

	public void setId(StgMbGefaehrTxtId id) {
		this.id = id;
	}

}
