package sernet.gs.reveng;

// Generated Jun 5, 2015 1:28:30 PM by Hibernate Tools 3.4.0.CR1

/**
 * StgNZielobjZielobj generated by hbm2java
 */
public class StgNZielobjZielobj implements java.io.Serializable {

	private StgNZielobjZielobjId id;

	public StgNZielobjZielobj() {
	}

	public StgNZielobjZielobj(StgNZielobjZielobjId id) {
		this.id = id;
	}

	public StgNZielobjZielobjId getId() {
		return this.id;
	}

	public void setId(StgNZielobjZielobjId id) {
		this.id = id;
	}

}
