package sernet.gs.reveng;

// Generated Jun 5, 2015 1:28:30 PM by Hibernate Tools 3.4.0.CR1

/**
 * StgNmbZusatz generated by hbm2java
 */
public class StgNmbZusatz implements java.io.Serializable {

	private StgNmbZusatzId id;

	public StgNmbZusatz() {
	}

	public StgNmbZusatz(StgNmbZusatzId id) {
		this.id = id;
	}

	public StgNmbZusatzId getId() {
		return this.id;
	}

	public void setId(StgNmbZusatzId id) {
		this.id = id;
	}

}
