package sernet.gs.reveng;

// Generated Jun 5, 2015 1:28:30 PM by Hibernate Tools 3.4.0.CR1

/**
 * StgNZielobjekt generated by hbm2java
 */
public class StgNZielobjekt implements java.io.Serializable {

	private StgNZielobjektId id;

	public StgNZielobjekt() {
	}

	public StgNZielobjekt(StgNZielobjektId id) {
		this.id = id;
	}

	public StgNZielobjektId getId() {
		return this.id;
	}

	public void setId(StgNZielobjektId id) {
		this.id = id;
	}

}
