package sernet.gs.reveng;

// Generated Jun 5, 2015 1:28:30 PM by Hibernate Tools 3.4.0.CR1

/**
 * StgRechteAnwenderImport generated by hbm2java
 */
public class StgRechteAnwenderImport implements java.io.Serializable {

	private StgRechteAnwenderImportId id;

	public StgRechteAnwenderImport() {
	}

	public StgRechteAnwenderImport(StgRechteAnwenderImportId id) {
		this.id = id;
	}

	public StgRechteAnwenderImportId getId() {
		return this.id;
	}

	public void setId(StgRechteAnwenderImportId id) {
		this.id = id;
	}

}
