package sernet.gs.reveng;

// Generated Jun 5, 2015 1:28:30 PM by Hibernate Tools 3.4.0.CR1

/**
 * StgRaZobGef generated by hbm2java
 */
public class StgRaZobGef implements java.io.Serializable {

	private StgRaZobGefId id;

	public StgRaZobGef() {
	}

	public StgRaZobGef(StgRaZobGefId id) {
		this.id = id;
	}

	public StgRaZobGefId getId() {
		return this.id;
	}

	public void setId(StgRaZobGefId id) {
		this.id = id;
	}

}
