package sernet.gs.reveng;

// Generated Jun 5, 2015 1:28:30 PM by Hibernate Tools 3.4.0.CR1

/**
 * StgRaZobGefMas generated by hbm2java
 */
public class StgRaZobGefMas implements java.io.Serializable {

	private StgRaZobGefMasId id;

	public StgRaZobGefMas() {
	}

	public StgRaZobGefMas(StgRaZobGefMasId id) {
		this.id = id;
	}

	public StgRaZobGefMasId getId() {
		return this.id;
	}

	public void setId(StgRaZobGefMasId id) {
		this.id = id;
	}

}
