package sernet.gs.reveng;

// Generated Jun 5, 2015 1:28:30 PM by Hibernate Tools 3.4.0.CR1

/**
 * StgRechteAnwender generated by hbm2java
 */
public class StgRechteAnwender implements java.io.Serializable {

	private StgRechteAnwenderId id;

	public StgRechteAnwender() {
	}

	public StgRechteAnwender(StgRechteAnwenderId id) {
		this.id = id;
	}

	public StgRechteAnwenderId getId() {
		return this.id;
	}

	public void setId(StgRechteAnwenderId id) {
		this.id = id;
	}

}
