package sernet.gs.reveng;

// Generated Jun 5, 2015 1:28:30 PM by Hibernate Tools 3.4.0.CR1

/**
 * StgSysMapping generated by hbm2java
 */
public class StgSysMapping implements java.io.Serializable {

	private StgSysMappingId id;

	public StgSysMapping() {
	}

	public StgSysMapping(StgSysMappingId id) {
		this.id = id;
	}

	public StgSysMappingId getId() {
		return this.id;
	}

	public void setId(StgSysMappingId id) {
		this.id = id;
	}

}
