package sernet.gs.reveng;

// Generated Jun 5, 2015 1:28:30 PM by Hibernate Tools 3.4.0.CR1

/**
 * StgSysIdentifier generated by hbm2java
 */
public class StgSysIdentifier implements java.io.Serializable {

	private StgSysIdentifierId id;

	public StgSysIdentifier() {
	}

	public StgSysIdentifier(StgSysIdentifierId id) {
		this.id = id;
	}

	public StgSysIdentifierId getId() {
		return this.id;
	}

	public void setId(StgSysIdentifierId id) {
		this.id = id;
	}

}
