package sernet.gs.reveng;

// Generated Jun 5, 2015 1:28:30 PM by Hibernate Tools 3.4.0.CR1

/**
 * StgSysStandortMapping generated by hbm2java
 */
public class StgSysStandortMapping implements java.io.Serializable {

	private StgSysStandortMappingId id;

	public StgSysStandortMapping() {
	}

	public StgSysStandortMapping(StgSysStandortMappingId id) {
		this.id = id;
	}

	public StgSysStandortMappingId getId() {
		return this.id;
	}

	public void setId(StgSysStandortMappingId id) {
		this.id = id;
	}

}
