package sernet.gs.reveng;

// Generated Jun 5, 2015 1:28:30 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * StgSysExportNotizId generated by hbm2java
 */
public class StgSysExportNotizId implements java.io.Serializable {

	private Integer expId;
	private Integer notizId;
	private Integer notizImpId;
	private Date erstelltAm;

	public StgSysExportNotizId() {
	}

	public StgSysExportNotizId(Integer expId, Integer notizId,
			Integer notizImpId, Date erstelltAm) {
		this.expId = expId;
		this.notizId = notizId;
		this.notizImpId = notizImpId;
		this.erstelltAm = erstelltAm;
	}

	public Integer getExpId() {
		return this.expId;
	}

	public void setExpId(Integer expId) {
		this.expId = expId;
	}

	public Integer getNotizId() {
		return this.notizId;
	}

	public void setNotizId(Integer notizId) {
		this.notizId = notizId;
	}

	public Integer getNotizImpId() {
		return this.notizImpId;
	}

	public void setNotizImpId(Integer notizImpId) {
		this.notizImpId = notizImpId;
	}

	public Date getErstelltAm() {
		return this.erstelltAm;
	}

	public void setErstelltAm(Date erstelltAm) {
		this.erstelltAm = erstelltAm;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof StgSysExportNotizId))
			return false;
		StgSysExportNotizId castOther = (StgSysExportNotizId) other;

		return ((this.getExpId() == castOther.getExpId()) || (this.getExpId() != null
				&& castOther.getExpId() != null && this.getExpId().equals(
				castOther.getExpId())))
				&& ((this.getNotizId() == castOther.getNotizId()) || (this
						.getNotizId() != null && castOther.getNotizId() != null && this
						.getNotizId().equals(castOther.getNotizId())))
				&& ((this.getNotizImpId() == castOther.getNotizImpId()) || (this
						.getNotizImpId() != null
						&& castOther.getNotizImpId() != null && this
						.getNotizImpId().equals(castOther.getNotizImpId())))
				&& ((this.getErstelltAm() == castOther.getErstelltAm()) || (this
						.getErstelltAm() != null
						&& castOther.getErstelltAm() != null && this
						.getErstelltAm().equals(castOther.getErstelltAm())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getExpId() == null ? 0 : this.getExpId().hashCode());
		result = 37 * result
				+ (getNotizId() == null ? 0 : this.getNotizId().hashCode());
		result = 37
				* result
				+ (getNotizImpId() == null ? 0 : this.getNotizImpId()
						.hashCode());
		result = 37
				* result
				+ (getErstelltAm() == null ? 0 : this.getErstelltAm()
						.hashCode());
		return result;
	}

}
