package sernet.gs.reveng;

// Generated Jun 5, 2015 1:28:30 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * StgSysExportBauId generated by hbm2java
 */
public class StgSysExportBauId implements java.io.Serializable {

	private Integer expId;
	private Integer bauId;
	private Integer bauImpId;
	private Date timestamp;

	public StgSysExportBauId() {
	}

	public StgSysExportBauId(Integer expId, Integer bauId, Integer bauImpId,
			Date timestamp) {
		this.expId = expId;
		this.bauId = bauId;
		this.bauImpId = bauImpId;
		this.timestamp = timestamp;
	}

	public Integer getExpId() {
		return this.expId;
	}

	public void setExpId(Integer expId) {
		this.expId = expId;
	}

	public Integer getBauId() {
		return this.bauId;
	}

	public void setBauId(Integer bauId) {
		this.bauId = bauId;
	}

	public Integer getBauImpId() {
		return this.bauImpId;
	}

	public void setBauImpId(Integer bauImpId) {
		this.bauImpId = bauImpId;
	}

	public Date getTimestamp() {
		return this.timestamp;
	}

	public void setTimestamp(Date timestamp) {
		this.timestamp = timestamp;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof StgSysExportBauId))
			return false;
		StgSysExportBauId castOther = (StgSysExportBauId) other;

		return ((this.getExpId() == castOther.getExpId()) || (this.getExpId() != null
				&& castOther.getExpId() != null && this.getExpId().equals(
				castOther.getExpId())))
				&& ((this.getBauId() == castOther.getBauId()) || (this
						.getBauId() != null && castOther.getBauId() != null && this
						.getBauId().equals(castOther.getBauId())))
				&& ((this.getBauImpId() == castOther.getBauImpId()) || (this
						.getBauImpId() != null
						&& castOther.getBauImpId() != null && this
						.getBauImpId().equals(castOther.getBauImpId())))
				&& ((this.getTimestamp() == castOther.getTimestamp()) || (this
						.getTimestamp() != null
						&& castOther.getTimestamp() != null && this
						.getTimestamp().equals(castOther.getTimestamp())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getExpId() == null ? 0 : this.getExpId().hashCode());
		result = 37 * result
				+ (getBauId() == null ? 0 : this.getBauId().hashCode());
		result = 37 * result
				+ (getBauImpId() == null ? 0 : this.getBauImpId().hashCode());
		result = 37 * result
				+ (getTimestamp() == null ? 0 : this.getTimestamp().hashCode());
		return result;
	}

}
