package sernet.gs.reveng;

// Generated Jun 5, 2015 1:28:30 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * StgSysHistorieId generated by hbm2java
 */
public class StgSysHistorieId implements java.io.Serializable {

	private Integer hisId;
	private Integer hisUsn;
	private String hisUser;
	private String hisLogin;
	private String hisGuid;
	private String hisSpalte;
	private String hisSpalteImp;
	private String hisSpalte2;
	private String hisAltWert;
	private Date hisAltDatum;
	private BigDecimal hisAltDecimal;
	private Integer hisAltId;
	private Integer hisAltImpId;
	private Integer hisNr;
	private Short hisUid;
	private Date timestamp;
	private Integer dtyId;

	public StgSysHistorieId() {
	}

	public StgSysHistorieId(Integer hisId, Integer hisUsn, String hisUser,
			String hisLogin, String hisGuid, String hisSpalte,
			String hisSpalteImp, String hisSpalte2, String hisAltWert,
			Date hisAltDatum, BigDecimal hisAltDecimal, Integer hisAltId,
			Integer hisAltImpId, Integer hisNr, Short hisUid, Date timestamp,
			Integer dtyId) {
		this.hisId = hisId;
		this.hisUsn = hisUsn;
		this.hisUser = hisUser;
		this.hisLogin = hisLogin;
		this.hisGuid = hisGuid;
		this.hisSpalte = hisSpalte;
		this.hisSpalteImp = hisSpalteImp;
		this.hisSpalte2 = hisSpalte2;
		this.hisAltWert = hisAltWert;
		this.hisAltDatum = hisAltDatum;
		this.hisAltDecimal = hisAltDecimal;
		this.hisAltId = hisAltId;
		this.hisAltImpId = hisAltImpId;
		this.hisNr = hisNr;
		this.hisUid = hisUid;
		this.timestamp = timestamp;
		this.dtyId = dtyId;
	}

	public Integer getHisId() {
		return this.hisId;
	}

	public void setHisId(Integer hisId) {
		this.hisId = hisId;
	}

	public Integer getHisUsn() {
		return this.hisUsn;
	}

	public void setHisUsn(Integer hisUsn) {
		this.hisUsn = hisUsn;
	}

	public String getHisUser() {
		return this.hisUser;
	}

	public void setHisUser(String hisUser) {
		this.hisUser = hisUser;
	}

	public String getHisLogin() {
		return this.hisLogin;
	}

	public void setHisLogin(String hisLogin) {
		this.hisLogin = hisLogin;
	}

	public String getHisGuid() {
		return this.hisGuid;
	}

	public void setHisGuid(String hisGuid) {
		this.hisGuid = hisGuid;
	}

	public String getHisSpalte() {
		return this.hisSpalte;
	}

	public void setHisSpalte(String hisSpalte) {
		this.hisSpalte = hisSpalte;
	}

	public String getHisSpalteImp() {
		return this.hisSpalteImp;
	}

	public void setHisSpalteImp(String hisSpalteImp) {
		this.hisSpalteImp = hisSpalteImp;
	}

	public String getHisSpalte2() {
		return this.hisSpalte2;
	}

	public void setHisSpalte2(String hisSpalte2) {
		this.hisSpalte2 = hisSpalte2;
	}

	public String getHisAltWert() {
		return this.hisAltWert;
	}

	public void setHisAltWert(String hisAltWert) {
		this.hisAltWert = hisAltWert;
	}

	public Date getHisAltDatum() {
		return this.hisAltDatum;
	}

	public void setHisAltDatum(Date hisAltDatum) {
		this.hisAltDatum = hisAltDatum;
	}

	public BigDecimal getHisAltDecimal() {
		return this.hisAltDecimal;
	}

	public void setHisAltDecimal(BigDecimal hisAltDecimal) {
		this.hisAltDecimal = hisAltDecimal;
	}

	public Integer getHisAltId() {
		return this.hisAltId;
	}

	public void setHisAltId(Integer hisAltId) {
		this.hisAltId = hisAltId;
	}

	public Integer getHisAltImpId() {
		return this.hisAltImpId;
	}

	public void setHisAltImpId(Integer hisAltImpId) {
		this.hisAltImpId = hisAltImpId;
	}

	public Integer getHisNr() {
		return this.hisNr;
	}

	public void setHisNr(Integer hisNr) {
		this.hisNr = hisNr;
	}

	public Short getHisUid() {
		return this.hisUid;
	}

	public void setHisUid(Short hisUid) {
		this.hisUid = hisUid;
	}

	public Date getTimestamp() {
		return this.timestamp;
	}

	public void setTimestamp(Date timestamp) {
		this.timestamp = timestamp;
	}

	public Integer getDtyId() {
		return this.dtyId;
	}

	public void setDtyId(Integer dtyId) {
		this.dtyId = dtyId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof StgSysHistorieId))
			return false;
		StgSysHistorieId castOther = (StgSysHistorieId) other;

		return ((this.getHisId() == castOther.getHisId()) || (this.getHisId() != null
				&& castOther.getHisId() != null && this.getHisId().equals(
				castOther.getHisId())))
				&& ((this.getHisUsn() == castOther.getHisUsn()) || (this
						.getHisUsn() != null && castOther.getHisUsn() != null && this
						.getHisUsn().equals(castOther.getHisUsn())))
				&& ((this.getHisUser() == castOther.getHisUser()) || (this
						.getHisUser() != null && castOther.getHisUser() != null && this
						.getHisUser().equals(castOther.getHisUser())))
				&& ((this.getHisLogin() == castOther.getHisLogin()) || (this
						.getHisLogin() != null
						&& castOther.getHisLogin() != null && this
						.getHisLogin().equals(castOther.getHisLogin())))
				&& ((this.getHisGuid() == castOther.getHisGuid()) || (this
						.getHisGuid() != null && castOther.getHisGuid() != null && this
						.getHisGuid().equals(castOther.getHisGuid())))
				&& ((this.getHisSpalte() == castOther.getHisSpalte()) || (this
						.getHisSpalte() != null
						&& castOther.getHisSpalte() != null && this
						.getHisSpalte().equals(castOther.getHisSpalte())))
				&& ((this.getHisSpalteImp() == castOther.getHisSpalteImp()) || (this
						.getHisSpalteImp() != null
						&& castOther.getHisSpalteImp() != null && this
						.getHisSpalteImp().equals(castOther.getHisSpalteImp())))
				&& ((this.getHisSpalte2() == castOther.getHisSpalte2()) || (this
						.getHisSpalte2() != null
						&& castOther.getHisSpalte2() != null && this
						.getHisSpalte2().equals(castOther.getHisSpalte2())))
				&& ((this.getHisAltWert() == castOther.getHisAltWert()) || (this
						.getHisAltWert() != null
						&& castOther.getHisAltWert() != null && this
						.getHisAltWert().equals(castOther.getHisAltWert())))
				&& ((this.getHisAltDatum() == castOther.getHisAltDatum()) || (this
						.getHisAltDatum() != null
						&& castOther.getHisAltDatum() != null && this
						.getHisAltDatum().equals(castOther.getHisAltDatum())))
				&& ((this.getHisAltDecimal() == castOther.getHisAltDecimal()) || (this
						.getHisAltDecimal() != null
						&& castOther.getHisAltDecimal() != null && this
						.getHisAltDecimal()
						.equals(castOther.getHisAltDecimal())))
				&& ((this.getHisAltId() == castOther.getHisAltId()) || (this
						.getHisAltId() != null
						&& castOther.getHisAltId() != null && this
						.getHisAltId().equals(castOther.getHisAltId())))
				&& ((this.getHisAltImpId() == castOther.getHisAltImpId()) || (this
						.getHisAltImpId() != null
						&& castOther.getHisAltImpId() != null && this
						.getHisAltImpId().equals(castOther.getHisAltImpId())))
				&& ((this.getHisNr() == castOther.getHisNr()) || (this
						.getHisNr() != null && castOther.getHisNr() != null && this
						.getHisNr().equals(castOther.getHisNr())))
				&& ((this.getHisUid() == castOther.getHisUid()) || (this
						.getHisUid() != null && castOther.getHisUid() != null && this
						.getHisUid().equals(castOther.getHisUid())))
				&& ((this.getTimestamp() == castOther.getTimestamp()) || (this
						.getTimestamp() != null
						&& castOther.getTimestamp() != null && this
						.getTimestamp().equals(castOther.getTimestamp())))
				&& ((this.getDtyId() == castOther.getDtyId()) || (this
						.getDtyId() != null && castOther.getDtyId() != null && this
						.getDtyId().equals(castOther.getDtyId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getHisId() == null ? 0 : this.getHisId().hashCode());
		result = 37 * result
				+ (getHisUsn() == null ? 0 : this.getHisUsn().hashCode());
		result = 37 * result
				+ (getHisUser() == null ? 0 : this.getHisUser().hashCode());
		result = 37 * result
				+ (getHisLogin() == null ? 0 : this.getHisLogin().hashCode());
		result = 37 * result
				+ (getHisGuid() == null ? 0 : this.getHisGuid().hashCode());
		result = 37 * result
				+ (getHisSpalte() == null ? 0 : this.getHisSpalte().hashCode());
		result = 37
				* result
				+ (getHisSpalteImp() == null ? 0 : this.getHisSpalteImp()
						.hashCode());
		result = 37
				* result
				+ (getHisSpalte2() == null ? 0 : this.getHisSpalte2()
						.hashCode());
		result = 37
				* result
				+ (getHisAltWert() == null ? 0 : this.getHisAltWert()
						.hashCode());
		result = 37
				* result
				+ (getHisAltDatum() == null ? 0 : this.getHisAltDatum()
						.hashCode());
		result = 37
				* result
				+ (getHisAltDecimal() == null ? 0 : this.getHisAltDecimal()
						.hashCode());
		result = 37 * result
				+ (getHisAltId() == null ? 0 : this.getHisAltId().hashCode());
		result = 37
				* result
				+ (getHisAltImpId() == null ? 0 : this.getHisAltImpId()
						.hashCode());
		result = 37 * result
				+ (getHisNr() == null ? 0 : this.getHisNr().hashCode());
		result = 37 * result
				+ (getHisUid() == null ? 0 : this.getHisUid().hashCode());
		result = 37 * result
				+ (getTimestamp() == null ? 0 : this.getTimestamp().hashCode());
		result = 37 * result
				+ (getDtyId() == null ? 0 : this.getDtyId().hashCode());
		return result;
	}

}
