package sernet.gs.reveng;

// Generated Jun 5, 2015 1:28:30 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * StgSysIdentifierId generated by hbm2java
 */
public class StgSysIdentifierId implements java.io.Serializable {

	private String ideTabelle;
	private Integer ideImpId;
	private Integer ideCurrentId;
	private Date timestamp;
	private String guid;

	public StgSysIdentifierId() {
	}

	public StgSysIdentifierId(String ideTabelle, Integer ideImpId,
			Integer ideCurrentId, Date timestamp, String guid) {
		this.ideTabelle = ideTabelle;
		this.ideImpId = ideImpId;
		this.ideCurrentId = ideCurrentId;
		this.timestamp = timestamp;
		this.guid = guid;
	}

	public String getIdeTabelle() {
		return this.ideTabelle;
	}

	public void setIdeTabelle(String ideTabelle) {
		this.ideTabelle = ideTabelle;
	}

	public Integer getIdeImpId() {
		return this.ideImpId;
	}

	public void setIdeImpId(Integer ideImpId) {
		this.ideImpId = ideImpId;
	}

	public Integer getIdeCurrentId() {
		return this.ideCurrentId;
	}

	public void setIdeCurrentId(Integer ideCurrentId) {
		this.ideCurrentId = ideCurrentId;
	}

	public Date getTimestamp() {
		return this.timestamp;
	}

	public void setTimestamp(Date timestamp) {
		this.timestamp = timestamp;
	}

	public String getGuid() {
		return this.guid;
	}

	public void setGuid(String guid) {
		this.guid = guid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof StgSysIdentifierId))
			return false;
		StgSysIdentifierId castOther = (StgSysIdentifierId) other;

		return ((this.getIdeTabelle() == castOther.getIdeTabelle()) || (this
				.getIdeTabelle() != null && castOther.getIdeTabelle() != null && this
				.getIdeTabelle().equals(castOther.getIdeTabelle())))
				&& ((this.getIdeImpId() == castOther.getIdeImpId()) || (this
						.getIdeImpId() != null
						&& castOther.getIdeImpId() != null && this
						.getIdeImpId().equals(castOther.getIdeImpId())))
				&& ((this.getIdeCurrentId() == castOther.getIdeCurrentId()) || (this
						.getIdeCurrentId() != null
						&& castOther.getIdeCurrentId() != null && this
						.getIdeCurrentId().equals(castOther.getIdeCurrentId())))
				&& ((this.getTimestamp() == castOther.getTimestamp()) || (this
						.getTimestamp() != null
						&& castOther.getTimestamp() != null && this
						.getTimestamp().equals(castOther.getTimestamp())))
				&& ((this.getGuid() == castOther.getGuid()) || (this.getGuid() != null
						&& castOther.getGuid() != null && this.getGuid()
						.equals(castOther.getGuid())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getIdeTabelle() == null ? 0 : this.getIdeTabelle()
						.hashCode());
		result = 37 * result
				+ (getIdeImpId() == null ? 0 : this.getIdeImpId().hashCode());
		result = 37
				* result
				+ (getIdeCurrentId() == null ? 0 : this.getIdeCurrentId()
						.hashCode());
		result = 37 * result
				+ (getTimestamp() == null ? 0 : this.getTimestamp().hashCode());
		result = 37 * result
				+ (getGuid() == null ? 0 : this.getGuid().hashCode());
		return result;
	}

}
