package sernet.gs.reveng;

// Generated Jun 5, 2015 1:28:30 PM by Hibernate Tools 3.4.0.CR1

/**
 * StgSysNetzMapping generated by hbm2java
 */
public class StgSysNetzMapping implements java.io.Serializable {

	private StgSysNetzMappingId id;

	public StgSysNetzMapping() {
	}

	public StgSysNetzMapping(StgSysNetzMappingId id) {
		this.id = id;
	}

	public StgSysNetzMappingId getId() {
		return this.id;
	}

	public void setId(StgSysNetzMappingId id) {
		this.id = id;
	}

}
