package sernet.gs.reveng;

// Generated Jun 5, 2015 1:28:30 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * SysExportZos generated by hbm2java
 */
public class SysExportZos implements java.io.Serializable {

	private SysExportZosId id;
	private Date timestamp;
	private SysExport sysExport;

	public SysExportZos() {
	}

	public SysExportZos(SysExportZosId id, SysExport sysExport) {
		this.id = id;
		this.sysExport = sysExport;
	}

	public SysExportZosId getId() {
		return this.id;
	}

	public void setId(SysExportZosId id) {
		this.id = id;
	}

	public Date getTimestamp() {
		return this.timestamp;
	}

	public void setTimestamp(Date timestamp) {
		this.timestamp = timestamp;
	}

	public SysExport getSysExport() {
		return this.sysExport;
	}

	public void setSysExport(SysExport sysExport) {
		this.sysExport = sysExport;
	}

}
