package sernet.gs.reveng;

// Generated Jun 5, 2015 1:28:30 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * SysExportItv generated by hbm2java
 */
public class SysExportItv implements java.io.Serializable {

	private SysExportItvId id;
	private Date timestamp;
	private NZielobjekt NZielobjekt;
	private SysExport sysExport;

	public SysExportItv() {
	}

	public SysExportItv(SysExportItvId id, NZielobjekt NZielobjekt,
			SysExport sysExport) {
		this.id = id;
		this.NZielobjekt = NZielobjekt;
		this.sysExport = sysExport;
	}

	public SysExportItvId getId() {
		return this.id;
	}

	public void setId(SysExportItvId id) {
		this.id = id;
	}

	public Date getTimestamp() {
		return this.timestamp;
	}

	public void setTimestamp(Date timestamp) {
		this.timestamp = timestamp;
	}

	public NZielobjekt getNZielobjekt() {
		return this.NZielobjekt;
	}

	public void setNZielobjekt(NZielobjekt NZielobjekt) {
		this.NZielobjekt = NZielobjekt;
	}

	public SysExport getSysExport() {
		return this.sysExport;
	}

	public void setSysExport(SysExport sysExport) {
		this.sysExport = sysExport;
	}

}
