package sernet.gs.reveng;

// Generated Jun 5, 2015 1:28:30 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * SysExportMas generated by hbm2java
 */
public class SysExportMas implements java.io.Serializable {

	private SysExportMasId id;
	private Date timestamp;
	private SysExport sysExport;

	public SysExportMas() {
	}

	public SysExportMas(SysExportMasId id, SysExport sysExport) {
		this.id = id;
		this.sysExport = sysExport;
	}

	public SysExportMasId getId() {
		return this.id;
	}

	public void setId(SysExportMasId id) {
		this.id = id;
	}

	public Date getTimestamp() {
		return this.timestamp;
	}

	public void setTimestamp(Date timestamp) {
		this.timestamp = timestamp;
	}

	public SysExport getSysExport() {
		return this.sysExport;
	}

	public void setSysExport(SysExport sysExport) {
		this.sysExport = sysExport;
	}

}
