package sernet.gs.reveng;

// Generated Jun 5, 2015 1:28:30 PM by Hibernate Tools 3.4.0.CR1

/**
 * SysIdentifierId generated by hbm2java
 */
public class SysIdentifierId implements java.io.Serializable {

	private int ideImpId;
	private String ideTabelle;

	public SysIdentifierId() {
	}

	public SysIdentifierId(int ideImpId, String ideTabelle) {
		this.ideImpId = ideImpId;
		this.ideTabelle = ideTabelle;
	}

	public int getIdeImpId() {
		return this.ideImpId;
	}

	public void setIdeImpId(int ideImpId) {
		this.ideImpId = ideImpId;
	}

	public String getIdeTabelle() {
		return this.ideTabelle;
	}

	public void setIdeTabelle(String ideTabelle) {
		this.ideTabelle = ideTabelle;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SysIdentifierId))
			return false;
		SysIdentifierId castOther = (SysIdentifierId) other;

		return (this.getIdeImpId() == castOther.getIdeImpId())
				&& ((this.getIdeTabelle() == castOther.getIdeTabelle()) || (this
						.getIdeTabelle() != null
						&& castOther.getIdeTabelle() != null && this
						.getIdeTabelle().equals(castOther.getIdeTabelle())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdeImpId();
		result = 37
				* result
				+ (getIdeTabelle() == null ? 0 : this.getIdeTabelle()
						.hashCode());
		return result;
	}

}
