package sernet.gs.reveng;

// Generated Jun 5, 2015 1:28:30 PM by Hibernate Tools 3.4.0.CR1

/**
 * SysLocks generated by hbm2java
 */
public class SysLocks implements java.io.Serializable {

	private SysLocksId id;

	public SysLocks() {
	}

	public SysLocks(SysLocksId id) {
		this.id = id;
	}

	public SysLocksId getId() {
		return this.id;
	}

	public void setId(SysLocksId id) {
		this.id = id;
	}

}
