package sernet.gs.reveng;

// Generated Jun 5, 2015 1:28:30 PM by Hibernate Tools 3.4.0.CR1

/**
 * SysLogging generated by hbm2java
 */
public class SysLogging implements java.io.Serializable {

	private SysLoggingId id;

	public SysLogging() {
	}

	public SysLogging(SysLoggingId id) {
		this.id = id;
	}

	public SysLoggingId getId() {
		return this.id;
	}

	public void setId(SysLoggingId id) {
		this.id = id;
	}

}
