package sernet.gs.reveng;

// Generated Jun 5, 2015 1:28:30 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * SysProperties generated by hbm2java
 */
public class SysProperties implements java.io.Serializable {

	private SysPropertiesId id;
	private Integer propLong;
	private String propVarc;
	private Integer defaultLong;
	private String defaultVarc;
	private String propComment;
	private short versionMajor;
	private short versionMinor;
	private String guid;
	private Date erstelltAm;
	private String erstelltDurch;

	public SysProperties() {
	}

	public SysProperties(SysPropertiesId id, short versionMajor,
			short versionMinor, Date erstelltAm, String erstelltDurch) {
		this.id = id;
		this.versionMajor = versionMajor;
		this.versionMinor = versionMinor;
		this.erstelltAm = erstelltAm;
		this.erstelltDurch = erstelltDurch;
	}

	public SysProperties(SysPropertiesId id, Integer propLong, String propVarc,
			Integer defaultLong, String defaultVarc, String propComment,
			short versionMajor, short versionMinor, String guid,
			Date erstelltAm, String erstelltDurch) {
		this.id = id;
		this.propLong = propLong;
		this.propVarc = propVarc;
		this.defaultLong = defaultLong;
		this.defaultVarc = defaultVarc;
		this.propComment = propComment;
		this.versionMajor = versionMajor;
		this.versionMinor = versionMinor;
		this.guid = guid;
		this.erstelltAm = erstelltAm;
		this.erstelltDurch = erstelltDurch;
	}

	public SysPropertiesId getId() {
		return this.id;
	}

	public void setId(SysPropertiesId id) {
		this.id = id;
	}

	public Integer getPropLong() {
		return this.propLong;
	}

	public void setPropLong(Integer propLong) {
		this.propLong = propLong;
	}

	public String getPropVarc() {
		return this.propVarc;
	}

	public void setPropVarc(String propVarc) {
		this.propVarc = propVarc;
	}

	public Integer getDefaultLong() {
		return this.defaultLong;
	}

	public void setDefaultLong(Integer defaultLong) {
		this.defaultLong = defaultLong;
	}

	public String getDefaultVarc() {
		return this.defaultVarc;
	}

	public void setDefaultVarc(String defaultVarc) {
		this.defaultVarc = defaultVarc;
	}

	public String getPropComment() {
		return this.propComment;
	}

	public void setPropComment(String propComment) {
		this.propComment = propComment;
	}

	public short getVersionMajor() {
		return this.versionMajor;
	}

	public void setVersionMajor(short versionMajor) {
		this.versionMajor = versionMajor;
	}

	public short getVersionMinor() {
		return this.versionMinor;
	}

	public void setVersionMinor(short versionMinor) {
		this.versionMinor = versionMinor;
	}

	public String getGuid() {
		return this.guid;
	}

	public void setGuid(String guid) {
		this.guid = guid;
	}

	public Date getErstelltAm() {
		return this.erstelltAm;
	}

	public void setErstelltAm(Date erstelltAm) {
		this.erstelltAm = erstelltAm;
	}

	public String getErstelltDurch() {
		return this.erstelltDurch;
	}

	public void setErstelltDurch(String erstelltDurch) {
		this.erstelltDurch = erstelltDurch;
	}

}
