package sernet.gs.reveng;

// Generated Jun 5, 2015 1:28:30 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * SysUsertbs generated by hbm2java
 */
public class SysUsertbs implements java.io.Serializable {

	private int tbsId;
	private Date timestamp;
	private RechteAnwender rechteAnwender;
	private String tbsText;
	private short tbsKeycode1;
	private Short tbsKeycode2;
	private short tbsShift;
	private String guid;

	public SysUsertbs() {
	}

	public SysUsertbs(int tbsId, RechteAnwender rechteAnwender, String tbsText,
			short tbsKeycode1, short tbsShift, String guid) {
		this.tbsId = tbsId;
		this.rechteAnwender = rechteAnwender;
		this.tbsText = tbsText;
		this.tbsKeycode1 = tbsKeycode1;
		this.tbsShift = tbsShift;
		this.guid = guid;
	}

	public SysUsertbs(int tbsId, RechteAnwender rechteAnwender, String tbsText,
			short tbsKeycode1, Short tbsKeycode2, short tbsShift, String guid) {
		this.tbsId = tbsId;
		this.rechteAnwender = rechteAnwender;
		this.tbsText = tbsText;
		this.tbsKeycode1 = tbsKeycode1;
		this.tbsKeycode2 = tbsKeycode2;
		this.tbsShift = tbsShift;
		this.guid = guid;
	}

	public int getTbsId() {
		return this.tbsId;
	}

	public void setTbsId(int tbsId) {
		this.tbsId = tbsId;
	}

	public Date getTimestamp() {
		return this.timestamp;
	}

	public void setTimestamp(Date timestamp) {
		this.timestamp = timestamp;
	}

	public RechteAnwender getRechteAnwender() {
		return this.rechteAnwender;
	}

	public void setRechteAnwender(RechteAnwender rechteAnwender) {
		this.rechteAnwender = rechteAnwender;
	}

	public String getTbsText() {
		return this.tbsText;
	}

	public void setTbsText(String tbsText) {
		this.tbsText = tbsText;
	}

	public short getTbsKeycode1() {
		return this.tbsKeycode1;
	}

	public void setTbsKeycode1(short tbsKeycode1) {
		this.tbsKeycode1 = tbsKeycode1;
	}

	public Short getTbsKeycode2() {
		return this.tbsKeycode2;
	}

	public void setTbsKeycode2(Short tbsKeycode2) {
		this.tbsKeycode2 = tbsKeycode2;
	}

	public short getTbsShift() {
		return this.tbsShift;
	}

	public void setTbsShift(short tbsShift) {
		this.tbsShift = tbsShift;
	}

	public String getGuid() {
		return this.guid;
	}

	public void setGuid(String guid) {
		this.guid = guid;
	}

}
