package sernet.gs.reveng;

// Generated Jun 5, 2015 1:28:30 PM by Hibernate Tools 3.4.0.CR1

/**
 * TmpBauSel generated by hbm2java
 */
public class TmpBauSel implements java.io.Serializable {

	private TmpBauSelId id;
	private Integer prio;
	private Integer neuId;
	private Integer neuImpId;
	private Character typ;
	private Integer altId;
	private Integer altImpId;
	private boolean recoverable;
	private boolean recover;
	private boolean createok;
	private boolean deleted;
	private boolean existing;
	private int usn;
	private boolean ignore;

	public TmpBauSel() {
	}

	public TmpBauSel(TmpBauSelId id, boolean recoverable, boolean recover,
			boolean createok, boolean deleted, boolean existing, int usn,
			boolean ignore) {
		this.id = id;
		this.recoverable = recoverable;
		this.recover = recover;
		this.createok = createok;
		this.deleted = deleted;
		this.existing = existing;
		this.usn = usn;
		this.ignore = ignore;
	}

	public TmpBauSel(TmpBauSelId id, Integer prio, Integer neuId,
			Integer neuImpId, Character typ, Integer altId, Integer altImpId,
			boolean recoverable, boolean recover, boolean createok,
			boolean deleted, boolean existing, int usn, boolean ignore) {
		this.id = id;
		this.prio = prio;
		this.neuId = neuId;
		this.neuImpId = neuImpId;
		this.typ = typ;
		this.altId = altId;
		this.altImpId = altImpId;
		this.recoverable = recoverable;
		this.recover = recover;
		this.createok = createok;
		this.deleted = deleted;
		this.existing = existing;
		this.usn = usn;
		this.ignore = ignore;
	}

	public TmpBauSelId getId() {
		return this.id;
	}

	public void setId(TmpBauSelId id) {
		this.id = id;
	}

	public Integer getPrio() {
		return this.prio;
	}

	public void setPrio(Integer prio) {
		this.prio = prio;
	}

	public Integer getNeuId() {
		return this.neuId;
	}

	public void setNeuId(Integer neuId) {
		this.neuId = neuId;
	}

	public Integer getNeuImpId() {
		return this.neuImpId;
	}

	public void setNeuImpId(Integer neuImpId) {
		this.neuImpId = neuImpId;
	}

	public Character getTyp() {
		return this.typ;
	}

	public void setTyp(Character typ) {
		this.typ = typ;
	}

	public Integer getAltId() {
		return this.altId;
	}

	public void setAltId(Integer altId) {
		this.altId = altId;
	}

	public Integer getAltImpId() {
		return this.altImpId;
	}

	public void setAltImpId(Integer altImpId) {
		this.altImpId = altImpId;
	}

	public boolean isRecoverable() {
		return this.recoverable;
	}

	public void setRecoverable(boolean recoverable) {
		this.recoverable = recoverable;
	}

	public boolean isRecover() {
		return this.recover;
	}

	public void setRecover(boolean recover) {
		this.recover = recover;
	}

	public boolean isCreateok() {
		return this.createok;
	}

	public void setCreateok(boolean createok) {
		this.createok = createok;
	}

	public boolean isDeleted() {
		return this.deleted;
	}

	public void setDeleted(boolean deleted) {
		this.deleted = deleted;
	}

	public boolean isExisting() {
		return this.existing;
	}

	public void setExisting(boolean existing) {
		this.existing = existing;
	}

	public int getUsn() {
		return this.usn;
	}

	public void setUsn(int usn) {
		this.usn = usn;
	}

	public boolean isIgnore() {
		return this.ignore;
	}

	public void setIgnore(boolean ignore) {
		this.ignore = ignore;
	}

}
