package sernet.gs.reveng;

// Generated Jun 5, 2015 1:28:30 PM by Hibernate Tools 3.4.0.CR1

/**
 * TmpGefSelId generated by hbm2java
 */
public class TmpGefSelId implements java.io.Serializable {

	private short spid;
	private int gefImpId;
	private int gefId;

	public TmpGefSelId() {
	}

	public TmpGefSelId(short spid, int gefImpId, int gefId) {
		this.spid = spid;
		this.gefImpId = gefImpId;
		this.gefId = gefId;
	}

	public short getSpid() {
		return this.spid;
	}

	public void setSpid(short spid) {
		this.spid = spid;
	}

	public int getGefImpId() {
		return this.gefImpId;
	}

	public void setGefImpId(int gefImpId) {
		this.gefImpId = gefImpId;
	}

	public int getGefId() {
		return this.gefId;
	}

	public void setGefId(int gefId) {
		this.gefId = gefId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TmpGefSelId))
			return false;
		TmpGefSelId castOther = (TmpGefSelId) other;

		return (this.getSpid() == castOther.getSpid())
				&& (this.getGefImpId() == castOther.getGefImpId())
				&& (this.getGefId() == castOther.getGefId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getSpid();
		result = 37 * result + this.getGefImpId();
		result = 37 * result + this.getGefId();
		return result;
	}

}
