package sernet.gs.reveng;

// Generated Jun 5, 2015 1:28:30 PM by Hibernate Tools 3.4.0.CR1

/**
 * TmpMasSelId generated by hbm2java
 */
public class TmpMasSelId implements java.io.Serializable {

	private short spid;
	private int masImpId;
	private int masId;

	public TmpMasSelId() {
	}

	public TmpMasSelId(short spid, int masImpId, int masId) {
		this.spid = spid;
		this.masImpId = masImpId;
		this.masId = masId;
	}

	public short getSpid() {
		return this.spid;
	}

	public void setSpid(short spid) {
		this.spid = spid;
	}

	public int getMasImpId() {
		return this.masImpId;
	}

	public void setMasImpId(int masImpId) {
		this.masImpId = masImpId;
	}

	public int getMasId() {
		return this.masId;
	}

	public void setMasId(int masId) {
		this.masId = masId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TmpMasSelId))
			return false;
		TmpMasSelId castOther = (TmpMasSelId) other;

		return (this.getSpid() == castOther.getSpid())
				&& (this.getMasImpId() == castOther.getMasImpId())
				&& (this.getMasId() == castOther.getMasId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getSpid();
		result = 37 * result + this.getMasImpId();
		result = 37 * result + this.getMasId();
		return result;
	}

}
