package sernet.gs.reveng;

// Generated Jun 5, 2015 1:28:30 PM by Hibernate Tools 3.4.0.CR1

/**
 * TmpRolSel generated by hbm2java
 */
public class TmpRolSel implements java.io.Serializable {

	private TmpRolSelId id;

	public TmpRolSel() {
	}

	public TmpRolSel(TmpRolSelId id) {
		this.id = id;
	}

	public TmpRolSelId getId() {
		return this.id;
	}

	public void setId(TmpRolSelId id) {
		this.id = id;
	}

}
