package sernet.gs.reveng;

// Generated Jun 5, 2015 1:28:30 PM by Hibernate Tools 3.4.0.CR1

/**
 * TmpRepZobbaumasId generated by hbm2java
 */
public class TmpRepZobbaumasId implements java.io.Serializable {

	private int repId;
	private int zobImpId;
	private int zobId;
	private int bauImpId;
	private int bauId;
	private int masImpId;
	private int masId;

	public TmpRepZobbaumasId() {
	}

	public TmpRepZobbaumasId(int repId, int zobImpId, int zobId, int bauImpId,
			int bauId, int masImpId, int masId) {
		this.repId = repId;
		this.zobImpId = zobImpId;
		this.zobId = zobId;
		this.bauImpId = bauImpId;
		this.bauId = bauId;
		this.masImpId = masImpId;
		this.masId = masId;
	}

	public int getRepId() {
		return this.repId;
	}

	public void setRepId(int repId) {
		this.repId = repId;
	}

	public int getZobImpId() {
		return this.zobImpId;
	}

	public void setZobImpId(int zobImpId) {
		this.zobImpId = zobImpId;
	}

	public int getZobId() {
		return this.zobId;
	}

	public void setZobId(int zobId) {
		this.zobId = zobId;
	}

	public int getBauImpId() {
		return this.bauImpId;
	}

	public void setBauImpId(int bauImpId) {
		this.bauImpId = bauImpId;
	}

	public int getBauId() {
		return this.bauId;
	}

	public void setBauId(int bauId) {
		this.bauId = bauId;
	}

	public int getMasImpId() {
		return this.masImpId;
	}

	public void setMasImpId(int masImpId) {
		this.masImpId = masImpId;
	}

	public int getMasId() {
		return this.masId;
	}

	public void setMasId(int masId) {
		this.masId = masId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TmpRepZobbaumasId))
			return false;
		TmpRepZobbaumasId castOther = (TmpRepZobbaumasId) other;

		return (this.getRepId() == castOther.getRepId())
				&& (this.getZobImpId() == castOther.getZobImpId())
				&& (this.getZobId() == castOther.getZobId())
				&& (this.getBauImpId() == castOther.getBauImpId())
				&& (this.getBauId() == castOther.getBauId())
				&& (this.getMasImpId() == castOther.getMasImpId())
				&& (this.getMasId() == castOther.getMasId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getRepId();
		result = 37 * result + this.getZobImpId();
		result = 37 * result + this.getZobId();
		result = 37 * result + this.getBauImpId();
		result = 37 * result + this.getBauId();
		result = 37 * result + this.getMasImpId();
		result = 37 * result + this.getMasId();
		return result;
	}

}
