package sernet.gs.reveng;

// Generated Jun 5, 2015 1:28:30 PM by Hibernate Tools 3.4.0.CR1

/**
 * TmpRepZobId generated by hbm2java
 */
public class TmpRepZobId implements java.io.Serializable {

	private int repId;
	private int zobImpId;
	private int zobId;

	public TmpRepZobId() {
	}

	public TmpRepZobId(int repId, int zobImpId, int zobId) {
		this.repId = repId;
		this.zobImpId = zobImpId;
		this.zobId = zobId;
	}

	public int getRepId() {
		return this.repId;
	}

	public void setRepId(int repId) {
		this.repId = repId;
	}

	public int getZobImpId() {
		return this.zobImpId;
	}

	public void setZobImpId(int zobImpId) {
		this.zobImpId = zobImpId;
	}

	public int getZobId() {
		return this.zobId;
	}

	public void setZobId(int zobId) {
		this.zobId = zobId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TmpRepZobId))
			return false;
		TmpRepZobId castOther = (TmpRepZobId) other;

		return (this.getRepId() == castOther.getRepId())
				&& (this.getZobImpId() == castOther.getZobImpId())
				&& (this.getZobId() == castOther.getZobId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getRepId();
		result = 37 * result + this.getZobImpId();
		result = 37 * result + this.getZobId();
		return result;
	}

}
