package sernet.gs.reveng;

// Generated Jun 5, 2015 1:28:30 PM by Hibernate Tools 3.4.0.CR1

/**
 * TmpRepZobbau generated by hbm2java
 */
public class TmpRepZobbau implements java.io.Serializable {

	private TmpRepZobbauId id;
	private short spid;

	public TmpRepZobbau() {
	}

	public TmpRepZobbau(TmpRepZobbauId id, short spid) {
		this.id = id;
		this.spid = spid;
	}

	public TmpRepZobbauId getId() {
		return this.id;
	}

	public void setId(TmpRepZobbauId id) {
		this.id = id;
	}

	public short getSpid() {
		return this.spid;
	}

	public void setSpid(short spid) {
		this.spid = spid;
	}

}
