package sernet.gs.reveng;

// Generated Jun 5, 2015 1:28:30 PM by Hibernate Tools 3.4.0.CR1

/**
 * TmpZotSel generated by hbm2java
 */
public class TmpZotSel implements java.io.Serializable {

	private TmpZotSelId id;
	private byte rechtZ;
	private byte rechtZb;

	public TmpZotSel() {
	}

	public TmpZotSel(TmpZotSelId id, byte rechtZ, byte rechtZb) {
		this.id = id;
		this.rechtZ = rechtZ;
		this.rechtZb = rechtZb;
	}

	public TmpZotSelId getId() {
		return this.id;
	}

	public void setId(TmpZotSelId id) {
		this.id = id;
	}

	public byte getRechtZ() {
		return this.rechtZ;
	}

	public void setRechtZ(byte rechtZ) {
		this.rechtZ = rechtZ;
	}

	public byte getRechtZb() {
		return this.rechtZb;
	}

	public void setRechtZb(byte rechtZb) {
		this.rechtZb = rechtZb;
	}

}
