package sernet.gs.reveng;

// Generated Jun 5, 2015 1:28:30 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * TmpZusatz generated by hbm2java
 */
public class TmpZusatz implements java.io.Serializable {

	private TmpZusatzId id;
	private String name;
	private Integer dtyId;
	private Short prec;
	private Short scale;
	private Short length;
	private Boolean muss;
	private String wertZeichen;
	private BigDecimal wertWaehrung;
	private Date wertDatum;
	private BigDecimal wertDezimal;
	private Integer wertGanzzahl;
	private Integer waeId;
	private Integer waeImpId;
	private Integer altZusId;
	private Byte loeschen;
	private Integer altZosZusId;

	public TmpZusatz() {
	}

	public TmpZusatz(TmpZusatzId id) {
		this.id = id;
	}

	public TmpZusatz(TmpZusatzId id, String name, Integer dtyId, Short prec,
			Short scale, Short length, Boolean muss, String wertZeichen,
			BigDecimal wertWaehrung, Date wertDatum, BigDecimal wertDezimal,
			Integer wertGanzzahl, Integer waeId, Integer waeImpId,
			Integer altZusId, Byte loeschen, Integer altZosZusId) {
		this.id = id;
		this.name = name;
		this.dtyId = dtyId;
		this.prec = prec;
		this.scale = scale;
		this.length = length;
		this.muss = muss;
		this.wertZeichen = wertZeichen;
		this.wertWaehrung = wertWaehrung;
		this.wertDatum = wertDatum;
		this.wertDezimal = wertDezimal;
		this.wertGanzzahl = wertGanzzahl;
		this.waeId = waeId;
		this.waeImpId = waeImpId;
		this.altZusId = altZusId;
		this.loeschen = loeschen;
		this.altZosZusId = altZosZusId;
	}

	public TmpZusatzId getId() {
		return this.id;
	}

	public void setId(TmpZusatzId id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getDtyId() {
		return this.dtyId;
	}

	public void setDtyId(Integer dtyId) {
		this.dtyId = dtyId;
	}

	public Short getPrec() {
		return this.prec;
	}

	public void setPrec(Short prec) {
		this.prec = prec;
	}

	public Short getScale() {
		return this.scale;
	}

	public void setScale(Short scale) {
		this.scale = scale;
	}

	public Short getLength() {
		return this.length;
	}

	public void setLength(Short length) {
		this.length = length;
	}

	public Boolean getMuss() {
		return this.muss;
	}

	public void setMuss(Boolean muss) {
		this.muss = muss;
	}

	public String getWertZeichen() {
		return this.wertZeichen;
	}

	public void setWertZeichen(String wertZeichen) {
		this.wertZeichen = wertZeichen;
	}

	public BigDecimal getWertWaehrung() {
		return this.wertWaehrung;
	}

	public void setWertWaehrung(BigDecimal wertWaehrung) {
		this.wertWaehrung = wertWaehrung;
	}

	public Date getWertDatum() {
		return this.wertDatum;
	}

	public void setWertDatum(Date wertDatum) {
		this.wertDatum = wertDatum;
	}

	public BigDecimal getWertDezimal() {
		return this.wertDezimal;
	}

	public void setWertDezimal(BigDecimal wertDezimal) {
		this.wertDezimal = wertDezimal;
	}

	public Integer getWertGanzzahl() {
		return this.wertGanzzahl;
	}

	public void setWertGanzzahl(Integer wertGanzzahl) {
		this.wertGanzzahl = wertGanzzahl;
	}

	public Integer getWaeId() {
		return this.waeId;
	}

	public void setWaeId(Integer waeId) {
		this.waeId = waeId;
	}

	public Integer getWaeImpId() {
		return this.waeImpId;
	}

	public void setWaeImpId(Integer waeImpId) {
		this.waeImpId = waeImpId;
	}

	public Integer getAltZusId() {
		return this.altZusId;
	}

	public void setAltZusId(Integer altZusId) {
		this.altZusId = altZusId;
	}

	public Byte getLoeschen() {
		return this.loeschen;
	}

	public void setLoeschen(Byte loeschen) {
		this.loeschen = loeschen;
	}

	public Integer getAltZosZusId() {
		return this.altZosZusId;
	}

	public void setAltZosZusId(Integer altZosZusId) {
		this.altZosZusId = altZosZusId;
	}

}
