#!/bin/sh
# This generates the Java sources out of the WSDL file for the verinice WebService
# 
# Prior to running this command make sure that you have the 'wsdl2java' script from
# *Apache CXF* in your path.
#
wsdl2java -d srcGenerated/ -server -verbose src/sernet/verinice/service/sync/sync-service.wsdl
