------------------------
-- PRIMARY KEYS, INDICES
------------------------

-- ALLGEFAEHRDUNGSUMSETZUNGEN
CREATE INDEX SQL101119172940880 ON "APP"."ALLGEFAEHRDUNGSUMSETZUNGEN"(ELT);
CREATE INDEX SQL101119172940830 ON "APP"."ALLGEFAEHRDUNGSUMSETZUNGEN"(RISKANALYSISLISTS_ID1);
ALTER TABLE ALLGEFAEHRDUNGSUMSETZUNGEN ADD PRIMARY KEY (RISKANALYSISLISTS_ID1,IDX1);

--ASSOCIATEDGEFAEHRDUNGEN
CREATE INDEX SQL101119172941000 ON "APP"."ASSOCIATEDGEFAEHRDUNGEN"(ELT);
ALTER TABLE ASSOCIATEDGEFAEHRDUNGEN ADD PRIMARY KEY (RISKANALYSISLISTS_ID2,IDX2);

--BAUSTEINVORSCHLAG
ALTER TABLE BAUSTEINVORSCHLAG ADD PRIMARY KEY (DBID);

--CHANGELOGENTRY
ALTER TABLE CHANGELOGENTRY ADD PRIMARY KEY (DBID);

--CNALINK
CREATE INDEX SQL101119172941140 ON "APP"."CNALINK"(DEPENDENCY_ID);
CREATE INDEX SQL101119172941080 ON "APP"."CNALINK"(DEPENDANT_ID);
ALTER TABLE CNALINK ADD PRIMARY KEY (DEPENDANT_ID,DEPENDENCY_ID,TYPE_ID);

--CNATREEELEMENT
CREATE INDEX SQL101119172941210 ON "APP"."CNATREEELEMENT"(PARENT);
CREATE INDEX SQL101119172941170 ON "APP"."CNATREEELEMENT"(ENTITY_ID);
ALTER TABLE CNATREEELEMENT ADD PRIMARY KEY (DBID);

--CONFIGURATION
CREATE INDEX SQL101119172941260 ON "APP"."CONFIGURATION"(ENTITY_ID);
CREATE INDEX SQL101119172941300 ON "APP"."CONFIGURATION"(PERSON_ID);
ALTER TABLE CONFIGURATION ADD PRIMARY KEY (DBID);

-- ENTITY
ALTER TABLE ENTITY ADD PRIMARY KEY (DBID);

--"FINISHEDRISKANALYSISLISTS"
ALTER TABLE FINISHEDRISKANALYSISLISTS ADD PRIMARY KEY (DBID);

-- "GEFAEHRDUNG"
ALTER TABLE GEFAEHRDUNG ADD PRIMARY KEY (DBID);

-- NOTE
ALTER TABLE NOTE ADD PRIMARY KEY (DBID);
CREATE INDEX SQL101119172941370 ON "APP"."NOTE"(ENTITY_ID);

-- NOTOKGEFAEHRDUNGSUMSETZUNGEN
CREATE INDEX SQL101119172941430 ON "APP"."NOTOKGEFAEHRDUNGSUMSETZUNGEN"(RISKANALYSISLISTS_ID3);
CREATE INDEX SQL101119172941460 ON "APP"."NOTOKGEFAEHRDUNGSUMSETZUNGEN"(ELT);
ALTER TABLE NOTOKGEFAEHRDUNGSUMSETZUNGEN ADD PRIMARY KEY (RISKANALYSISLISTS_ID3,IDX3);

-- "OWNGEFAEHRDUNG"
ALTER TABLE OWNGEFAEHRDUNG ADD PRIMARY KEY (DBID);

-- PERMISSION
ALTER TABLE PERMISSION ADD PRIMARY KEY (DBID);
CREATE INDEX SQL101119172941510 ON "APP"."PERMISSION"(CTE_ID);

--PROPERTIES
ALTER TABLE PROPERTIES ADD PRIMARY KEY (PROPERTIES_ID,PROPERTIES_IDX);
CREATE INDEX SQL101119172941560 ON "APP"."PROPERTIES"(PROPERTIES_ID);

--PROPERTYLIST
ALTER TABLE PROPERTYLIST ADD PRIMARY KEY (DBID);
CREATE INDEX SQL101119172941610 ON "APP"."PROPERTYLIST"(TYPEDLIST_ID);

--RISIKOMASSNAHME
ALTER TABLE RISIKOMASSNAHME ADD PRIMARY KEY (DBID);

---------------
-- FOREIGN KEYS
---------------

--ALLGEFAEHRDUNGSUMSETZUNGEN
ALTER TABLE "APP"."ALLGEFAEHRDUNGSUMSETZUNGEN"
ADD CONSTRAINT FK861776933016EFB8
FOREIGN KEY (RISKANALYSISLISTS_ID1)
REFERENCES "APP"."FINISHEDRISKANALYSISLISTS"(DBID);

ALTER TABLE "APP"."ALLGEFAEHRDUNGSUMSETZUNGEN"
ADD CONSTRAINT FK86177693D66C9577
FOREIGN KEY (ELT)
REFERENCES "APP"."CNATREEELEMENT"(DBID);

-- FINISHEDRISKANALYSISLISTS
ALTER TABLE "APP"."ASSOCIATEDGEFAEHRDUNGEN"
ADD CONSTRAINT FK152D4BE3D66C9577
FOREIGN KEY (ELT)
REFERENCES "APP"."CNATREEELEMENT"(DBID);

ALTER TABLE "APP"."ASSOCIATEDGEFAEHRDUNGEN"
ADD CONSTRAINT FK152D4BE33016EFB9
FOREIGN KEY (RISKANALYSISLISTS_ID2)
REFERENCES "APP"."FINISHEDRISKANALYSISLISTS"(DBID);

--CNALINK
ALTER TABLE "APP"."CNALINK"
ADD CONSTRAINT FK3647965079C64E9B
FOREIGN KEY (DEPENDENCY_ID)
REFERENCES "APP"."CNATREEELEMENT"(DBID);
ALTER TABLE "APP"."CNALINK"
ADD CONSTRAINT FK36479650EE21A7EB
FOREIGN KEY (DEPENDANT_ID)
REFERENCES "APP"."CNATREEELEMENT"(DBID);

--CNATREEELEMENT
ALTER TABLE "APP"."CNATREEELEMENT"
ADD CONSTRAINT FK17706A888A5411FE
FOREIGN KEY (ENTITY_ID)
REFERENCES "APP"."ENTITY"(DBID);
ALTER TABLE "APP"."CNATREEELEMENT"
ADD CONSTRAINT FK17706A889B9180B6
FOREIGN KEY (PARENT)
REFERENCES "APP"."CNATREEELEMENT"(DBID);

--CONFIGURATION
ALTER TABLE "APP"."CONFIGURATION"
ADD CONSTRAINT FK733374F68A5411FE
FOREIGN KEY (ENTITY_ID)
REFERENCES "APP"."ENTITY"(DBID);
ALTER TABLE "APP"."CONFIGURATION"
ADD CONSTRAINT FK733374F6AF34D1AF
FOREIGN KEY (PERSON_ID)
REFERENCES "APP"."CNATREEELEMENT"(DBID);

--NOTE
ALTER TABLE "APP"."NOTE"
ADD CONSTRAINT FK33AFF28A5411FE
FOREIGN KEY (ENTITY_ID)
REFERENCES "APP"."ENTITY"(DBID);

-- NOTOKGEFAEHRDUNGSUMSETZUNGEN
ALTER TABLE "APP"."NOTOKGEFAEHRDUNGSUMSETZUNGEN"
ADD CONSTRAINT FK8DBF68853016EFBA
FOREIGN KEY (RISKANALYSISLISTS_ID3)
REFERENCES "APP"."FINISHEDRISKANALYSISLISTS"(DBID);
ALTER TABLE "APP"."NOTOKGEFAEHRDUNGSUMSETZUNGEN"
ADD CONSTRAINT FK8DBF6885D66C9577
FOREIGN KEY (ELT)
REFERENCES "APP"."CNATREEELEMENT"(DBID);

--OWNGEFAEHRDUNG
ALTER TABLE "APP"."OWNGEFAEHRDUNG"
ADD CONSTRAINT FK6BBE5B3A16C4A0C3
FOREIGN KEY (DBID)
REFERENCES "APP"."GEFAEHRDUNG"(DBID);

--PERMISSION
ALTER TABLE "APP"."PERMISSION"
ADD CONSTRAINT FKE125C5CF86683F32
FOREIGN KEY (CTE_ID)
REFERENCES "APP"."CNATREEELEMENT"(DBID);

--PROPERTIES
ALTER TABLE "APP"."PROPERTIES"
ADD CONSTRAINT FKC8CD8D3329BC67DE
FOREIGN KEY (PROPERTIES_ID)
REFERENCES "APP"."PROPERTYLIST"(DBID);

-- PROPERTYLIST
ALTER TABLE "APP"."PROPERTYLIST"
ADD CONSTRAINT FKCC839BF390FF03B9
FOREIGN KEY (TYPEDLIST_ID)
REFERENCES "APP"."ENTITY"(DBID);
